# scripts/data_a2.py
# Nivel A2: 750 palabras esenciales SIELE
# Formato: (palabra, categoría_gramatical, significado_chino, categoría_temática, ejemplo_es, ejemplo_zh)

A2_WORDS = [
    # --- El cuerpo humano y anatomía ---
    ("cabeza", "f.", "头，头部", "daily"),
    ("cara", "f.", "脸庞，面容", "daily"),
    ("frente", "f.", "额头", "daily"),
    ("ojo", "m.", "眼睛", "daily"),
    ("ceja", "f.", "眉毛", "daily"),
    ("pestaña", "f.", "睫毛", "daily"),
    ("nariz", "f.", "鼻子", "daily"),
    ("mejilla", "f.", "面颊，脸蛋", "daily"),
    ("boca", "f.", "嘴巴", "daily"),
    ("labio", "m.", "嘴唇", "daily"),
    ("diente", "m.", "牙齿", "daily"),
    ("muela", "f.", "臼齿，大牙", "daily"),
    ("lengua", "f.", "舌头", "daily"),
    ("barbilla", "f.", "下巴", "daily"),
    ("oreja", "f.", "耳朵（外耳）", "daily"),
    ("oído", "m.", "听觉，内耳", "daily"),
    ("pelo", "m.", "头发，毛发", "daily"),
    ("cabello", "m.", "发丝，头发", "daily"),
    ("cuello", "m.", "颈部，脖子", "daily"),
    ("garganta", "f.", "咽喉，喉咙", "daily"),
    ("hombro", "m.", "肩膀", "daily"),
    ("brazo", "m.", "手臂", "daily"),
    ("codo", "m.", "手肘", "daily"),
    ("muñeca", "f.", "手腕；洋娃娃", "daily"),
    ("mano", "f.", "手", "daily"),
    ("dedo", "m.", "手指，脚趾", "daily"),
    ("uña", "f.", "指甲", "daily"),
    ("pecho", "m.", "胸膛，胸部", "daily"),
    ("espalda", "f.", "后背，背部", "daily"),
    ("columna", "f.", "脊椎，柱子", "daily"),
    ("cintura", "f.", "腰部", "daily"),
    ("barriga", "f.", "肚子，腹部", "daily"),
    ("vientre", "m.", "小腹", "daily"),
    ("estómago", "m.", "胃部", "daily"),
    ("corazón", "m.", "心脏；内心", "daily"),
    ("pulmón", "m.", "肺脏", "daily"),
    ("hígado", "m.", "肝脏", "daily"),
    ("riñón", "m.", "肾脏", "daily"),
    ("cadera", "f.", "臀部，髋部", "daily"),
    ("pierna", "f.", "小腿，整腿", "daily"),
    ("muslo", "m.", "大腿", "daily"),
    ("rodilla", "f.", "膝盖", "daily"),
    ("tobillo", "m.", "脚踝", "daily"),
    ("pie", "m.", "脚掌，足部", "daily"),
    ("talón", "m.", "脚后跟", "daily"),
    ("piel", "f.", "皮肤，皮层", "daily"),
    ("hueso", "m.", "骨骼，骨头", "daily"),
    ("músculo", "m.", "肌肉", "daily"),
    ("sangre", "f.", "血液", "daily"),
    ("vena", "f.", "静脉血管", "daily"),
    ("cerebro", "m.", "大脑", "daily"),
    ("nervio", "m.", "神经", "daily"),
    ("voz", "f.", "声音，嗓音", "daily"),
    ("aliento", "m.", "呼吸，气息", "daily"),

    # --- Salud, síntomas y medicina ---
    ("salud", "f.", "健康状况", "daily"),
    ("enfermedad", "f.", "疾病，病症", "daily"),
    ("dolor", "m.", "疼痛，痛楚", "daily"),
    ("fiebre", "f.", "发烧，体温过高", "daily"),
    ("gripe", "f.", "流行性感冒", "daily"),
    ("resfriado", "m.", "普通感冒，着凉", "daily"),
    ("catarro", "m.", "上呼吸道感染", "daily"),
    ("tos", "f.", "咳嗽", "daily"),
    ("estornudo", "m.", "喷嚏", "daily"),
    ("herida", "f.", "外伤，创口", "daily"),
    ("corte", "m.", "刀划伤", "daily"),
    ("quemadura", "f.", "烫伤，烧伤", "daily"),
    ("golpe", "m.", "撞击，淤青", "daily"),
    ("fractura", "f.", "骨折", "daily"),
    ("esguince", "m.", "扭伤", "daily"),
    ("alergia", "f.", "过敏反应", "daily"),
    ("picadura", "f.", "蚊虫叮咬", "daily"),
    ("infección", "f.", "感染，发炎", "daily"),
    ("inflamación", "f.", "红肿发炎", "daily"),
    ("mareo", "m.", "头晕目眩", "daily"),
    ("náuseas", "f.pl.", "恶心欲呕", "daily"),
    ("vómito", "m.", "呕吐物", "daily"),
    ("diarrea", "f.", "腹泻，拉肚子", "daily"),
    ("estreñimiento", "m.", "便秘", "daily"),
    ("insomnio", "m.", "失眠症", "daily"),
    ("estrés", "m.", "精神压力", "emotion"),
    ("ansiedad", "f.", "焦虑抑郁", "emotion"),
    ("cansancio", "m.", "疲劳倦怠", "daily"),
    ("fatiga", "f.", "过度疲乏", "daily"),
    ("peso", "m.", "体重，重量", "daily"),
    ("altura", "f.", "身长身高", "daily"),
    ("tensión", "f.", "血压；紧张", "daily"),
    ("pulso", "m.", "脉搏", "daily"),
    ("temperatura", "f.", "身体温度", "daily"),
    ("síntoma", "m.", "病状反应", "daily"),
    ("diagnóstico", "m.", "医生诊断", "daily"),
    ("tratamiento", "m.", "疗程对策", "daily"),
    ("cura", "f./m.", "治愈；神父", "daily"),
    ("receta", "f.", "处方笺；烹饪菜谱", "daily"),
    ("medicina", "f.", "药物；医学", "daily"),
    ("medicamento", "m.", "药剂", "daily"),
    ("fármaco", "m.", "药品", "daily"),
    ("pastilla", "f.", "药丸，片剂", "daily"),
    ("comprimido", "m.", "压制药片", "daily"),
    ("cápsula", "f.", "胶囊丸", "daily"),
    ("jarabe", "m.", "止咳糖浆", "daily"),
    ("gotas", "f.pl.", "眼药滴剂", "daily"),
    ("pomada", "f.", "软膏药膏", "daily"),
    ("crema", "f.", "护肤霜；奶油", "daily"),
    ("tirita", "f.", "创口贴", "daily"),
    ("venda", "f.", "医用绷带", "daily"),
    ("gasa", "f.", "消毒纱布", "daily"),
    ("algodón", "m.", "医用脱脂棉", "daily"),
    ("alcohol", "m.", "医用酒精", "daily"),
    ("inyección", "f.", "注射打针", "daily"),
    ("vacuna", "f.", "预防疫苗", "daily"),
    ("suero", "m.", "生理盐水输液", "daily"),
    ("termómetro", "m.", "体温计", "daily"),
    ("muletas", "f.pl.", "双腋拐杖", "daily"),
    ("silla de ruedas", "f.", "轮椅", "daily"),
    ("ambulancia", "f.", "急救救护车", "daily"),
    ("urgencias", "f.pl.", "急诊室", "daily"),
    ("consulta", "f.", "问诊诊室", "daily"),
    ("quirófano", "m.", "外科手术室", "daily"),
    ("operación", "f.", "外科手术", "daily"),
    ("cirugía", "f.", "外科学", "daily"),
    ("paciente", "m./f./adj.", "就诊病患；有耐心的", "daily"),
    ("dentista", "m./f.", "牙科医生", "daily"),
    ("farmacéutico", "m.", "药剂师", "daily"),
    ("especialista", "m./f.", "专科医师", "daily"),
    ("cita previa", "f.", "事先门诊预约", "daily"),

    # --- Compras, tiendas y servicios ---
    ("comercio", "m.", "商业，贸易，店铺", "business"),
    ("tienda", "f.", "零售店铺", "daily"),
    ("gran almacén", "m.", "大型百货商场", "daily"),
    ("centro comercial", "m.", "商业购物中心", "daily"),
    ("supermercado", "m.", "自选超市", "daily"),
    ("hipermercado", "m.", "超大型卖场", "daily"),
    ("mercado", "m.", "传统菜市", "daily"),
    ("mercadillo", "m.", "露天跳蚤集市", "daily"),
    ("panadería", "f.", "面包烘焙坊", "food"),
    ("pastelería", "f.", "西点甜品店", "food"),
    ("carnicería", "f.", "生鲜肉铺", "food"),
    ("pescadería", "f.", "海产鱼档", "food"),
    ("frutería", "f.", "鲜果摊铺", "food"),
    ("verdulería", "f.", "蔬菜行", "food"),
    ("charcutería", "f.", "熟食火腿店", "food"),
    ("farmacia", "f.", "处方药房", "daily"),
    ("óptica", "f.", "验光眼镜行", "daily"),
    ("zapatería", "f.", "鞋店", "daily"),
    ("tienda de ropa", "f.", "成衣服装店", "daily"),
    ("joyería", "f.", "金银珠宝首饰店", "daily"),
    ("perfumería", "f.", "香水化妆品店", "daily"),
    ("peluquería", "f.", "美发沙龙", "daily"),
    ("librería", "f.", "新华书店", "daily"),
    ("papelería", "f.", "办公文具店", "daily"),
    ("quiosco", "m.", "报刊小亭", "daily"),
    ("estanco", "m.", "烟草邮票专卖店", "daily"),
    ("ferretería", "f.", "五金建材行", "daily"),
    ("floristería", "f.", "花艺店", "daily"),
    ("tintorería", "f.", "干洗店", "daily"),
    ("lavandería", "f.", "自助洗衣房", "daily"),
    ("taller", "m.", "修车工坊", "daily"),
    ("escaparate", "m.", "临街橱窗", "daily"),
    ("mostrador", "m.", "服务接待柜台", "daily"),
    ("estante", "m.", "货架置物板", "daily"),
    ("probador", "m.", "试衣间", "daily"),
    ("espejo", "m.", "穿衣镜", "daily"),
    ("caja", "f.", "收银结账通道", "daily"),
    ("cajero", "m.", "收银员；取款机", "daily"),
    ("cajero automático", "m.", "ATM自动取款机", "business"),
    ("cliente", "m./f.", "光临主顾", "business"),
    ("consumidor", "m.", "终端消费者", "business"),
    ("dependiente", "m.", "专柜导购员", "daily"),
    ("cola", "f.", "排队队伍", "daily"),
    ("turno", "m.", "叫号排期", "daily"),
    ("tique", "m.", "收银小票", "daily"),
    ("recibo", "m.", "缴费收据", "daily"),
    ("factura", "f.", "增值发票", "business"),
    ("garantía", "f.", "售后质保", "business"),
    ("precio", "m.", "明码标价", "daily"),
    ("rebajas", "f.pl.", "季末大减价", "daily"),
    ("descuento", "m.", "价格折让", "daily"),
    ("oferta", "f.", "限时促销优惠", "daily"),
    ("ganga", "f.", "捡漏廉价物", "daily"),
    ("chollo", "m.", "划算合算美差", "daily"),
    ("liquidación", "f.", "清仓甩卖", "business"),
    ("devolución", "f.", "退货退款", "daily"),
    ("cambio", "m.", "换货；外币找零", "daily"),
    ("efectivo", "m.", "纸币现金", "business"),
    ("tarjeta de crédito", "f.", "透支信用卡", "business"),
    ("tarjeta de débito", "f.", "储蓄借记卡", "business"),
    ("moneda", "f.", "硬币；币种", "business"),
    ("billete", "m.", "大面额纸钞", "business"),
    ("suelto", "m./adj.", "零钱散钱；松散的", "daily"),
    ("cambio", "m.", "零钱，找回差额", "daily"),

    # --- Restaurante y gastronomía avanzada ---
    ("restaurante", "m.", "正餐餐馆", "food"),
    ("mesón", "m.", "西班牙传统客栈酒肆", "food"),
    ("taberna", "f.", "平民小酒馆", "food"),
    ("chiringuito", "m.", "沙滩露天大排档", "food"),
    ("terraza", "f.", "街边外摆露天座", "food"),
    ("camarero", "m.", "侍者，跑堂", "food"),
    ("cocinero", "m.", "主勺大厨", "food"),
    ("chef", "m.", "主厨掌厨", "food"),
    ("comensal", "m.", "同桌食客", "food"),
    ("reserva", "f.", "餐桌订位", "food"),
    ("menú del día", "m.", "工作日实惠午市套餐", "food"),
    ("carta de vinos", "f.", "品鉴酒单", "food"),
    ("aperitivo", "m.", "餐前开胃点心", "food"),
    ("tapa", "f.", "经典下酒小菜", "food"),
    ("pincho", "m.", "巴斯克竹签串小食", "food"),
    ("montadito", "m.", "烤酥小圆包夹肉", "food"),
    ("ración", "f.", "整份热菜盘", "food"),
    ("media ración", "f.", "半份菜盘", "food"),
    ("primer plato", "m.", "第一道头盘（汤/沙拉/面）", "food"),
    ("segundo plato", "m.", "第二道硬菜（肉/鱼）", "food"),
    ("guarnición", "f.", "盘边配菜（薯条/时蔬）", "food"),
    ("postre", "m.", "甜点收尾", "food"),
    ("sobremesa", "f.", "饭后围坐闲聊时光", "food"),
    ("chupito", "m.", "一口闷烈酒小杯", "food"),
    ("propina", "f.", "赏钱小费", "food"),
    ("cuenta", "f.", "用餐消费总单", "food"),
    ("especialidad", "f.", "招牌当家菜", "food"),
    ("ingrediente", "m.", "烹饪原材", "food"),
    ("receta", "f.", "烹饪秘方", "food"),
    ("sabor", "m.", "口感滋味", "food"),
    ("olor", "m.", "气味芳香", "food"),
    ("gusto", "m.", "味蕾味觉", "food"),
    ("asado", "adj./m.", "炭烤烘烤的", "food"),
    ("frito", "adj.", "滚油煎炸的", "food"),
    ("cocido", "adj./m.", "慢火慢炖的；马德里乱炖", "food"),
    ("hervido", "adj.", "清水煮透的", "food"),
    ("a la plancha", "exp.", "无油铁板扒烤", "food"),
    ("al vapor", "exp.", "蒸笼汽蒸", "food"),
    ("al horno", "exp.", "进烤箱烘焙", "food"),
    ("crudo", "adj.", "生鲜未烹熟的", "food"),
    ("poco hecho", "exp.", "三分熟，嫩带血丝", "food"),
    ("al punto", "exp.", "五至七分熟，恰到火候", "food"),
    ("muy hecho", "exp.", "全熟熟透", "food"),
    ("quemado", "adj.", "焦糊过火", "food"),
    ("picante", "adj.", "辛辣带劲", "food"),
    ("dulce", "adj.", "甘美怡人", "food"),
    ("salado", "adj.", "过咸重口味", "food"),
    ("amargo", "adj.", "苦口", "food"),
    ("ácido", "adj.", "泛酸柠檬味", "food"),
    ("soso", "adj.", "寡淡缺盐", "food"),
    ("grasiento", "adj.", "油腻荤腥", "food"),
    ("pesado", "adj.", "胀肚难消化", "food"),
    ("ligero", "adj.", "轻盈清爽", "food"),
    ("casero", "adj.", "家常纯手工自制", "food"),
    ("artesanal", "adj.", "古法匠心制作", "food"),

    # --- Viajes, transportes y hoteles ---
    ("viaje", "m.", "长途行程", "travel"),
    ("viajero", "m.", "旅者行客", "travel"),
    ("turismo", "m.", "观光旅游业", "travel"),
    ("vacaciones", "f.pl.", "休假假期", "travel"),
    ("excursión", "f.", "短途远足郊游", "travel"),
    ("guía turístico", "m.", "随团导游", "travel"),
    ("itinerario", "m.", "游历路线图", "travel"),
    ("destino", "m.", "抵达目的地", "travel"),
    ("equipaje", "m.", "随行行李", "travel"),
    ("maleta", "f.", "拉杆皮箱", "travel"),
    ("mochila", "f.", "双肩户外包", "travel"),
    ("bolso de mano", "m.", "随身小包", "travel"),
    ("pasaporte", "m.", "出入境护照", "travel"),
    ("visado", "m.", "大使馆签证", "travel"),
    ("billete de ida", "m.", "单程客票", "travel"),
    ("billete de ida y vuelta", "m.", "往返双程票", "travel"),
    ("abono transporte", "m.", "公共交通周/月卡", "travel"),
    ("andén", "m.", "列车月台", "travel"),
    ("vía", "f.", "铁轨轨道", "travel"),
    ("taquilla", "f.", "人工售票窗口", "travel"),
    ("revisor", "m.", "列车查票验票员", "travel"),
    ("vagón", "m.", "列车节厢", "travel"),
    ("asiento", "m.", "客舱坐席", "travel"),
    ("plaza", "f.", "车厢空位；席位", "travel"),
    ("pasillo", "m.", "过道排座", "travel"),
    ("ventanilla", "f.", "靠窗机位席", "travel"),
    ("retraso", "m.", "航班列车延误", "travel"),
    ("puntual", "adj.", "严守时刻准点", "travel"),
    ("salida", "f.", "列车发车；航班离港", "travel"),
    ("llegada", "f.", "到站抵达", "travel"),
    ("escala", "f.", "中途转机经停", "travel"),
    ("transbordo", "m.", "站内换乘", "travel"),
    ("aeropuerto", "m.", "民航飞机场", "travel"),
    ("terminal", "f.", "航站楼航厦", "travel"),
    ("mostrador", "m.", "值机办票岛台", "travel"),
    ("facturación", "f.", "行李托运及办票", "travel"),
    ("tarjeta de embarque", "f.", "登机凭证", "travel"),
    ("puerta de embarque", "f.", "登机口闸门", "travel"),
    ("control de seguridad", "m.", "随身行李安检", "travel"),
    ("aduana", "f.", "海关申报署", "travel"),
    ("despegue", "m.", "机轮离地起飞", "travel"),
    ("aterrizaje", "m.", "触地降落滑行", "travel"),
    ("vuelo", "m.", "定期航班", "travel"),
    ("azafata", "f.", "民航空姐空乘", "travel"),
    ("piloto", "m.", "机长飞行员", "travel"),
    ("cinturón de seguridad", "m.", "安全带", "travel"),
    ("chaleco salvavidas", "m.", "应急救生背心", "travel"),
    ("hotel", "m.", "星级宾馆饭店", "travel"),
    ("hostal", "m.", "温馨小招待所", "travel"),
    ("pensión", "f.", "包饭经济客栈", "travel"),
    ("albergue", "m.", "青年旅舍", "travel"),
    ("casa rural", "f.", "原生态乡村民宿", "travel"),
    ("camping", "m.", "野外露营地", "travel"),
    ("recepción", "f.", "大堂总台", "travel"),
    ("recepcionista", "m./f.", "前台接待员", "travel"),
    ("reserva", "f.", "客房预留登记", "travel"),
    ("habitación individual", "f.", "单人标准间", "travel"),
    ("habitación doble", "f.", "双人标准间", "travel"),
    ("cama de matrimonio", "f.", "大号双人床", "travel"),
    ("vistas al mar", "f.pl.", "全海景房", "travel"),
    ("pensión completa", "f.", "全包一日三餐", "travel"),
    ("media pensión", "f.", "半包早晚两餐", "travel"),
    ("alojamiento y desayuno", "m.", "含宿并早点", "travel"),
    ("clave de wifi", "f.", "无线网络密码", "travel"),
    ("llave electrónica", "f.", "磁条门禁房卡", "travel"),
    ("consigna", "f.", "行李寄放寄存处", "travel"),

    # --- Meteorología y clima A2 ---
    ("clima", "m.", "宏观气候", "travel"),
    ("tiempo atmosférico", "m.", "气象天气", "travel"),
    ("pronóstico", "m.", "天气预报预测", "travel"),
    ("previsión", "f.", "未来气候展望", "travel"),
    ("temperatura", "f.", "大气气温", "travel"),
    ("grado", "m.", "摄氏度数", "travel"),
    ("bajo cero", "exp.", "零度以下极寒", "travel"),
    ("caluroso", "adj.", "骄阳炙烤燥热", "travel"),
    ("frío", "adj./m.", "凛冽寒气", "travel"),
    ("fresco", "adj.", "微风清凉", "travel"),
    ("templado", "adj.", "四季宜人温和", "travel"),
    ("soleado", "adj.", "晴空万里阳光普照", "travel"),
    ("despejado", "adj.", "云消雾散碧空", "travel"),
    ("nublado", "adj.", "阴沉多云密布", "travel"),
    ("cubierto", "adj.", "铅云遮天蔽日", "travel"),
    ("lluvia", "f.", "甘霖降雨", "travel"),
    ("chubasco", "m.", "阵雨骤雨", "travel"),
    ("chaparrón", "m.", "暴雨倾盆大雨", "travel"),
    ("tormenta", "f.", "雷暴电闪雷鸣", "travel"),
    ("trueno", "m.", "隆隆雷声", "travel"),
    ("relámpago", "m.", "撕裂长空闪电", "travel"),
    ("rayo", "m.", "劈落雷霆电光", "travel"),
    ("granizo", "m.", "冰雹冰丸", "travel"),
    ("nieve", "f.", "鹅毛白雪", "travel"),
    ("helada", "f.", "地表霜冻", "travel"),
    ("hielo", "m.", "结冰坚冰", "travel"),
    ("niebla", "f.", "弥漫大雾", "travel"),
    ("bruma", "f.", "水上晨曦薄雾", "travel"),
    ("viento", "m.", "劲吹风势", "travel"),
    ("aire", "m.", "空气；清风", "travel"),
    ("brisa", "f.", "拂面和煦微风", "travel"),
    ("humedad", "f.", "空气相对湿度", "travel"),
    ("seco", "adj.", "干旱干燥缺水", "travel"),
    ("húmedo", "adj.", "湿漉漉潮润", "travel"),
    ("arcoíris", "m.", "雨后绚丽彩虹", "travel"),

    # --- Ocio, deportes y aficiones A2 ---
    ("ocio", "m.", "闲暇消遣时光", "daily"),
    ("tiempo libre", "m.", "工作之余空闲", "daily"),
    ("afición", "f.", "个人嗜好癖好", "daily"),
    ("deporte", "m.", "体育竞技锻炼", "daily"),
    ("gimnasio", "m.", "健身俱乐部房", "daily"),
    ("entrenamiento", "m.", "专项日常训练", "daily"),
    ("entrenador", "m.", "带队主教练", "daily"),
    ("jugador", "m.", "场上选手球员", "daily"),
    ("árbitro", "m.", "执法主裁判", "daily"),
    ("partido", "m.", "对抗球赛；政党", "daily"),
    ("campeonato", "m.", "锦标联赛盛会", "daily"),
    ("torneo", "m.", "巡回排位赛", "daily"),
    ("victoria", "f.", "夺冠胜利捷报", "daily"),
    ("derrota", "f.", "败北遗憾失利", "daily"),
    ("empate", "m.", "双方平局握手", "daily"),
    ("gol", "m.", "皮球破门得分", "daily"),
    ("punto", "m.", "计分点数", "daily"),
    ("fútbol", "m.", "十一人制绿茵足球", "daily"),
    ("baloncesto", "m.", "五人篮球竞技", "daily"),
    ("balonmano", "m.", "手球对抗运动", "daily"),
    ("voleibol", "m.", "排球拦网扣杀", "daily"),
    ("tenis", "m.", "草地/红土网球", "daily"),
    ("pádel", "m.", "笼式板网球", "daily"),
    ("atletismo", "m.", "田径赛跑跳投", "daily"),
    ("ciclismo", "m.", "公路自行车拉练", "daily"),
    ("natación", "f.", "池水泳道竞速", "daily"),
    ("gimnasia", "f.", "形体艺术体操", "daily"),
    ("esquí", "m.", "高山雪板滑雪", "daily"),
    ("patinaje", "m.", "旱冰及真冰滑行", "daily"),
    ("vela", "f.", "帆船乘风破浪；蜡烛", "daily"),
    ("surf", "m.", "搏击海浪冲浪", "daily"),
    ("buceo", "m.", "背氧气瓶潜水", "daily"),
    ("senderismo", "m.", "青山绿道徒步", "daily"),
    ("escalada", "f.", "徒手攀岩绝壁", "daily"),
    ("pesca", "f.", "垂钓江河渔业", "daily"),
    ("caza", "f.", "山林围猎打猎", "daily"),
    ("música", "f.", "悦耳旋律音乐", "daily"),
    ("concierto", "m.", "现场交响音乐会", "daily"),
    ("festival", "m.", "露天狂欢音乐节", "daily"),
    ("canción", "f.", "单曲旋律歌词", "daily"),
    ("disco", "m.", "唱片实体大碟", "daily"),
    ("guitarra", "f.", "六弦西班牙吉他", "daily"),
    ("piano", "m.", "黑白键盘钢琴", "daily"),
    ("violín", "m.", "提琴小提琴拉弦", "daily"),
    ("batería", "f.", "架子鼓打击乐；电池", "daily"),
    ("flauta", "f.", "悠扬吹奏横笛", "daily"),
    ("cine", "m.", "大荧幕电影院", "daily"),
    ("película", "f.", "影视故事胶片", "daily"),
    ("estreno", "m.", "全球同步首映", "daily"),
    ("butaca", "f.", "剧场软座排椅", "daily"),
    ("fila", "f.", "坐席第几横排", "daily"),
    ("pantalla", "f.", "巨幕白幕放映", "daily"),
    ("palomitas", "f.pl.", "膨化黄油爆米花", "daily"),
    ("teatro", "m.", "古典话剧院", "daily"),
    ("obra de teatro", "f.", "舞台幕布戏剧", "daily"),
    ("actor", "m.", "担纲男主演", "daily"),
    ("actriz", "f.", "实力派女主角", "daily"),
    ("director", "m.", "掌镜总导演", "daily"),
    ("museo", "m.", "藏品展览博物馆", "travel"),
    ("exposición", "f.", "名作巡回专题展", "travel"),
    ("galería", "f.", "私立艺术画廊", "travel"),
    ("cuadro", "m.", "画布油画精装", "daily"),
    ("escultura", "f.", "石雕泥塑三维", "daily"),
    ("fotografía", "f.", "光学暗房摄影", "daily"),
    ("foto", "f.", "生活胶卷抓拍", "daily"),

    # --- Verbos de acción y rutina diaria A2 ---
    ("despertarse", "v.", "拂晓苏醒睁眼", "daily"),
    ("levantarse", "v.", "翻身掀被起床", "daily"),
    ("lavarse", "v.", "清水冲面洗手", "daily"),
    ("ducharse", "v.", "莲蓬喷头沐浴", "daily"),
    ("bañarse", "v.", "浴缸温水浸泡", "daily"),
    ("secarse", "v.", "浴巾拂拭吸水", "daily"),
    ("peinarse", "v.", "执梳打理头发", "daily"),
    ("afeitarse", "v.", "刮胡刀剃面须", "daily"),
    ("maquillarse", "v.", "轻敷脂粉施妆", "daily"),
    ("vestirse", "v.", "穿戴整齐衣着", "daily"),
    ("ponerse", "v.", "戴上饰物；变得", "daily"),
    ("quitarse", "v.", "宽衣解带脱鞋", "daily"),
    ("acostarse", "v.", "息灯合眼就寝", "daily"),
    ("dormirse", "v.", "不知不觉入眠", "daily"),
    ("soñar", "v.", "梦回神游；怀揣梦想", "emotion"),
    ("acordarse", "v.", "脑海蓦然记起", "daily"),
    ("recordar", "v.", "深切忆及缅怀", "daily"),
    ("olvidar", "v.", "忘却抛诸脑后", "daily"),
    ("olvidarse", "v.", "不小心疏忽遗忘", "daily"),
    ("sentirse", "v.", "自身体感状况", "emotion"),
    ("parecerse", "v.", "容貌性情神似", "daily"),
    ("doler", "v.", "机体局部作痛", "daily"),
    ("preocuparse", "v.", "焦心牵挂担忧", "emotion"),
    ("alegrarse", "v.", "欣慰开怀一笑", "emotion"),
    ("enfadarse", "v.", "动怒愤愤不平", "emotion"),
    ("enamorarse", "v.", "情定终身倾慕", "emotion"),
    ("casarse", "v.", "携手缔结婚约", "daily"),
    ("divorciarse", "v.", "离异各奔东西", "daily"),
    ("llevarse bien", "exp.", "融洽和睦共处", "emotion"),
    ("llevarse mal", "exp.", "势同水火龃龉", "emotion"),
    ("reír", "v.", "忍俊不禁发笑", "emotion"),
    ("reírse", "v.", "欢欣雀跃大笑", "emotion"),
    ("sonreír", "v.", "嘴角扬起微笑", "emotion"),
    ("llorar", "v.", "潸然泪下泣下", "emotion"),
    ("gritar", "v.", "扯嗓高声呼喊", "daily"),
    ("quejarse", "v.", "怨声载道诉苦", "emotion"),
    ("divertirse", "v.", "自得其乐尽兴", "emotion"),
    ("aburrirse", "v.", "百无聊赖沉闷", "emotion"),
    ("cansarse", "v.", "筋疲力竭气喘", "daily"),
    ("acostumbrarse", "v.", "见惯不怪习以为常", "daily"),
    ("equivocarse", "v.", "失策犯下差错", "daily"),
    ("perderse", "v.", "误入歧途迷失", "travel"),
    ("encontrarse", "v.", "不期而遇会合", "daily"),
    ("quedarse", "v.", "停驻原地不动", "daily"),
    ("irse", "v.", "拔腿就走告退", "travel"),
    ("marcharse", "v.", "离家启程远走", "travel"),

    # --- Verbos irregulares y tiempos compuestos A2 ---
    ("pedir", "v.", "索要乞求；下单点单", "daily"),
    ("servir", "v.", "上菜端盘；起效管用", "food"),
    ("seguir", "v.", "尾随跟紧；持续不断", "daily"),
    ("conseguir", "v.", "努力达成获得", "daily"),
    ("perseguir", "v.", "穷追不舍追赶", "daily"),
    ("elegir", "v.", "审慎抉择评选", "daily"),
    ("corregir", "v.", "批阅涂抹订正", "daily"),
    ("repetir", "v.", "依样再次复述", "daily"),
    ("reñir", "v.", "叱责斥责口角", "emotion"),
    ("vestir", "v.", "给某人穿上衣袍", "daily"),
    ("despedir", "v.", "解聘解雇；挥手送别", "business"),
    ("despedirse", "v.", "辞别作别依依", "daily"),
    ("reírse", "v.", "放声大笑欢愉", "emotion"),
    ("morir", "v.", "撒手人寰长逝", "daily"),
    ("fallecer", "v.", "寿终正寝辞世", "daily"),
    ("nacer", "v.", "呱呱坠地诞生", "daily"),
    ("crecer", "v.", "茁壮拔节成长", "daily"),
    ("obedecer", "v.", "遵纪听从顺服", "daily"),
    ("ofrecer", "v.", "主动提供奉献", "daily"),
    ("merecer", "v.", "理所应当配得", "daily"),
    ("conducir", "v.", "握紧方向盘驾车", "travel"),
    ("traducir", "v.", "转换语种笔译", "daily"),
    ("producir", "v.", "流水车间生产", "business"),
    ("reducir", "v.", "削减压缩幅度", "business"),
    ("introducir", "v.", "插入引入载入", "daily"),
    ("caber", "v.", "容得下装得进", "grammar"),
    ("caer", "v.", "失足自高跌落", "daily"),
    ("traer", "v.", "随手捎带至此", "daily"),
    ("atraer", "v.", "散发魅力吸引", "emotion"),
    ("oír", "v.", "耳中清晰听闻", "daily"),
    ("oler", "v.", "鼻翼抽动闻味", "daily"),

    # --- Adverbios y conectores A2 ---
    ("así que", "conj.", "因此，于是乎", "grammar"),
    ("de modo que", "conj.", "以至于，从而", "grammar"),
    ("de manera que", "conj.", "以便，因而", "grammar"),
    ("por lo tanto", "exp.", "因而，理所当然", "grammar"),
    ("por consiguiente", "exp.", "据此结果显示", "grammar"),
    ("entonces", "adv.", "当时，那个时候", "grammar"),
    ("luego", "adv.", "继而，随之", "grammar"),
    ("después", "adv.", "在后，随后", "grammar"),
    ("antes", "adv.", "先前，从前", "grammar"),
    ("mientras tanto", "exp.", "在这空档期间", "grammar"),
    ("al mismo tiempo", "exp.", "与此同时并驾齐驱", "grammar"),
    ("a la vez", "exp.", "同时一并发生", "grammar"),
    ("de repente", "exp.", "冷不防突发", "grammar"),
    ("de pronto", "exp.", "冷不丁倏忽", "grammar"),
    ("por fin", "exp.", "千呼万唤终于", "grammar"),
    ("finalmente", "adv.", "终究落定收场", "grammar"),
    ("al final", "exp.", "事情归根结底", "grammar"),
    ("en primer lugar", "exp.", "首当其冲第一条", "grammar"),
    ("en segundo lugar", "exp.", "次之退居第二", "grammar"),
    ("por último", "exp.", "压轴最后陈词", "grammar"),
    ("además", "adv.", "更有甚者再者", "grammar"),
    ("incluso", "adv.", "就连也是如此", "grammar"),
    ("hasta", "adv./prep.", "甚而至于到达", "grammar"),
    ("sin embargo", "exp.", "尽管如此话锋一转", "grammar"),
    ("en cambio", "exp.", "反观相比之下", "grammar"),
    ("por un lado", "exp.", "从一方面而言", "grammar"),
    ("por otro lado", "exp.", "另一方面考量", "grammar"),
    ("a pesar de que", "exp.", "纵使尽管哪怕", "grammar"),
    ("aunque", "conj.", "即使虽然哪怕", "grammar"),
    ("ya que", "exp.", "鉴于既然已知", "grammar"),
    ("puesto que", "exp.", "既成事实由于", "grammar"),
    ("dado que", "exp.", "考虑到有鉴于", "grammar"),
    ("por culpa de", "exp.", "全怪罪于拖累", "grammar"),
    ("gracias a", "exp.", "全仰仗得益于", "grammar"),
    ("debido a", "exp.", "归咎于源自于", "grammar"),
    ("a causa de", "exp.", "致使由于诱发", "grammar"),
    ("para que", "conj.", "以便于旨在令", "grammar"),
    ("a fin de que", "conj.", "目的在于达成", "grammar"),
    ("con tal de que", "conj.", "只要能够满足", "grammar"),
    ("siempre que", "conj.", "凡是每当倘若", "grammar"),
    ("a no ser que", "conj.", "除非发生意外", "grammar"),
    ("a menos que", "conj.", "除非万不得已", "grammar"),
    ("tal vez", "exp.", "或许可能猜想", "grammar"),
    ("quizás", "adv.", "也许说不准", "grammar"),
    ("a lo mejor", "exp.", "说不定大概率", "grammar"),
    ("seguramente", "adv.", "十有八九料定", "grammar"),
    ("probablemente", "adv.", "很有可能估计", "grammar"),
    ("posiblemente", "adv.", "存在可能性", "grammar"),
    ("casi", "adv.", "差一点点将近", "daily"),
    ("apenas", "adv.", "勉强勉为其难", "daily"),
    ("solamente", "adv.", "唯独仅仅而已", "daily"),
    ("solo", "adv./adj.", "只消；孤单寂寞", "daily"),
    ("únicamente", "adv.", "绝无仅有单单", "daily"),
    ("sobre todo", "exp.", "重中之重尤甚", "daily"),
    ("especialmente", "adv.", "专门特意尤其", "daily"),
    ("concretamente", "adv.", "具体落到实处", "daily"),
    ("en realidad", "exp.", "实质真相恰恰", "daily"),
    ("de hecho", "exp.", "事实上毫不避讳", "daily"),
    ("exactamente", "adv.", "分毫不差分明", "daily"),
    ("precisamente", "adv.", "恰恰正是此处", "daily"),
    ("por supuesto", "exp.", "不言而喻理当", "daily"),
    ("desde luego", "exp.", "断乎毫无疑问", "daily"),
    ("sin duda", "exp.", "毋庸置疑确凿", "daily"),
    ("claro que sí", "exp.", "确实无疑极是", "daily")
]

print(f"Loaded A2 items: {len(A2_WORDS)}")
