# scripts/data_b2.py
# Nivel B2: 650 palabras esenciales SIELE
# Formato: (palabra, categoría_gramatical, significado_chino, categoría_temática, ejemplo_es, ejemplo_zh)

B2_WORDS = [
    # --- Política, instituciones y relaciones internacionales ---
    ("constitución", "f.", "根本大法宪法", "business"),
    ("estado de derecho", "m.", "法治国家治理秩序", "business"),
    ("soberanía", "f.", "不容践踏国家主权", "business"),
    ("democracia", "f.", "人民当家作主民主制", "business"),
    ("monarquía parlamentaria", "f.", "欧洲议会制君主立宪", "business"),
    ("república", "f.", "主权民选共和国", "business"),
    ("separación de poderes", "f.", "立法司法行政三权分立", "business"),
    ("poder ejecutivo", "m.", "行政行署最高执行权", "business"),
    ("poder legislativo", "m.", "代议制议会立法权", "business"),
    ("poder judicial", "m.", "独立定罪审判司法权", "business"),
    ("parlamento", "m.", "最高代议机构国会", "business"),
    ("congreso de los diputados", "m.", "西班牙议会众议院", "business"),
    ("senado", "m.", "各地区代表参议院", "business"),
    ("diputado", "m.", "直选国会众议员", "business"),
    ("senador", "m.", "地区推举参议员", "business"),
    ("presidente del gobierno", "m.", "内阁第一人政府首相", "business"),
    ("ministro", "m.", "主管国家部委大臣", "business"),
    ("ministerio", "m.", "国务院部级行政厅署", "business"),
    ("portavoz", "m./f.", "代表集体发声新闻发言人", "business"),
    ("oposición", "f.", "在野监督制衡反对党", "business"),
    ("coalición", "f.", "多党携手执政联盟", "business"),
    ("pacto de estado", "m.", "跨党派签署国家战略公约", "business"),
    ("sufragio universal", "m.", "公民普遍直接投票选举权", "business"),
    ("elecciones generales", "f.pl.", "全国大选换届周期", "business"),
    ("censo electoral", "m.", "官方登记在册合法选民名册", "business"),
    ("abstención", "f.", "消极弃权不投选票", "business"),
    ("escaño", "m.", "议会内政党竞得席位", "business"),
    ("moción de censura", "f.", "弹劾政府下台不信任动议", "business"),
    ("decreto ley", "m.", "突发内阁紧急政令", "business"),
    ("promulgación", "f.", "元首签署颁布法案", "business"),
    ("derogación", "f.", "法条宣布全面废止作废", "business"),
    ("diplomacia", "f.", "穿梭斡旋多边外交", "business"),
    ("diplomático", "m./adj.", "使团公使；八面玲珑的", "business"),
    ("embajada", "f.", "常驻特命全权大使馆", "travel"),
    ("embajador", "m.", "一国特命全权大使", "business"),
    ("consulado", "m.", "办理侨民签证之领事馆", "travel"),
    ("cónsul", "m.", "派驻主要口岸总领事", "business"),
    ("tratado internacional", "m.", "两国多边签署国际条约", "business"),
    ("convenio multilateral", "m.", "多方遵从行业国际公约", "business"),
    ("relaciones bilaterales", "f.pl.", "两国元首双边友好会晤", "business"),
    ("organismo internacional", "m.", "联合国等跨国权威组织", "business"),
    ("geopolítica", "f.", "大国博弈地缘政治格局", "business"),
    ("globalización", "f.", "经贸深度绑定全球一体化", "business"),

    # --- Sistema judicial, penal y derechos procesales ---
    ("justicia", "f.", "公平正义；司法机关", "business"),
    ("tribunal supremo", "m.", "终审裁决最高法院", "business"),
    ("audiencia nacional", "f.", "跨省大案国家巡回法庭", "business"),
    ("juzgado", "m.", "基层立案地方法院", "business"),
    ("juez", "m./f.", "端坐法台定罪法官", "business"),
    ("magistrado", "m.", "资深高级资历大法官", "business"),
    ("fiscal", "m./f.", "代表国家提起公诉检察官", "business"),
    ("fiscalía", "f.", "国家检察署最高检", "business"),
    ("abogado defensor", "m.", "为当事人辩护之刑辩律师", "business"),
    ("acusación particular", "f.", "受害者聘请之原告律师", "business"),
    ("jurado popular", "m.", "公民随机抽签大陪审团", "business"),
    ("testigo presencial", "m.", "亲眼目击第一现场证人", "business"),
    ("perito judicial", "m.", "出具物证鉴定司法专家", "business"),
    ("demandante", "m./f.", "诉诸法律讨回公道原告", "business"),
    ("demandado", "m./f.", "出庭应诉之民事被告", "business"),
    ("imputado", "m.", "被立案传唤嫌疑人", "business"),
    ("acusado", "m.", "公诉指控刑事被告人", "business"),
    ("procesado", "m.", "正式移送起诉受审者", "business"),
    ("culpable", "adj./m.", "确凿罪责成立有罪者", "business"),
    ("inocente", "adj.", "蒙冤昭雪清白无罪", "business"),
    ("delito grave", "m.", "危害严重恶性重罪", "business"),
    ("infracción", "f.", "触犯条例文明轻微违法", "business"),
    ("estafa", "f.", "虚构事实巨额金融诈骗", "business"),
    ("fraude fiscal", "m.", "伪造账目偷逃国家税款", "business"),
    ("malversación", "f.", "中饱私囊侵吞公款罪", "business"),
    ("cohecho", "m.", "收受回扣权钱勾结受贿罪", "business"),
    ("soborno", "m.", "不法巨款行贿勾当", "business"),
    ("prevaricación", "f.", "明知故犯执法犯法渎职罪", "business"),
    ("blanqueo de capitales", "m.", "洗钱隐匿黑金地下钱庄", "business"),
    ("homicidio", "m.", "剥夺生命故意杀人罪", "business"),
    ("juicio oral", "m.", "当庭质证公开庭审对簿", "business"),
    ("vista", "f.", "法庭开庭质询程序", "business"),
    ("prueba pericial", "f.", "出示法医学刑侦关键铁证", "business"),
    ("confesión", "f.", "法网难逃痛哭如实招供", "business"),
    ("testimonio", "m.", "宣誓如实陈述证人证言", "business"),
    ("veredicto", "m.", "陪审团闭门审议决议裁决", "business"),
    ("sentencia firme", "f.", "终局生效不容推翻判决", "business"),
    ("condena", "f.", "科处徒刑刑事惩戒", "business"),
    ("absolución", "f.", "当庭宣判无罪获释", "business"),
    ("recurso de apelación", "m.", "不服初审提起上诉重审", "business"),
    ("indulto", "m.", "国家元首特许免罪特赦", "business"),
    ("amnistía", "f.", "全国范围宣布豁免大赦", "business"),
    ("pena de prisión", "f.", "羁押收监剥夺自由刑罚", "business"),
    ("cárcel", "f.", "铁窗深锁重刑犯监狱", "business"),
    ("fianza", "f.", "候审保释巨额保证金", "business"),
    ("indemnización por daños", "f.", "清算人身精神损害赔偿", "business"),

    # --- Macroeconomía, mercados globales e inversión B2 ---
    ("macroeconomía", "f.", "国家综合宏观经济运行", "business"),
    ("producto interior bruto", "m.", "境内生产总值GDP总量", "business"),
    ("renta per cápita", "f.", "全体国民人均支配收入", "business"),
    ("crecimiento económico", "m.", "年度经济稳步增长势头", "business"),
    ("recesión técnica", "f.", "连续两季度负增长衰退", "business"),
    ("depresión económica", "f.", "大崩盘大萧条黑暗期", "business"),
    ("tasa de paro", "f.", "全社会城镇登记失业率", "business"),
    ("inflación subyacente", "f.", "剔除能源食品核心通胀", "business"),
    ("deflación", "f.", "消费低迷物价负增长通缩", "business"),
    ("estanflación", "f.", "经济停滞伴随通胀高企", "business"),
    ("balanza comercial", "f.", "进出口货物外贸差额", "business"),
    ("superávit", "m.", "外贸资金结余顺差大增", "business"),
    ("déficit presupuestario", "m.", "财政收支亏空赤字扩大", "business"),
    ("deuda soberana", "f.", "由中央政府背书发行国债", "business"),
    ("prima de riesgo", "f.", "与基准国债利差风险溢价", "business"),
    ("mercado de capitales", "m.", "长期融通资本大市场", "business"),
    ("bolsa de valores", "f.", "国家证券有价交易大厅", "business"),
    ("cotización bursátil", "f.", "个股盘口实时走势牌价", "business"),
    ("índice bursátil", "m.", "蓝筹股合成股票指数", "business"),
    ("IBEX 35", "m.", "西班牙三十五大蓝筹股指数", "business"),
    ("volatilidad", "f.", "盘面剧烈震荡波动率", "business"),
    ("fondo de pensiones", "m.", "退休金托管信托基金", "business"),
    ("bono del estado", "m.", "五年十年期主权政府债券", "business"),
    ("obligación", "f.", "长期不可撤销固定债券", "business"),
    ("plusvalía", "f.", "资产转手获得增值溢价", "business"),
    ("capitalización", "f.", "全部总股本市场估值", "business"),
    ("banco central", "m.", "制定宏观货币政策央行", "business"),
    ("política monetaria", "f.", "降准加息银根松紧政策", "business"),
    ("liquidez", "f.", "现金池充裕资产变现力", "business"),
    ("divisa", "f.", "跨国贸易通用外汇储备", "business"),
    ("tipo de cambio", "m.", "本币对锚定货币汇率", "business"),
    ("devaluación", "f.", "官方主动宣布汇率贬值", "business"),
    ("arancel aduanero", "m.", "国门边防征收进口关税", "business"),
    ("proteccionismo", "m.", "构筑壁垒贸易保护主义", "business"),
    ("libre comercio", "m.", "货物零关税畅通自由贸易", "business"),
    ("deslocalización", "f.", "为降成本产能产业外迁", "business"),
    ("multinacional", "f./adj.", "跨越五大洲跨国巨头", "business"),
    ("monopolio", "m.", "独家吞并市场托拉斯垄断", "business"),
    ("oligopolio", "m.", "少数巨鳄合谋寡头垄断", "business"),
    ("competitividad", "f.", "全球产业链核心竞争力", "business"),

    # --- Ciencia puntera, investigación y bioética ---
    ("comunidad científica", "f.", "严谨治学国际科学界", "daily"),
    ("método científico", "m.", "假说检验求真科学方法", "daily"),
    ("rigor académico", "m.", "一丝不苟严密求实学风", "daily"),
    ("postulado", "m.", "毋庸证明先验假设公理", "daily"),
    ("premisa mayor", "f.", "三段论逻辑立论大前提", "daily"),
    ("hipótesis de trabajo", "f.", "实验初期拟定工作假说", "daily"),
    ("verificación empírica", "f.", "实验可重复实证检验", "daily"),
    ("refutación", "f.", "数据反驳颠覆既往认知", "daily"),
    ("paradigma", "m.", "改写教科书划时代新范式", "daily"),
    ("investigación y desarrollo", "f.", "企业核心科研攻关研发", "business"),
    ("I+D+i", "f.", "研发与产业商业化创新", "business"),
    ("patente de invención", "f.", "国家授予独占发明专利权", "business"),
    ("propiedad intelectual", "f.", "智慧成果神圣知识产权", "business"),
    ("ensayo clínico", "m.", "三期严密人体医药双盲试验", "daily"),
    ("placebo", "m.", "排除心理暗示无药效对照剂", "daily"),
    ("grupo de control", "m.", "对照比对标准空白对照组", "daily"),
    ("muestra representativa", "f.", "严丝合缝代表性大样本", "daily"),
    ("variable independiente", "f.", "人为控制变动之自变量", "daily"),
    ("genoma", "m.", "物种全部遗传全套基因组", "daily"),
    ("secuenciación", "f.", "碱基对排列顺序基因测序", "daily"),
    ("terapia génica", "f.", "修复受损缺陷基因靶向治疗", "daily"),
    ("células madre", "f.pl.", "具备全能分化多能干细胞", "daily"),
    ("clonación", "f.", "无性繁育克隆体培育", "daily"),
    ("organismo transgénico", "m.", "转入外源性基因农作物", "daily"),
    ("neurociencia", "f.", "探索人脑意识前沿神经学", "daily"),
    ("sinapsis", "f.", "神经递质交联神经突触", "daily"),
    ("inteligencia artificial", "f.", "通用深度大模型人工智能", "daily"),
    ("aprendizaje automático", "m.", "自主挖掘规律机器学习", "daily"),
    ("red neuronal", "f.", "多层深度人工神经网络", "daily"),
    ("procesamiento del lenguaje", "m.", "自然语言理解语义分析", "daily"),
    ("algoritmo predictivo", "m.", "大数据提前推演预测算法", "daily"),
    ("computación cuántica", "f.", "颠覆算力极值量子计算", "daily"),
    ("nanotecnología", "f.", "操纵微观分子纳米工程", "daily"),
    ("transición ecológica", "f.", "全面告别石化绿色生态转型", "daily"),
    ("economía circular", "f.", "零排放零废料闭环循环经济", "daily"),
    ("huella de carbono", "f.", "生命全周期碳踪迹足迹", "daily"),
    ("bioética", "f.", "规范生命科学边界生命伦理学", "daily"),
    ("dilema moral", "m.", "进退维谷考验两难伦理困局", "emotion"),

    # --- Arte, teoría estética, literatura y patrimonio ---
    ("estética", "f.", "审美哲学与纯艺术论", "daily"),
    ("canon artístico", "m.", "历经沧桑确立经典典范", "daily"),
    ("corriente artística", "f.", "风起云涌时代艺术流派", "daily"),
    ("vanguardia", "f.", "打破陈规锐意前卫实验派", "daily"),
    ("renacimiento", "m.", "人文觉醒意大利文艺复兴", "daily"),
    ("barroco", "m.", "繁复雕饰光影极度巴洛克", "daily"),
    ("romanticismo", "m.", "崇尚自由激情奔放浪漫主义", "daily"),
    ("realismo", "m.", "入木三分白描社会现实主义", "daily"),
    ("impresionismo", "m.", "户外捕捉瞬息光影印象派", "daily"),
    ("surrealismo", "m.", "潜意识梦境解构超现实主义", "daily"),
    ("obra maestra", "f.", "惊世骇俗名垂青史代表杰作", "daily"),
    ("perspectiva", "f.", "空间纵深焦点透视画法", "daily"),
    ("claroscuro", "m.", "卡拉瓦乔式强烈明暗对照法", "daily"),
    ("policromía", "f.", "斑斓绚烂多彩木雕彩绘", "daily"),
    ("bajorrelieve", "m.", "墙体凸起雕刻浅浮雕", "daily"),
    ("fresco", "m.", "湿壁灰泥矿物永存湿壁画", "daily"),
    ("patrimonio de la humanidad", "m.", "联合国教科文世界遗产", "travel"),
    ("vestigio histórico", "m.", "风雨剥蚀历史沧桑遗存", "travel"),
    ("yacimiento arqueológico", "m.", "泥土夯层远古考古遗址", "travel"),
    ("restauración", "f.", "修旧如旧文物精密修复", "travel"),
    ("género literario", "m.", "诗歌散文戏剧文学体裁", "daily"),
    ("prosa", "f.", "行云流水叙事散文体", "daily"),
    ("lírica", "f.", "倾吐衷肠高雅抒情诗歌", "daily"),
    ("dramaturgia", "f.", "舞台矛盾冲突编剧编创学", "daily"),
    ("ensayo filosófico", "m.", "明辨是非长篇哲学随笔", "daily"),
    ("antología", "f.", "千挑万选名家名篇选集", "daily"),
    ("verso libre", "m.", "打破格律韵脚自由诗体", "daily"),
    ("figura retórica", "f.", "绘声绘色高超修辞手法", "daily"),
    ("metáfora", "f.", "托物言志出神入化隐喻", "daily"),
    ("alegoría", "f.", "意味深长寓言故事讽喻", "daily"),
    ("hipérbole", "f.", "气吞山河艺术夸饰夸张", "daily"),
    ("ironía", "f.", "话中有话含蓄反讽冷嘲", "daily"),
    ("catarsis", "f.", "悲剧直击灵魂情感宣泄净化", "emotion"),
    ("trama argumental", "f.", "环环相扣跌宕起伏剧情主线", "daily"),
    ("desenlace", "m.", "高潮迭起故事最终结局", "daily"),
    ("narrador omnisciente", "m.", "通晓全局上帝全知视角叙述者", "daily"),
    ("monólogo interior", "m.", "意识流涌动内心独白", "daily"),
    ("crítica literaria", "f.", "洞幽烛微文艺批评品鉴", "daily"),

    # --- Verbos formales y académicos SIELE B2 ---
    ("abarcar", "v.", "胸罗万象囊括包罗", "business"),
    ("dilucidar", "v.", "去伪存真彻底阐明", "business"),
    ("elucidar", "v.", "抽丝剥茧透彻阐释", "business"),
    ("constatar", "v.", "依据确凿物证核实验证", "business"),
    ("corroborar", "v.", "旁征博引确证印证", "business"),
    ("refutar", "v.", "有理有据严词驳斥", "business"),
    ("contraponer", "v.", "针锋相对列举对照", "business"),
    ("desvirtuar", "v.", "歪曲真相削弱效力", "business"),
    ("ponderar", "v.", "审时度势全面权衡", "business"),
    ("vislumbrar", "v.", "依稀洞见远景曙光", "business"),
    ("suscitar", "v.", "掀起轩然大波引发热议", "business"),
    ("propiciar", "v.", "创造适宜良机促成", "business"),
    ("fomentar", "v.", "出台利好政策大力扶持", "business"),
    ("viabilizar", "v.", "突破阻力使方案切实可行", "business"),
    ("mitigar", "v.", "多管齐下缓解减轻灾情", "business"),
    ("paliar", "v.", "治标救急暂时遏制", "business"),
    ("optimizar", "v.", "提质增效优化到最佳", "business"),
    ("consolidar", "v.", "夯实基础巩固地位", "business"),
    ("afianzar", "v.", "深植根基牢牢确立", "business"),
    ("erradicar", "v.", "斩草除根彻底根除", "business"),
    ("vincular", "v.", "骨肉相连紧密挂钩绑定", "business"),
    ("desvincular", "v.", "澄清事实彻底撇清剥离", "business"),
    ("desestimar", "v.", "查无实据裁定驳回不予受理", "business"),
    ("perseverar", "v.", "百折不挠持之以恒坚守", "business"),
    ("soslayar", "v.", "巧舌如簧巧妙回避绕开", "business"),
    ("eludir", "v.", "逃避法定义务责任", "business"),
    ("dirimir", "v.", "公正仲裁平息纷争争议", "business"),
    ("estipular", "v.", "在合同协议白纸黑字载明", "business"),
    ("legitimar", "v.", "程序正义确立其合法性", "business"),
    ("sobrellevar", "v.", "忍辱负重经受住打击", "business"),
    ("trascender", "v.", "跨越时空超拔升华超越", "business"),
    ("preconizar", "v.", "高瞻远瞩倡导推崇", "business"),
    ("discernir", "v.", "火眼金睛明辨是非真伪", "business"),
    ("disentir", "v.", "不随波逐流表达不同政见", "business"),
    ("converger", "v.", "志同道合不谋而合汇聚", "business"),
    ("divergir", "v.", "各执一词渐行渐远分歧", "business"),
    ("inferir", "v.", "从已知线索合乎逻辑推断", "business"),
    ("deducir", "v.", "由普遍公理演绎得出", "business"),
    ("extrapolar", "v.", "举一反三推广外推", "business"),
    ("sintetizar", "v.", "去粗取精提炼高度综合", "business"),
    ("plasmar", "v.", "把抽象蓝图具象化呈现", "business"),
    ("reanudar", "v.", "鸣金收兵后重新复工恢复", "business"),
    ("consumar", "v.", "促成其事功德圆满告成", "business"),
    ("menguar", "v.", "日薄西山渐趋式微锐减", "business"),
    ("acrecentar", "v.", "锦上添花进一步与日俱增", "business"),

    # --- Marcadores discursivos y locuciones formales B2/C1 ---
    ("no obstante", "exp.", "尽管如此然而仍旧", "grammar"),
    ("por consiguiente", "exp.", "依照前述事实必然导致", "grammar"),
    ("en consecuencia", "exp.", "水到渠成作为其连锁结果", "grammar"),
    ("por ende", "exp.", "因此之故故而", "grammar"),
    ("en vista de lo anterior", "exp.", "通盘综上所述考量", "grammar"),
    ("a tenor de lo dispuesto", "exp.", "严格依据法律明文规定", "grammar"),
    ("en lo que respecta a", "exp.", "在涉及该特定维度领域", "grammar"),
    ("en lo atinente a", "exp.", "凡属于该项议题管辖范围", "grammar"),
    ("en lo relativo a", "exp.", "关于此一论点展开", "grammar"),
    ("por lo que atañe a", "exp.", "涉及触及各方核心利益", "grammar"),
    ("en definitiva", "exp.", "千回百转归结到底终极定论", "grammar"),
    ("a fin de cuentas", "exp.", "剥离表象直击要害归根结底", "grammar"),
    ("a modo de colofón", "exp.", "在全篇终了之际作结", "grammar"),
    ("en resumidas cuentas", "exp.", "用最洗练语言统揽全局", "grammar"),
    ("en última instancia", "exp.", "作为最后裁决兜底底线手段", "grammar"),
    ("huelga decir que", "exp.", "毋庸赘言不言自明毫无争议", "grammar"),
    ("cabe resaltar que", "exp.", "在此特别值得着重强调", "grammar"),
    ("conviene poner de relieve", "exp.", "尤有必要揭示并突出点明", "grammar"),
    ("es menester señalar que", "exp.", "必须郑重指出不可忽视", "grammar"),
    ("resulta insoslayable", "exp.", "这是断然不可回避严峻现实", "grammar"),
    ("a juicio de los expertos", "exp.", "各界权威泰斗一致公认评断", "grammar"),
    ("con arreglo a la legalidad", "exp.", "完完全全遵纪守法依规", "grammar"),
    ("so pretexto de", "exp.", "假借幌子堂而皇之托词", "grammar"),
    ("a sabiendas de que", "exp.", "心知肚明明知后果依然为之", "grammar")
]

print(f"Loaded B2 items: {len(B2_WORDS)}")
