# scripts/data_a1.py
# Nivel A1: 550 palabras esenciales SIELE
# Formato: (palabra, categoría_gramatical, significado_chino, categoría_temática, ejemplo_es, ejemplo_zh)

A1_WORDS = [
    # --- Saludos, cortesía y presentaciones ---
    ("hola", "interj.", "你好", "daily", "¡Hola! ¿Cómo estás?", "你好！你最近怎么样？"),
    ("adiós", "interj.", "再见", "daily", "Adiós, ¡hasta mañana!", "再见，明天见！"),
    ("gracias", "interj.", "谢谢", "daily", "Muchas gracias por tu ayuda.", "非常感谢你的帮助。"),
    ("de nada", "exp.", "不用谢，不客气", "daily", "—Gracias. —De nada.", "—谢谢。—不用谢。"),
    ("por favor", "exp.", "请，劳驾", "daily", "¿Un café, por favor?", "请给我一杯咖啡好吗？"),
    ("perdón", "m./interj.", "对不起，劳驾", "daily", "Perdón, ¿dónde está el metro?", "打扰一下，请问地铁在哪里？"),
    ("disculpe", "v./exp.", "劳驾，抱歉（尊称）", "daily", "Disculpe señor, ¿qué hora es?", "劳驾先生，请问几点了？"),
    ("lo siento", "exp.", "对不起，很抱歉", "daily", "Lo siento mucho, no puedo ir.", "非常抱歉，我不能去。"),
    ("bienvenido", "adj./interj.", "欢迎", "daily", "¡Bienvenidos a España!", "欢迎来到西班牙！"),
    ("buenos días", "exp.", "早上好，上午好", "daily", "Buenos días a todos.", "大家早上好。"),
    ("buenas tardes", "exp.", "下午好", "daily", "Buenas tardes, ¿en qué puedo ayudarle?", "下午好，有什么能帮您的？"),
    ("buenas noches", "exp.", "晚上好，晚安", "daily", "Buenas noches y que descanses.", "晚安，好好休息。"),
    ("hasta luego", "exp.", "回头见，待会儿见", "daily", "Hasta luego, nos vemos pronto.", "回头见，我们很快再见。"),
    ("hasta pronto", "exp.", "再见，很快再见", "daily", "Hasta pronto, amigo.", "再见，朋友。"),
    ("hasta mañana", "exp.", "明天见", "daily", "Hasta mañana en la oficina.", "明天办公室见。"),
    ("encantado", "adj./exp.", "很高兴认识你", "daily", "Mucho gusto, encantado.", "很高兴认识你。"),
    ("mucho gusto", "exp.", "初次见面，幸会", "daily", "Mucho gusto en conocerte.", "非常高兴认识你。"),
    ("qué tal", "exp.", "怎么样，你好吗", "daily", "¿Qué tal todo por allí?", "那边一切都好吗？"),
    ("cómo estás", "exp.", "你好吗，最近怎样", "daily", "¿Cómo estás hoy?", "你今天怎么样？"),
    ("muy bien", "exp.", "非常好", "daily", "Estoy muy bien, gracias.", "我很好，谢谢。"),
    ("regular", "adj./adv.", "马马虎虎，普通", "daily", "—¿Cómo estás? —Regular.", "—最近怎样？—马马虎虎。"),
    ("felicidades", "f.pl./interj.", "祝贺，恭喜", "daily", "¡Muchas felicidades por tu cumpleaños!", "祝你生日快乐！"),
    ("enhorabuena", "f./interj.", "恭贺，祝贺", "daily", "¡Enhorabuena por el examen!", "祝贺考试通过！"),
    ("saludos", "m.pl.", "问候，致意", "daily", "Muchos saludos a tu familia.", "代我向你家人问好。"),
    ("abrazo", "m.", "拥抱，抱", "daily", "Un fuerte abrazo.", "紧紧拥抱（书信结语）。"),

    # --- Pronombres y determinantes ---
    ("yo", "pron.", "我", "grammar"),
    ("tú", "pron.", "你", "grammar"),
    ("él", "pron.", "他", "grammar"),
    ("ella", "pron.", "她", "grammar"),
    ("usted", "pron.", "您", "grammar"),
    ("nosotros", "pron.", "我们（阳性/混合）", "grammar"),
    ("nosotras", "pron.", "我们（阴性）", "grammar"),
    ("vosotros", "pron.", "你们（阳性/混合）", "grammar"),
    ("vosotras", "pron.", "你们（阴性）", "grammar"),
    ("ellos", "pron.", "他们", "grammar"),
    ("ellas", "pron.", "她们", "grammar"),
    ("ustedes", "pron.", "您各位，你们", "grammar"),
    ("me", "pron.", "我（宾格/与格/反身）", "grammar"),
    ("te", "pron.", "你（宾格/与格/反身）", "grammar"),
    ("le", "pron.", "他/她/您（与格）", "grammar"),
    ("nos", "pron.", "我们（宾格/与格/反身）", "grammar"),
    ("os", "pron.", "你们（宾格/与格/反身）", "grammar"),
    ("les", "pron.", "他们/她们/诸位（与格）", "grammar"),
    ("se", "pron.", "自己，互相（反身代词）", "grammar"),
    ("lo", "pron.", "他/它（阳性直接宾语）", "grammar"),
    ("la", "pron./art.", "她/它（阴性直接宾语）；冠词", "grammar"),
    ("los", "pron./art.", "他们/它们；阳性复数冠词", "grammar"),
    ("las", "pron./art.", "她们/它们；阴性复数冠词", "grammar"),
    ("mí", "pron.", "我（介词后）", "grammar"),
    ("ti", "pron.", "你（介词后）", "grammar"),
    ("conmigo", "pron.", "和我一起", "grammar"),
    ("contigo", "pron.", "和你一起", "grammar"),
    ("este", "adj./pron.", "这，这个（阳性）", "grammar"),
    ("esta", "adj./pron.", "这，这个（阴性）", "grammar"),
    ("estos", "adj./pron.", "这些（阳性）", "grammar"),
    ("estas", "adj./pron.", "这些（阴性）", "grammar"),
    ("esto", "pron.", "这个（中性）", "grammar"),
    ("ese", "adj./pron.", "那，那个（阳性）", "grammar"),
    ("esa", "adj./pron.", "那，那个（阴性）", "grammar"),
    ("esos", "adj./pron.", "那些（阳性）", "grammar"),
    ("esas", "adj./pron.", "那些（阴性）", "grammar"),
    ("eso", "pron.", "那个（中性）", "grammar"),
    ("aquel", "adj./pron.", "那边的，远处的（阳性）", "grammar"),
    ("aquella", "adj./pron.", "那边的，远处的（阴性）", "grammar"),
    ("aquellos", "adj./pron.", "那些（远处阳性）", "grammar"),
    ("aquellas", "adj./pron.", "那些（远处阴性）", "grammar"),
    ("aquello", "pron.", "那事，那物（远处中性）", "grammar"),
    ("mi", "adj.", "我的（单数）", "grammar"),
    ("mis", "adj.", "我的（复数）", "grammar"),
    ("tu", "adj.", "你的（单数）", "grammar"),
    ("tus", "adj.", "你的（复数）", "grammar"),
    ("su", "adj.", "他/她/您的（单数）", "grammar"),
    ("sus", "adj.", "他/她/您的（复数）", "grammar"),
    ("nuestro", "adj.", "我们的（阳性单数）", "grammar"),
    ("nuestra", "adj.", "我们的（阴性单数）", "grammar"),
    ("nuestros", "adj.", "我们的（阳性复数）", "grammar"),
    ("nuestras", "adj.", "我们的（阴性复数）", "grammar"),
    ("vuestro", "adj.", "你们的（阳性单数）", "grammar"),
    ("vuestra", "adj.", "你们的（阴性单数）", "grammar"),
    ("vuestros", "adj.", "你们的（阳性复数）", "grammar"),
    ("vuestras", "adj.", "你们的（阴性复数）", "grammar"),
    ("mío", "pron.", "我的东西（阳单）", "grammar"),
    ("mía", "pron.", "我的东西（阴单）", "grammar"),
    ("tuyo", "pron.", "你的东西（阳单）", "grammar"),
    ("tuya", "pron.", "你的东西（阴单）", "grammar"),
    ("suyo", "pron.", "他/她的东西（阳单）", "grammar"),
    ("suya", "pron.", "他/她的东西（阴单）", "grammar"),

    # --- Interrogativos ---
    ("qué", "pron.", "什么", "grammar", "¿Qué haces ahora?", "你现在在做什么？"),
    ("quién", "pron.", "谁", "grammar", "¿Quién es esa persona?", "那个人是谁？"),
    ("quiénes", "pron.", "谁（复数）", "grammar", "¿Quiénes son ellos?", "他们是谁？"),
    ("cómo", "adv.", "怎样，如何", "grammar", "¿Cómo te llamas?", "你叫什么名字？"),
    ("dónde", "adv.", "哪里", "grammar", "¿Dónde vives?", "你住在哪里？"),
    ("adónde", "adv.", "去哪里", "grammar", "¿Adónde vas?", "你要去哪里？"),
    ("cuándo", "adv.", "何时，什么时候", "grammar", "¿Cuándo empieza la clase?", "课程什么时候开始？"),
    ("cuánto", "adj./pron.", "多少（阳单）", "grammar", "¿Cuánto cuesta esto?", "这个多少钱？"),
    ("cuánta", "adj./pron.", "多少（阴单）", "grammar", "¿Cuánta agua bebes?", "你喝多少水？"),
    ("cuántos", "adj./pron.", "多少个（阳复）", "grammar", "¿Cuántos años tienes?", "你多大年纪？"),
    ("cuántas", "adj./pron.", "多少个（阴复）", "grammar", "¿Cuántas personas hay?", "有多少人？"),
    ("cuál", "pron.", "哪一个", "grammar", "¿Cuál es tu libro?", "哪本是你的书？"),
    ("cuáles", "pron.", "哪些", "grammar", "¿Cuáles prefieres?", "你更喜欢哪些？"),
    ("por qué", "exp.", "为什么", "grammar", "¿Por qué estudias español?", "你为什么学西语？"),
    ("porque", "conj.", "因为", "grammar", "Porque es muy útil.", "因为这很有用。"),

    # --- Números cardinales y ordinales ---
    ("cero", "num.", "零", "daily"),
    ("uno", "num.", "一", "daily"),
    ("un", "art./num.", "一个（阳单前缩略）", "daily"),
    ("una", "art./num.", "一个（阴单）", "daily"),
    ("dos", "num.", "二", "daily"),
    ("tres", "num.", "三", "daily"),
    ("cuatro", "num.", "四", "daily"),
    ("cinco", "num.", "五", "daily"),
    ("seis", "num.", "六", "daily"),
    ("siete", "num.", "七", "daily"),
    ("ocho", "num.", "八", "daily"),
    ("nueve", "num.", "九", "daily"),
    ("diez", "num.", "十", "daily"),
    ("once", "num.", "十一", "daily"),
    ("doce", "num.", "十二", "daily"),
    ("trece", "num.", "十三", "daily"),
    ("catorce", "num.", "十四", "daily"),
    ("quince", "num.", "十五", "daily"),
    ("dieciséis", "num.", "十六", "daily"),
    ("diecisiete", "num.", "十七", "daily"),
    ("dieciocho", "num.", "十八", "daily"),
    ("diecinueve", "num.", "十九", "daily"),
    ("veinte", "num.", "二十", "daily"),
    ("veintiuno", "num.", "二十一", "daily"),
    ("veintidós", "num.", "二十二", "daily"),
    ("veintitrés", "num.", "二十三", "daily"),
    ("veinticuatro", "num.", "二十四", "daily"),
    ("veinticinco", "num.", "二十五", "daily"),
    ("veintiséis", "num.", "二十六", "daily"),
    ("veintisiete", "num.", "二十七", "daily"),
    ("veintiocho", "num.", "二十八", "daily"),
    ("veintinueve", "num.", "二十九", "daily"),
    ("treinta", "num.", "三十", "daily"),
    ("cuarenta", "num.", "四十", "daily"),
    ("cincuenta", "num.", "五十", "daily"),
    ("sesenta", "num.", "六十", "daily"),
    ("setenta", "num.", "七十", "daily"),
    ("ochenta", "num.", "八十", "daily"),
    ("noventa", "num.", "九十", "daily"),
    ("cien", "num.", "一百", "daily"),
    ("ciento", "num.", "一百多", "daily"),
    ("doscientos", "num.", "两百", "daily"),
    ("trescientos", "num.", "三百", "daily"),
    ("cuatrocientos", "num.", "四百", "daily"),
    ("quinientos", "num.", "五百", "daily"),
    ("seiscientos", "num.", "六百", "daily"),
    ("setecientos", "num.", "七百", "daily"),
    ("ochocientos", "num.", "八百", "daily"),
    ("novecientos", "num.", "九百", "daily"),
    ("mil", "num.", "一千", "daily"),
    ("dos mil", "num.", "两千", "daily"),
    ("millón", "m.", "百万", "daily"),
    ("primero", "adj.", "第一的", "daily"),
    ("segundo", "adj./m.", "第二的；秒", "daily"),
    ("tercero", "adj.", "第三的", "daily"),
    ("cuarto", "adj./m.", "第四的；房间", "daily"),
    ("quinto", "adj.", "第五的", "daily"),
    ("sexto", "adj.", "第六的", "daily"),
    ("séptimo", "adj.", "第七的", "daily"),
    ("octavo", "adj.", "第八的", "daily"),
    ("noveno", "adj.", "第九的", "daily"),
    ("décimo", "adj.", "第十的", "daily"),
    ("último", "adj.", "最后的，最新的", "daily"),

    # --- Cantidades y expresiones ---
    ("mucho", "adj./adv.", "许多，很多", "daily"),
    ("mucha", "adj.", "许多（阴）", "daily"),
    ("muchos", "adj./pron.", "很多个（阳复）", "daily"),
    ("muchas", "adj./pron.", "很多个（阴复）", "daily"),
    ("poco", "adj./adv.", "很少，少许", "daily"),
    ("poca", "adj.", "很少（阴）", "daily"),
    ("pocos", "adj./pron.", "少数（阳复）", "daily"),
    ("pocas", "adj./pron.", "少数（阴复）", "daily"),
    ("bastante", "adj./adv.", "相当，足够", "daily"),
    ("demasiado", "adj./adv.", "太，过多", "daily"),
    ("más", "adv.", "更，加", "daily"),
    ("menos", "adv.", "较少，减", "daily"),
    ("tan", "adv.", "如此，这么", "daily"),
    ("tanto", "adj./adv.", "这么多", "daily"),
    ("todo", "adj./pron.", "全部，所有的", "daily"),
    ("toda", "adj.", "全部（阴）", "daily"),
    ("todos", "adj./pron.", "所有人，每天", "daily"),
    ("todas", "adj./pron.", "全部（阴复）", "daily"),
    ("nada", "pron./adv.", "什么都没有，毫不", "daily"),
    ("algo", "pron./adv.", "某些东西，有点", "daily"),
    ("alguien", "pron.", "某人，有人", "daily"),
    ("nadie", "pron.", "没有人", "daily"),
    ("alguno", "adj./pron.", "某个，某些", "grammar"),
    ("ninguno", "adj./pron.", "没有任何一个", "grammar"),
    ("algún", "adj.", "某个（阳单前置）", "grammar"),
    ("ningún", "adj.", "没有一个（阳单前置）", "grammar"),
    ("cada", "adj.", "每个，各个", "daily"),
    ("ambos", "adj./pron.", "两者，双方", "daily"),
    ("medio", "adj./m.", "一半的；中间", "daily"),
    ("mitad", "f.", "一半，二分之一", "daily"),
    ("doble", "adj./m.", "双倍的", "daily"),

    # --- Tiempo, días, meses y estaciones ---
    ("tiempo", "m.", "时间；天气", "daily"),
    ("hora", "f.", "小时；点钟", "daily"),
    ("minuto", "m.", "分钟", "daily"),
    ("segundo", "m.", "秒", "daily"),
    ("momento", "m.", "时刻，瞬间", "daily"),
    ("rato", "m.", "一会儿，片刻", "daily"),
    ("día", "m.", "天，日子，白天", "daily"),
    ("noche", "f.", "夜晚", "daily"),
    ("mañana", "f./adv.", "早晨，上午；明天", "daily"),
    ("mediodía", "m.", "中午，正午", "daily"),
    ("tarde", "f./adv.", "下午；迟，晚", "daily"),
    ("medianoche", "f.", "午夜，半夜", "daily"),
    ("semana", "f.", "周，星期", "daily"),
    ("fin de semana", "m.", "周末", "daily"),
    ("mes", "m.", "月份", "daily"),
    ("año", "m.", "年，岁", "daily"),
    ("siglo", "m.", "世纪，百年", "daily"),
    ("fecha", "f.", "日期", "daily"),
    ("calendario", "m.", "日历", "daily"),
    ("hoy", "adv.", "今天", "daily"),
    ("ayer", "adv.", "昨天", "daily"),
    ("anteayer", "adv.", "前天", "daily"),
    ("anoche", "adv.", "昨晚", "daily"),
    ("ahora", "adv.", "现在", "daily"),
    ("luego", "adv.", "随后，然后", "daily"),
    ("después", "adv.", "在...之后，后来", "daily"),
    ("antes", "adv.", "在...之前，以前", "daily"),
    ("siempre", "adv.", "总是，永远", "daily"),
    ("nunca", "adv.", "从不，绝不", "daily"),
    ("jamás", "adv.", "决不", "daily"),
    ("a veces", "exp.", "有时，偶尔", "daily"),
    ("a menudo", "exp.", "经常，常常", "daily"),
    ("frecuentemente", "adv.", "频繁地", "daily"),
    ("raramente", "adv.", "罕见地，很少", "daily"),
    ("temprano", "adv.", "早", "daily"),
    ("pronto", "adv.", "很快，马上", "daily"),
    ("tarde", "adv.", "晚，迟", "daily"),
    ("ya", "adv.", "已经，立刻", "daily"),
    ("todavía", "adv.", "仍然，还", "daily"),
    ("aún", "adv.", "尚且，还", "daily"),
    ("mientras", "conj./adv.", "当...之时；同时", "grammar"),
    ("durante", "prep.", "在...期间", "grammar"),
    ("lunes", "m.", "星期一", "daily"),
    ("martes", "m.", "星期二", "daily"),
    ("miércoles", "m.", "星期三", "daily"),
    ("jueves", "m.", "星期四", "daily"),
    ("viernes", "m.", "星期五", "daily"),
    ("sábado", "m.", "星期六", "daily"),
    ("domingo", "m.", "星期天", "daily"),
    ("enero", "m.", "一月", "daily"),
    ("febrero", "m.", "二月", "daily"),
    ("marzo", "m.", "三月", "daily"),
    ("abril", "m.", "四月", "daily"),
    ("mayo", "m.", "五月", "daily"),
    ("junio", "m.", "六月", "daily"),
    ("julio", "m.", "七月", "daily"),
    ("agosto", "m.", "八月", "daily"),
    ("septiembre", "m.", "九月", "daily"),
    ("octubre", "m.", "十月", "daily"),
    ("noviembre", "m.", "十一月", "daily"),
    ("diciembre", "m.", "十二月", "daily"),
    ("primavera", "f.", "春季", "daily"),
    ("verano", "m.", "夏季", "daily"),
    ("otoño", "m.", "秋季", "daily"),
    ("invierno", "m.", "冬季", "daily"),
    ("estación", "f.", "季节；车站", "daily"),

    # --- Personas, familia e identidad ---
    ("persona", "f.", "人", "daily"),
    ("hombre", "m.", "男人，人类", "daily"),
    ("mujer", "f.", "女人，妻子", "daily"),
    ("niño", "m.", "男孩，儿童", "daily"),
    ("niña", "f.", "女孩", "daily"),
    ("chico", "m.", "小伙子，男孩", "daily"),
    ("chica", "f.", "姑娘，女孩", "daily"),
    ("joven", "adj./m.f.", "年轻的；青年", "daily"),
    ("anciano", "m./adj.", "老人；年迈的", "daily"),
    ("padre", "m.", "父亲", "daily"),
    ("madre", "f.", "母亲", "daily"),
    ("padres", "m.pl.", "父母，双亲", "daily"),
    ("papá", "m.", "爸爸", "daily"),
    ("mamá", "f.", "妈妈", "daily"),
    ("hijo", "m.", "儿子", "daily"),
    ("hija", "f.", "女儿", "daily"),
    ("hijos", "m.pl.", "儿女，孩子们", "daily"),
    ("hermano", "m.", "兄弟，哥哥，弟弟", "daily"),
    ("hermana", "f.", "姐妹，姐姐，妹妹", "daily"),
    ("hermanos", "m.pl.", "兄弟姐妹", "daily"),
    ("abuelo", "m.", "爷爷，外公", "daily"),
    ("abuela", "f.", "奶奶，外婆", "daily"),
    ("abuelos", "m.pl.", "祖父母，外祖父母", "daily"),
    ("nieto", "m.", "孙子，外孙", "daily"),
    ("nieta", "f.", "孙女，外孙女", "daily"),
    ("tío", "m.", "叔伯舅姑父", "daily"),
    ("tía", "f.", "姑姨婶伯母", "daily"),
    ("primo", "m.", "堂表兄弟", "daily"),
    ("prima", "f.", "堂表姐妹", "daily"),
    ("sobrino", "m.", "侄子，外甥", "daily"),
    ("sobrina", "f.", "侄女，外甥女", "daily"),
    ("marido", "m.", "丈夫", "daily"),
    ("mujer", "f.", "妻子；女人", "daily"),
    ("esposo", "m.", "配偶，丈夫", "daily"),
    ("esposa", "f.", "配偶，妻子", "daily"),
    ("novio", "m.", "男朋友，新郎", "daily"),
    ("novia", "f.", "女朋友，新娘", "daily"),
    ("pareja", "f.", "伴侣，一对", "daily"),
    ("amigo", "m.", "朋友（男）", "daily"),
    ("amiga", "f.", "朋友（女）", "daily"),
    ("compañero", "m.", "同伴，同学，同事", "daily"),
    ("vecino", "m.", "邻居", "daily"),
    ("bebé", "m.", "婴儿", "daily"),
    ("gente", "f.", "人们，大家", "daily"),
    ("nombre", "m.", "名字", "daily"),
    ("apellido", "m.", "姓氏", "daily"),
    ("edad", "f.", "年龄", "daily"),
    ("cumpleaños", "m.", "生日", "daily"),
    ("lugar de nacimiento", "m.", "出生地", "daily"),
    ("estado civil", "m.", "婚姻状况", "daily"),
    ("soltero", "adj.", "单身的，未婚的", "daily"),
    ("casado", "adj.", "已婚的", "daily"),
    ("divorciado", "adj.", "离异的", "daily"),
    ("viudo", "adj.", "鳏寡的，丧偶的", "daily"),
    ("país", "m.", "国家", "travel"),
    ("nacionalidad", "f.", "国籍", "daily"),
    ("origen", "m.", "起源，原籍", "daily"),
    ("extranjero", "m./adj.", "外国人；外国的", "travel"),
    ("idioma", "m.", "语言", "daily"),
    ("lengua", "f.", "舌头；语言", "daily"),
    ("español", "m./adj.", "西班牙语；西班牙的", "daily"),
    ("castellano", "m./adj.", "卡斯蒂利亚语（西语）", "daily"),
    ("inglés", "m./adj.", "英语；英国的", "daily"),
    ("francés", "m./adj.", "法语；法国的", "daily"),
    ("alemán", "m./adj.", "德语；德国的", "daily"),
    ("italiano", "m./adj.", "意大利语；意大利的", "daily"),
    ("portugués", "m./adj.", "葡萄牙语；葡萄牙的", "daily"),
    ("chino", "m./adj.", "汉语；中国的", "daily"),
    ("japonés", "m./adj.", "日语；日本的", "daily"),
    ("ruso", "m./adj.", "俄语；俄罗斯的", "daily"),
    ("árabe", "m./adj.", "阿拉伯语；阿拉伯的", "daily"),

    # --- Profesiones y trabajo básico ---
    ("profesión", "f.", "职业", "daily"),
    ("oficio", "m.", "手艺，行当", "daily"),
    ("trabajo", "m.", "工作", "daily"),
    ("estudiante", "m./f.", "学生", "daily"),
    ("alumno", "m.", "学员，小学生", "daily"),
    ("profesor", "m.", "教师，教授", "daily"),
    ("profesora", "f.", "女教师", "daily"),
    ("maestro", "m.", "师傅，小学老师", "daily"),
    ("médico", "m.", "医生", "daily"),
    ("doctor", "m.", "医生，博士", "daily"),
    ("enfermero", "m.", "男护士", "daily"),
    ("enfermera", "f.", "女护士", "daily"),
    ("camarero", "m.", "男服务员", "food"),
    ("camarera", "f.", "女服务员", "food"),
    ("cocinero", "m.", "厨师", "food"),
    ("policía", "m./f.", "警察", "daily"),
    ("bombero", "m.", "消防员", "daily"),
    ("dependiente", "m.", "男店员，售货员", "daily"),
    ("secretario", "m.", "男秘书", "daily"),
    ("secretaria", "f.", "女秘书", "daily"),
    ("abogado", "m.", "男律师", "business"),
    ("ingeniero", "m.", "男工程师", "business"),
    ("arquitecto", "m.", "建筑师", "business"),
    ("periodista", "m./f.", "记者", "daily"),
    ("escritor", "m.", "作家", "daily"),
    ("pintor", "m.", "画家，油漆工", "daily"),
    ("músico", "m.", "音乐家", "daily"),
    ("actor", "m.", "男演员", "daily"),
    ("actriz", "f.", "女演员", "daily"),
    ("cantante", "m./f.", "歌手", "daily"),
    ("conductor", "m.", "司机", "travel"),
    ("taxista", "m./f.", "出租车司机", "travel"),
    ("peluquero", "m.", "理发师", "daily"),
    ("mecánico", "m.", "机修工", "daily"),
    ("fontanero", "m.", "水管工", "daily"),
    ("electricista", "m./f.", "电工", "daily"),
    ("cartero", "m.", "邮递员", "daily"),

    # --- La casa, estancias y muebles ---
    ("casa", "f.", "家，房子", "daily"),
    ("hogar", "m.", "家园，家庭", "daily"),
    ("piso", "m.", "公寓，楼层", "daily"),
    ("apartamento", "m.", "套房，公寓", "daily"),
    ("edificio", "m.", "大楼，建筑", "daily"),
    ("residencia", "f.", "住所，宿舍", "daily"),
    ("habitación", "f.", "房间", "daily"),
    ("dormitorio", "m.", "卧室", "daily"),
    ("cuarto", "m.", "房间，屋子", "daily"),
    ("sala", "f.", "厅，大厅", "daily"),
    ("salón", "m.", "客厅", "daily"),
    ("comedor", "m.", "餐厅", "food"),
    ("cocina", "f.", "厨房", "food"),
    ("baño", "m.", "浴室，洗手间", "daily"),
    ("aseo", "m.", "卫生间", "daily"),
    ("pasillo", "m.", "走廊，过道", "daily"),
    ("recibidor", "m.", "门厅，玄关", "daily"),
    ("entrada", "f.", "入口，大门", "daily"),
    ("salida", "f.", "出口", "daily"),
    ("puerta", "f.", "门", "daily"),
    ("ventana", "f.", "窗户", "daily"),
    ("pared", "f.", "墙壁", "daily"),
    ("muro", "m.", "围墙，石墙", "daily"),
    ("suelo", "m.", "地面，地板", "daily"),
    ("techo", "m.", "天花板，屋顶", "daily"),
    ("tejado", "m.", "屋顶瓦片", "daily"),
    ("balcón", "m.", "阳台", "daily"),
    ("terraza", "f.", "露台，平台", "daily"),
    ("jardín", "m.", "花园", "daily"),
    ("patio", "m.", "天井，院子", "daily"),
    ("garaje", "m.", "车库", "daily"),
    ("sótano", "m.", "地下室", "daily"),
    ("trastero", "m.", "储藏室", "daily"),
    ("escalera", "f.", "楼梯", "daily"),
    ("ascensor", "m.", "电梯", "daily"),
    ("mueble", "m.", "家具", "daily"),
    ("cama", "f.", "床", "daily"),
    ("colchón", "m.", "床垫", "daily"),
    ("sábana", "f.", "床单", "daily"),
    ("manta", "f.", "毛毯，毯子", "daily"),
    ("almohada", "f.", "枕头", "daily"),
    ("mesa", "f.", "桌子", "daily"),
    ("escritorio", "m.", "书桌，办公桌", "daily"),
    ("silla", "f.", "椅子", "daily"),
    ("sillón", "m.", "扶手椅", "daily"),
    ("sofá", "m.", "沙发", "daily"),
    ("armario", "m.", "衣柜，橱柜", "daily"),
    ("estantería", "f.", "书架，置物架", "daily"),
    ("cajón", "m.", "抽屉", "daily"),
    ("cómoda", "f.", "五斗橱，梳妆台", "daily"),
    ("lámpara", "f.", "灯，台灯", "daily"),
    ("luz", "f.", "光线，电灯", "daily"),
    ("espejo", "m.", "镜子", "daily"),
    ("cuadro", "m.", "画，框架", "daily"),
    ("alfombra", "f.", "地毯", "daily"),
    ("cortina", "f.", "窗帘", "daily"),
    ("reloj", "m.", "钟表", "daily"),
    ("despertador", "m.", "闹钟", "daily"),
    ("llave", "f.", "钥匙", "daily"),
    ("cerradura", "f.", "锁", "daily"),
    ("timbre", "m.", "门铃", "daily"),
    ("buzón", "m.", "邮箱，信箱", "daily"),

    # --- Electrodomésticos y objetos ---
    ("teléfono", "m.", "电话", "daily"),
    ("móvil", "m.", "手机", "daily"),
    ("celular", "m.", "手机（拉美）", "daily"),
    ("ordenador", "m.", "电脑", "daily"),
    ("computadora", "f.", "电脑（拉美）", "daily"),
    ("portátil", "m./adj.", "笔记本电脑；便携的", "daily"),
    ("pantalla", "f.", "屏幕", "daily"),
    ("teclado", "m.", "键盘", "daily"),
    ("ratón", "m.", "鼠标；老鼠", "daily"),
    ("televisión", "f.", "电视", "daily"),
    ("tele", "f.", "电视（口语）", "daily"),
    ("mando", "m.", "遥控器", "daily"),
    ("radio", "f.", "收音机，广播", "daily"),
    ("nevera", "f.", "冰箱", "food"),
    ("frigorífico", "m.", "电冰箱", "food"),
    ("congelador", "m.", "冷冻柜", "food"),
    ("lavadora", "f.", "洗衣机", "daily"),
    ("lavavajillas", "m.", "洗碗机", "daily"),
    ("microondas", "m.", "微波炉", "food"),
    ("horno", "m.", "烤箱", "food"),
    ("cocina eléctrica", "f.", "电磁炉", "food"),
    ("tostadora", "f.", "烤面包机", "food"),
    ("cafetera", "f.", "咖啡壶，咖啡机", "food"),
    ("plancha", "f.", "熨斗；铁板", "daily"),
    ("aspiradora", "f.", "吸尘器", "daily"),
    ("calefacción", "f.", "暖气", "daily"),
    ("aire acondicionado", "m.", "空调", "daily"),
    ("ventilador", "m.", "风扇", "daily"),

    # --- Vajilla y utensilios de cocina ---
    ("plato", "m.", "盘子；一道菜", "food"),
    ("vaso", "m.", "玻璃杯", "food"),
    ("copa", "f.", "高脚杯", "food"),
    ("taza", "f.", "马克杯，茶杯", "food"),
    ("jarra", "f.", "大水壶，大扎杯", "food"),
    ("cubiertos", "m.pl.", "刀叉餐具", "food"),
    ("cuchara", "f.", "勺子", "food"),
    ("cucharilla", "f.", "小茶匙", "food"),
    ("tenedor", "m.", "叉子", "food"),
    ("cuchillo", "m.", "餐刀", "food"),
    ("servilleta", "f.", "餐巾纸", "food"),
    ("mantel", "m.", "桌布", "food"),
    ("sartén", "f.", "平底锅", "food"),
    ("olla", "f.", "煮锅，深锅", "food"),
    ("cazuela", "f.", "砂锅", "food"),
    ("botella", "f.", "瓶子", "food"),
    ("lata", "f.", "易拉罐，罐头", "food"),
    ("abrelatas", "m.", "开罐器", "food"),
    ("sacacorchos", "m.", "开瓶器", "food"),
    ("caja", "f.", "盒子，收银台", "daily"),
    ("bolsa", "f.", "塑料袋，袋子", "daily"),
    ("cubo de basura", "m.", "垃圾桶", "daily"),

    # --- Material escolar y de oficina ---
    ("papel", "m.", "纸张", "daily"),
    ("hoja", "f.", "树叶；活页纸", "daily"),
    ("bolígrafo", "m.", "圆珠笔", "daily"),
    ("boli", "m.", "笔（口语）", "daily"),
    ("lápiz", "m.", "铅笔", "daily"),
    ("pluma", "f.", "钢笔；羽毛", "daily"),
    ("goma", "f.", "橡皮擦", "daily"),
    ("sacapuntas", "m.", "卷笔刀", "daily"),
    ("regla", "f.", "尺子；规则", "daily"),
    ("tijeras", "f.pl.", "剪刀", "daily"),
    ("pegamento", "m.", "胶水", "daily"),
    ("cuaderno", "m.", "笔记本", "daily"),
    ("libreta", "f.", "便签本", "daily"),
    ("libro", "m.", "书籍", "daily"),
    ("diccionario", "m.", "词典，字典", "daily"),
    ("carpeta", "f.", "文件夹", "daily"),
    ("estuche", "m.", "文具盒", "daily"),
    ("mochila", "f.", "双肩背包", "daily"),
    ("pizarra", "f.", "黑板，白板", "daily"),
    ("tiza", "f.", "粉笔", "daily"),
    ("marcador", "m.", "荧光记号笔", "daily"),
    ("carta", "f.", "信件；菜单；卡牌", "daily"),
    ("tarjeta", "f.", "卡片，名片", "daily"),
    ("postal", "f.", "明信片", "travel"),
    ("sello", "m.", "邮票；印章", "daily"),
    ("sobre", "m./prep.", "信封；在...之上", "daily"),

    # --- Colores ---
    ("blanco", "adj.", "白色的", "daily"),
    ("negro", "adj.", "黑色的", "daily"),
    ("rojo", "adj.", "红色的", "daily"),
    ("azul", "adj.", "蓝色的", "daily"),
    ("verde", "adj.", "绿色的", "daily"),
    ("amarillo", "adj.", "黄色的", "daily"),
    ("naranja", "adj./f.", "橙色的；橙子", "daily"),
    ("rosa", "adj./f.", "粉色的；玫瑰", "daily"),
    ("gris", "adj.", "灰色的", "daily"),
    ("marrón", "adj.", "棕色的，褐色的", "daily"),
    ("morado", "adj.", "紫色的", "daily"),
    ("violeta", "adj./f.", "紫罗兰色的", "daily"),
    ("dorado", "adj.", "金色的", "daily"),
    ("plateado", "adj.", "银色的", "daily"),
    ("claro", "adj.", "浅色的；明亮的", "daily"),
    ("oscuro", "adj.", "深色的；昏暗的", "daily"),
    ("color", "m.", "颜色", "daily"),

    # --- Adjetivos básicos y descriptivos ---
    ("grande", "adj.", "大的", "daily"),
    ("pequeño", "adj.", "小的", "daily"),
    ("enorme", "adj.", "巨大的", "daily"),
    ("alto", "adj.", "高的", "daily"),
    ("bajo", "adj.", "矮的，低的", "daily"),
    ("gordo", "adj.", "胖的，厚的", "daily"),
    ("delgado", "adj.", "苗条的，瘦的", "daily"),
    ("flaco", "adj.", "干瘦的", "daily"),
    ("fuerte", "adj.", "强壮的，浓烈的", "daily"),
    ("débil", "adj.", "虚弱的", "daily"),
    ("nuevo", "adj.", "崭新的", "daily"),
    ("viejo", "adj.", "老旧的，陈旧的", "daily"),
    ("antiguo", "adj.", "古老的", "daily"),
    ("moderno", "adj.", "现代的", "daily"),
    ("bueno", "adj.", "好的，优秀的", "daily"),
    ("buen", "adj.", "好（阳单前置）", "daily"),
    ("malo", "adj.", "差的，坏的", "daily"),
    ("mal", "adj./adv.", "坏（阳单前置）；坏地", "daily"),
    ("bonito", "adj.", "好看的，漂亮的", "daily"),
    ("hermoso", "adj.", "美丽的", "daily"),
    ("lindo", "adj.", "清秀的，可爱的", "daily"),
    ("feo", "adj.", "难看的，丑陋的", "daily"),
    ("guapo", "adj.", "英俊的，漂亮的", "daily"),
    ("fácil", "adj.", "容易的，简单的", "daily"),
    ("sencillo", "adj.", "朴素的，简易的", "daily"),
    ("difícil", "adj.", "困难的", "daily"),
    ("complicado", "adj.", "复杂的", "daily"),
    ("caro", "adj.", "昂贵的", "daily"),
    ("barato", "adj.", "便宜的", "daily"),
    ("económico", "adj.", "经济实惠的", "daily"),
    ("rápido", "adj./adv.", "快速的；快地", "daily"),
    ("lento", "adj./adv.", "缓慢的；慢地", "daily"),
    ("limpio", "adj.", "干净的，清洁的", "daily"),
    ("sucio", "adj.", "脏的，污秽的", "daily"),
    ("caliente", "adj.", "温热的，滚烫的", "food"),
    ("cálido", "adj.", "温暖的", "daily"),
    ("frío", "adj./m.", "冰冷的；寒冷", "daily"),
    ("fresco", "adj.", "凉爽的，新鲜的", "food"),
    ("rico", "adj.", "美味的；富裕的", "food"),
    ("delicioso", "adj.", "可口的，极其美味的", "food"),
    ("sabroso", "adj.", "有风味的", "food"),
    ("pobre", "adj.", "贫穷的，可怜的", "daily"),
    ("simpático", "adj.", "平易近人的，和蔼的", "emotion"),
    ("antipático", "adj.", "讨人嫌的，冷漠的", "emotion"),
    ("amable", "adj.", "友善的，客气的", "emotion"),
    ("inteligente", "adj.", "聪颖的", "daily"),
    ("listo", "adj.", "机灵的；准备就绪的", "daily"),
    ("tonto", "adj.", "愚笨的", "daily"),
    ("divertido", "adj.", "有趣的，好玩的", "emotion"),
    ("aburrido", "adj.", "无聊的，乏味的", "emotion"),
    ("interesante", "adj.", "有意思的，耐人寻味的", "daily"),
    ("alegre", "adj.", "开朗的，快乐的", "emotion"),
    ("triste", "adj.", "悲伤的", "emotion"),
    ("feliz", "adj.", "幸福的，快乐的", "emotion"),
    ("contento", "adj.", "满意的，高兴的", "emotion"),
    ("enfadado", "adj.", "生气的，恼怒的", "emotion"),
    ("enojado", "adj.", "生气的（拉美）", "emotion"),
    ("nervioso", "adj.", "紧张的", "emotion"),
    ("tranquilo", "adj.", "平静的，镇定的", "emotion"),
    ("cansado", "adj.", "劳累的，疲惫的", "daily"),
    ("enfermo", "adj.", "生病的", "daily"),
    ("sano", "adj.", "健康的", "daily"),
    ("abierto", "adj.", "开门的，开放的", "daily"),
    ("cerrado", "adj.", "关着的，关闭的", "daily"),
    ("libre", "adj.", "空闲的，自由的", "daily"),
    ("ocupado", "adj.", "忙碌的，被占用的", "daily"),
    ("lleno", "adj.", "满载的，饱满的", "daily"),
    ("vacío", "adj.", "空荡的", "daily"),
    ("correcto", "adj.", "正确的", "daily"),
    ("incorrecto", "adj.", "错误的", "daily"),
    ("mismo", "adj.", "同一的，同样的", "daily"),
    ("igual", "adj.", "平等的，相同的", "daily"),
    ("diferente", "adj.", "不同的", "daily"),
    ("distinto", "adj.", "有差异的", "daily"),
    ("seguro", "adj./m.", "确凿的，安全的；保险", "daily"),
    ("peligroso", "adj.", "危险的", "daily"),
    ("importante", "adj.", "重大的，要紧的", "daily"),
    ("principal", "adj.", "主要的，首要的", "daily"),
    ("necesario", "adj.", "必须的，必要的", "daily"),
    ("posible", "adj.", "有可能的", "daily"),
    ("imposible", "adj.", "办不到的", "daily"),
    ("verdadero", "adj.", "真实的", "daily"),
    ("falso", "adj.", "虚假的", "daily"),
    ("perfecto", "adj.", "完美的", "daily"),

    # --- Comida y bebidas ---
    ("comida", "f.", "食品，饭菜；午餐", "food"),
    ("alimento", "m.", "食物，养料", "food"),
    ("bebida", "f.", "饮料", "food"),
    ("agua", "f.", "水", "food"),
    ("agua mineral", "f.", "矿泉水", "food"),
    ("agua con gas", "f.", "气泡水", "food"),
    ("agua sin gas", "f.", "纯净水", "food"),
    ("pan", "m.", "面包", "food"),
    ("leche", "f.", "牛奶", "food"),
    ("café", "m.", "咖啡", "food"),
    ("café solo", "m.", "意式浓缩黑咖啡", "food"),
    ("café con leche", "m.", "拿铁牛奶咖啡", "food"),
    ("café cortado", "m.", "浓缩加微量牛奶", "food"),
    ("té", "m.", "茶", "food"),
    ("infusión", "f.", "花草茶", "food"),
    ("zumo", "m.", "果汁", "food"),
    ("jugo", "m.", "果汁（拉美）", "food"),
    ("refresco", "m.", "汽水，清凉饮料", "food"),
    ("vino", "m.", "葡萄酒", "food"),
    ("vino tinto", "m.", "红葡萄酒", "food"),
    ("vino blanco", "m.", "白葡萄酒", "food"),
    ("cerveza", "f.", "啤酒", "food"),
    ("caña", "f.", "一小杯生啤", "food"),
    ("carne", "f.", "肉类", "food"),
    ("ternera", "f.", "牛肉，小牛肉", "food"),
    ("cerdo", "m.", "猪肉；生猪", "food"),
    ("pollo", "m.", "鸡肉", "food"),
    ("pescado", "m.", "食用鱼，海鲜鱼类", "food"),
    ("marisco", "m.", "海鲜，贝壳类", "food"),
    ("gamba", "f.", "虾，大虾", "food"),
    ("atún", "m.", "金枪鱼", "food"),
    ("salmón", "m.", "三文鱼", "food"),
    ("huevo", "m.", "鸡蛋", "food"),
    ("queso", "m.", "芝士，奶酪", "food"),
    ("arroz", "m.", "米饭，大米", "food"),
    ("pasta", "f.", "意大利面", "food"),
    ("espaguetis", "m.pl.", "意式细面", "food"),
    ("sopa", "f.", "热汤", "food"),
    ("caldo", "m.", "清汤，高汤", "food"),
    ("ensalada", "f.", "沙拉，凉拌菜", "food"),
    ("fruta", "f.", "新鲜水果", "food"),
    ("manzana", "f.", "苹果", "food"),
    ("plátano", "m.", "香蕉", "food"),
    ("naranja", "f.", "甜橙", "food"),
    ("limón", "m.", "柠檬", "food"),
    ("fresa", "f.", "草莓", "food"),
    ("uva", "f.", "葡萄", "food"),
    ("sandía", "f.", "西瓜", "food"),
    ("melón", "m.", "甜瓜，哈密瓜", "food"),
    ("melocotón", "m.", "桃子", "food"),
    ("pera", "f.", "梨", "food"),
    ("piña", "f.", "菠萝", "food"),
    ("verdura", "f.", "蔬菜", "food"),
    ("vegetales", "m.pl.", "时蔬", "food"),
    ("tomate", "m.", "番茄", "food"),
    ("patata", "f.", "马铃薯，土豆", "food"),
    ("papa", "f.", "土豆（拉美）", "food"),
    ("cebolla", "f.", "洋葱", "food"),
    ("ajo", "m.", "大蒜", "food"),
    ("lechuga", "f.", "生菜", "food"),
    ("zanahoria", "f.", "胡萝卜", "food"),
    ("pepino", "m.", "黄瓜", "food"),
    ("pimiento", "m.", "彩椒，甜椒", "food"),
    ("champiñón", "m.", "口蘑", "food"),
    ("seta", "f.", "食用菌，蘑菇", "food"),
    ("sal", "f.", "食用食盐", "food"),
    ("azúcar", "m./f.", "白糖", "food"),
    ("aceite", "m.", "油", "food"),
    ("aceite de oliva", "m.", "特级初榨橄榄油", "food"),
    ("vinagre", "m.", "食用醋", "food"),
    ("mantequilla", "f.", "黄油", "food"),
    ("pimienta", "f.", "胡椒粉", "food"),
    ("salsa", "f.", "调味酱汁", "food"),
    ("bocadillo", "m.", "西班牙式长棍三明治", "food"),
    ("sándwich", "m.", "吐司三明治", "food"),
    ("tapas", "f.pl.", "佐酒小食", "food"),
    ("ración", "f.", "一大份菜肴", "food"),
    ("paella", "f.", "西班牙铁盘海鲜饭", "food"),
    ("tortilla", "f.", "西式土豆厚蛋饼", "food"),
    ("tortilla española", "f.", "西班牙经典蛋饼", "food"),
    ("tortilla francesa", "f.", "原味煎蛋卷", "food"),
    ("jamón", "m.", "风干火腿", "food"),
    ("jamón serrano", "m.", "塞拉诺山地火腿", "food"),
    ("jamón ibérico", "m.", "伊比利亚橡果黑猪火腿", "food"),
    ("chorizo", "m.", "西式辣香肠", "food"),
    ("helado", "m.", "冰淇淋雪糕", "food"),
    ("chocolate", "m.", "巧克力", "food"),
    ("pastel", "m.", "蛋糕", "food"),
    ("tarta", "f.", "生日大蛋糕", "food"),
    ("galleta", "f.", "曲奇饼干", "food"),
    ("caramelo", "m.", "硬糖，焦糖", "food"),
    ("dulce", "adj./m.", "甘甜的；甜品", "food"),
    ("salado", "adj.", "咸味的", "food"),
    ("amargo", "adj.", "苦涩的", "food"),
    ("ácido", "adj.", "酸涩的", "food"),
    ("picante", "adj.", "香辣辛辣的", "food"),
    ("desayuno", "m.", "早晨餐饮", "food"),
    ("almuerzo", "m.", "午间大餐", "food"),
    ("comida", "f.", "正餐午饭", "food"),
    ("cena", "f.", "夜间晚饭", "food"),
    ("merienda", "f.", "下午四五点茶点", "food"),
    ("aperitivo", "m.", "开胃前菜，开胃酒", "food"),
    ("menú", "m.", "每日套餐，菜单", "food"),
    ("carta", "f.", "单点菜单", "food"),
    ("primer plato", "m.", "头盘，第一道菜", "food"),
    ("segundo plato", "m.", "主盘，第二道菜", "food"),
    ("postre", "m.", "饭后甜点", "food"),
    ("cuenta", "f.", "结账账单", "food"),
    ("propina", "f.", "自愿小费", "food"),

    # --- Ropa y calzado ---
    ("ropa", "f.", "衣物服装", "daily"),
    ("camisa", "f.", "正装长袖衬衫", "daily"),
    ("camiseta", "f.", "短袖圆领文化衫", "daily"),
    ("polo", "m.", "POLO翻领衫", "daily"),
    ("blusa", "f.", "女士衬衫", "daily"),
    ("pantalón", "m.", "长裤", "daily"),
    ("pantalones", "m.pl.", "裤子", "daily"),
    ("vaqueros", "m.pl.", "牛仔长裤", "daily"),
    ("jeans", "m.pl.", "牛仔裤", "daily"),
    ("pantalón corto", "m.", "清凉短裤", "daily"),
    ("falda", "f.", "半身裙", "daily"),
    ("minifalda", "f.", "超短裙", "daily"),
    ("vestido", "m.", "连体长裙，礼服", "daily"),
    ("traje", "m.", "男士西服套装", "daily"),
    ("corbata", "f.", "领带", "daily"),
    ("abrigo", "m.", "加厚大衣", "daily"),
    ("chaqueta", "f.", "防风夹克，西装外褂", "daily"),
    ("cazadora", "f.", "短夹克", "daily"),
    ("jersey", "m.", "针织毛衫", "daily"),
    ("suéter", "m.", "套头毛衣", "daily"),
    ("sudadera", "f.", "连帽卫衣", "daily"),
    ("chaleco", "m.", "马甲，背心", "daily"),
    ("pijama", "m.", "家居睡衣", "daily"),
    ("bañador", "m.", "游泳衣，泳裤", "daily"),
    ("bikini", "m.", "比基尼泳装", "daily"),
    ("ropa interior", "f.", "贴身内衣", "daily"),
    ("bragas", "f.pl.", "女士三角内裤", "daily"),
    ("calzoncillos", "m.pl.", "男士平角短裤", "daily"),
    ("zapato", "m.", "皮鞋", "daily"),
    ("zapatos", "m.pl.", "鞋靴", "daily"),
    ("zapatillas", "f.pl.", "平底运动球鞋", "daily"),
    ("tenis", "m.pl.", "网球鞋", "daily"),
    ("bota", "f.", "高帮靴子", "daily"),
    ("sandalia", "f.", "凉鞋", "daily"),
    ("chanclas", "f.pl.", "人字拖鞋", "daily"),
    ("tacones", "m.pl.", "女士高跟鞋", "daily"),
    ("calcetín", "m.", "短袜", "daily"),
    ("calcetines", "m.pl.", "袜子", "daily"),
    ("medias", "f.pl.", "长筒丝袜", "daily"),
    ("sombrero", "m.", "宽檐帽", "daily"),
    ("gorra", "f.", "遮阳鸭舌帽", "daily"),
    ("gorro", "m.", "保暖毛线帽", "daily"),
    ("bufanda", "f.", "御寒围巾", "daily"),
    ("pañuelo", "m.", "手帕，丝巾", "daily"),
    ("guantes", "m.pl.", "双手手套", "daily"),
    ("cinturón", "m.", "皮带腰带", "daily"),
    ("gafas", "f.pl.", "视力眼镜", "daily"),
    ("gafas de sol", "f.pl.", "防紫外线墨镜", "daily"),
    ("paraguas", "m.", "防雨雨伞", "daily"),
    ("bolso", "m.", "手提女包", "daily"),
    ("cartera", "f.", "折叠钱包", "daily"),
    ("monedero", "m.", "硬币零钱包", "daily"),
    ("reloj de pulsera", "m.", "腕表", "daily"),
    ("joya", "f.", "首饰珠宝", "daily"),
    ("anillo", "m.", "戒指", "daily"),
    ("collar", "m.", "项链", "daily"),
    ("pulsera", "f.", "手链手镯", "daily"),
    ("pendientes", "m.pl.", "耳坠耳环", "daily"),
    ("talla", "f.", "成衣尺码", "daily"),
    ("número", "m.", "鞋码编号", "daily"),
    ("algodón", "m.", "纯棉材质", "daily"),
    ("lana", "f.", "羊毛料子", "daily"),
    ("seda", "f.", "天然蚕丝", "daily"),
    ("cuero", "m.", "真皮皮革", "daily"),
    ("piel", "f.", "动物皮革；皮肤", "daily"),

    # --- Verbos fundamentales A1 ---
    ("ser", "v.", "是（固有特性，国籍，身份）", "grammar"),
    ("estar", "v.", "处于，在（方位，暂态）", "grammar"),
    ("tener", "v.", "拥有，具有；感觉有", "grammar"),
    ("haber", "v.", "有（无主客观存在/完成时助动）", "grammar"),
    ("hacer", "v.", "制作，实行；天气状况", "grammar"),
    ("ir", "v.", "前往，前去", "travel"),
    ("venir", "v.", "前来，赶来", "daily"),
    ("salir", "v.", "出门，离去；去玩", "travel"),
    ("entrar", "v.", "踏入，迈进", "daily"),
    ("llegar", "v.", "抵达目的地", "travel"),
    ("volver", "v.", "归返，回来", "travel"),
    ("regresar", "v.", "返回", "travel"),
    ("partir", "v.", "动身出发；切开", "travel"),
    ("ver", "v.", "看见，观赏", "daily"),
    ("mirar", "v.", "目视，注视", "daily"),
    ("oír", "v.", "听闻，听得见", "daily"),
    ("escuchar", "v.", "专心倾听", "daily"),
    ("hablar", "v.", "说话，谈吐", "daily"),
    ("decir", "v.", "讲述，道明", "daily"),
    ("contar", "v.", "数数；叙述故事", "daily"),
    ("preguntar", "v.", "提出疑问", "daily"),
    ("responder", "v.", "作出解答", "daily"),
    ("contestar", "v.", "回话", "daily"),
    ("comer", "v.", "进餐咀嚼", "food"),
    ("beber", "v.", "畅饮，饮用", "food"),
    ("tomar", "v.", "拿取；饮用；乘车", "food"),
    ("desayunar", "v.", "享用早餐", "food"),
    ("almorzar", "v.", "进食午餐", "food"),
    ("cenar", "v.", "用毕晚餐", "food"),
    ("cocinar", "v.", "下厨烹饪", "food"),
    ("vivir", "v.", "长居，存活", "daily"),
    ("trabajar", "v.", "劳作，任职", "business"),
    ("estudiar", "v.", "刻苦研读", "daily"),
    ("aprender", "v.", "掌握汲取新知", "daily"),
    ("comprender", "v.", "领会理解", "daily"),
    ("entender", "v.", "明白了解", "daily"),
    ("escribir", "v.", "书写执笔", "daily"),
    ("leer", "v.", "翻阅朗读", "daily"),
    ("comprar", "v.", "出资选购", "daily"),
    ("pagar", "v.", "结清付款", "daily"),
    ("vender", "v.", "出售货物", "business"),
    ("gastar", "v.", "破费，花钱", "daily"),
    ("costar", "v.", "标价花费", "daily"),
    ("cobrar", "v.", "收取款项；领薪水", "business"),
    ("querer", "v.", "渴求愿望；相爱", "emotion"),
    ("poder", "v.", "具备能够", "grammar"),
    ("saber", "v.", "获知了解；熟练技巧", "grammar"),
    ("conocer", "v.", "熟识结交；游历", "daily"),
    ("llamar", "v.", "呼唤声名；通电话", "daily"),
    ("llamarse", "v.", "名字尊称为", "daily"),
    ("gustar", "v.", "使某人倾心喜爱", "emotion"),
    ("encantar", "v.", "令极其陶醉着迷", "emotion"),
    ("preferir", "v.", "宁选偏好", "emotion"),
    ("dar", "v.", "赐予，交付", "daily"),
    ("poner", "v.", "安放安置", "daily"),
    ("quitar", "v.", "撤走移开", "daily"),
    ("llevar", "v.", "携走随身；穿戴服饰", "daily"),
    ("traer", "v.", "带至此处", "daily"),
    ("abrir", "v.", "启开门窗；开张", "daily"),
    ("cerrar", "v.", "关闭锁上", "daily"),
    ("empezar", "v.", "启动开始", "daily"),
    ("comenzar", "v.", "着手起步", "daily"),
    ("terminar", "v.", "宣告收尾", "daily"),
    ("acabar", "v.", "彻底告终", "daily"),
    ("necesitar", "v.", "迫切需要", "daily"),
    ("buscar", "v.", "探寻搜寻", "daily"),
    ("encontrar", "v.", "寻觅获得", "daily"),
    ("perder", "v.", "遗失错过", "daily"),
    ("esperar", "v.", "耐心等候；希冀", "daily"),
    ("usar", "v.", "使用采用", "daily"),
    ("utilizar", "v.", "加以利用", "daily"),
    ("jugar", "v.", "游玩娱乐；踢球", "daily"),
    ("cantar", "v.", "放声歌唱", "daily"),
    ("bailar", "v.", "翩翩起舞", "daily"),
    ("tocar", "v.", "弹奏乐器；触碰", "daily"),
    ("viajar", "v.", "游历旅行", "travel"),
    ("caminar", "v.", "迈步步行", "daily"),
    ("andar", "v.", "行走踱步", "daily"),
    ("correr", "v.", "奔跑奔走", "daily"),
    ("nadar", "v.", "戏水游泳", "daily"),
    ("montar", "v.", "骑马；骑车；安装", "daily"),
    ("descansar", "v.", "憩息安歇", "daily"),
    ("dormir", "v.", "进入梦乡", "daily"),
    ("pensar", "v.", "寻思琢磨；企图", "daily"),
    ("creer", "v.", "深信不疑", "daily"),
    ("sentir", "v.", "感知觉察；心疼", "emotion"),
    ("ayudar", "v.", "施以援手", "daily"),
    ("cambiar", "v.", "转换更替；兑换外币", "daily"),
    ("pasar", "v.", "穿行而过；消磨时光", "daily"),
    ("quedar", "v.", "逗留；相聚约定", "daily"),
    ("deber", "v./m.", "理应必当；欠付债务", "grammar"),
    ("parecer", "v.", "呈现显露外观", "daily"),
    ("doler", "v.", "使感肉体阵痛", "daily"),

    # --- Preposiciones y conectores A1 ---
    ("a", "prep.", "朝，向，在（钟点/指人直宾）", "grammar"),
    ("de", "prep.", "源于，关于；材料", "grammar"),
    ("en", "prep.", "居于其内，在上面", "grammar"),
    ("con", "prep.", "伴随协同，持有", "grammar"),
    ("sin", "prep.", "欠缺毫无，排除", "grammar"),
    ("por", "prep.", "因由；经由；为了", "grammar"),
    ("para", "prep.", "以期为了；受词给与", "grammar"),
    ("sobre", "prep.", "置于其表；论及", "grammar"),
    ("entre", "prep.", "夹峙于两者间", "grammar"),
    ("hacia", "prep.", "趋向方位", "grammar"),
    ("hasta", "prep.", "直至终点限度", "grammar"),
    ("desde", "prep.", "起始自某时某地", "grammar"),
    ("bajo", "prep.", "置于其下方", "grammar"),
    ("contra", "prep.", "迎面碰撞，逆着", "grammar"),
    ("según", "prep.", "遵照依据", "grammar"),
    ("aquí", "adv.", "此地附近", "grammar"),
    ("acá", "adv.", "这边（拉美）", "grammar"),
    ("ahí", "adv.", "那处近旁", "grammar"),
    ("allí", "adv.", "彼处远地", "grammar"),
    ("allá", "adv.", "茫茫远方", "grammar"),
    ("cerca", "adv.", "不远处", "grammar"),
    ("lejos", "adv.", "迢迢千里", "grammar"),
    ("dentro", "adv.", "内层室中", "grammar"),
    ("fuera", "adv.", "室外露天", "grammar"),
    ("arriba", "adv.", "上方高处", "grammar"),
    ("abajo", "adv.", "下首低地", "grammar"),
    ("delante", "adv.", "眼前正面", "grammar"),
    ("detrás", "adv.", "背影后方", "grammar"),
    ("encima", "adv.", "顶端其上", "grammar"),
    ("debajo", "adv.", "底端其下", "grammar"),
    ("enfrente", "adv.", "门面对首", "grammar"),
    ("al lado", "exp.", "肩并贴近", "grammar"),
    ("alrededor", "adv.", "周遭四周", "grammar"),
    ("bien", "adv./m.", "妥帖良好", "daily"),
    ("mal", "adv./m.", "欠佳糟粕", "daily"),
    ("sí", "adv.", "诺，肯定答复", "daily"),
    ("no", "adv.", "非，全盘否定", "daily"),
    ("también", "adv.", "亦然复同", "daily"),
    ("tampoco", "adv.", "亦复不然", "daily"),
    ("claro", "adv./interj.", "当然显而易见", "daily"),
    ("por supuesto", "exp.", "理当如此", "daily"),
    ("seguro", "adv.", "确凿无疑", "daily"),
    ("y", "conj.", "及，并列连词", "grammar"),
    ("e", "conj.", "和（遇i/hi前置音变）", "grammar"),
    ("o", "conj.", "或者，二择其一", "grammar"),
    ("u", "conj.", "抑或（遇o/ho前置）", "grammar"),
    ("pero", "conj.", "转折然而", "grammar"),
    ("sino", "conj.", "并非彼而是此", "grammar"),
    ("si", "conj.", "倘若假使", "grammar"),
    ("como", "conj./adv.", "犹如相仿；既然", "grammar"),
    ("que", "conj./pron.", "连接词以至于", "grammar")
]

print(f"Loaded A1 items: {len(A1_WORDS)}")
