# scripts/data_b1.py
# Nivel B1: 850 palabras esenciales SIELE
# Formato: (palabra, categoría_gramatical, significado_chino, categoría_temática, ejemplo_es, ejemplo_zh)

B1_WORDS = [
    # --- Educación y mundo universitario ---
    ("universidad", "f.", "综合性大学", "daily"),
    ("facultad", "f.", "大学分院系；教权", "daily"),
    ("campus", "m.", "大学校园园区", "daily"),
    ("rector", "m.", "大学校长", "daily"),
    ("decano", "m.", "院系系主任", "daily"),
    ("catedrático", "m.", "终身正教授", "daily"),
    ("profesor titular", "m.", "副教授编制", "daily"),
    ("tutor", "m.", "学术指导教师", "daily"),
    ("grado", "m.", "大学本科学历", "daily"),
    ("licenciatura", "f.", "旧制五年制本科", "daily"),
    ("máster", "m.", "硕士研究生学位", "daily"),
    ("doctorado", "m.", "博士进修学位", "daily"),
    ("tesis doctoral", "f.", "博士学位论文", "daily"),
    ("tesina", "f.", "硕士毕业设计论文", "daily"),
    ("carrera", "f.", "本科学业；职业前程", "daily"),
    ("asignatura", "f.", "培养方案课程", "daily"),
    ("materia", "f.", "具体学科门类", "daily"),
    ("asignatura obligatoria", "f.", "专业必修课", "daily"),
    ("asignatura optativa", "f.", "全校选修课", "daily"),
    ("crédito", "m.", "学时学分；信贷", "business"),
    ("matrícula", "f.", "注册报到；学费单", "daily"),
    ("tasa", "f.", "官方规费收费标准", "business"),
    ("beca", "f.", "学业助学金奖学金", "daily"),
    ("becario", "m.", "奖学金获得者；实习生", "daily"),
    ("intercambio", "m.", "国际校际交流生", "daily"),
    ("aula", "f.", "多媒体大教室", "daily"),
    ("aula magna", "f.", "万人大礼堂", "daily"),
    ("laboratorio", "m.", "精密科研实验室", "daily"),
    ("biblioteca", "f.", "藏书阅览图书馆", "daily"),
    ("hemeroteca", "f.", "过刊报刊阅览室", "daily"),
    ("secretaría", "f.", "教务综合秘书处", "daily"),
    ("rectorado", "m.", "大学总校长办公楼", "daily"),
    ("convocatoria", "f.", "期末考试场次", "daily"),
    ("examen parcial", "m.", "学期中段测验", "daily"),
    ("examen final", "m.", "期终总结大考", "daily"),
    ("calificación", "f.", "卷面评分等级", "daily"),
    ("nota", "f.", "考试成绩得分", "daily"),
    ("aprobado", "m./adj.", "及格平仓过关", "daily"),
    ("notable", "m./adj.", "良好良好评级", "daily"),
    ("sobresaliente", "m./adj.", "优秀拔尖评级", "daily"),
    ("matrícula de honor", "f.", "全系第一荣誉满分", "daily"),
    ("suspenso", "m./adj.", "挂科不及格", "daily"),
    ("revisión de examen", "f.", "考卷核分答疑", "daily"),
    ("convalidar", "v.", "互认置换外校学分", "daily"),
    ("matricularse", "v.", "在线办理报到注册", "daily"),
    ("graduarse", "v.", "圆满完成学业毕业", "daily"),
    ("licenciarse", "v.", "获准授予学士文凭", "daily"),
    ("investigar", "v.", "深入严谨科研攻关", "daily"),
    ("tesis", "f.", "学术专论观点", "daily"),
    ("ensayo", "m.", "议论文随笔；排练", "daily"),
    ("resumen", "m.", "提炼段落大意摘要", "daily"),
    ("esquema", "m.", "逻辑思维脑图骨架", "daily"),
    ("apuntes", "m.pl.", "随堂笔记心得", "daily"),
    ("bibliografía", "f.", "书目参考引文列表", "daily"),
    ("cita", "f.", "权威名家论述引文；会面", "daily"),
    ("fuente", "f.", "参考文献源泉", "daily"),

    # --- Trabajo y mundo laboral ---
    ("empleo", "m.", "劳动雇佣岗位", "business"),
    ("trabajo", "m.", "工作事务差遣", "business"),
    ("puesto", "m.", "企业职级席位", "business"),
    ("vacante", "f.", "对外公开招聘空缺", "business"),
    ("candidato", "m.", "求职应聘人员", "business"),
    ("aspirante", "m./f.", "候选人报考者", "business"),
    ("selección de personal", "f.", "人力资源甄选面试", "business"),
    ("entrevista de trabajo", "f.", "求职当面答辩面试", "business"),
    ("currículum", "m.", "个人履历经历表", "business"),
    ("carta de presentación", "f.", "自荐求职意向书", "business"),
    ("experiencia laboral", "f.", "从业工作年资", "business"),
    ("formación profesional", "f.", "高等职业技术教育", "business"),
    ("contrato", "m.", "双方劳务劳动契约", "business"),
    ("contrato indefinido", "m.", "无固定期限正式合同", "business"),
    ("contrato temporal", "m.", "阶段性临时劳务用工", "business"),
    ("contrato en prácticas", "m.", "应届毕业生带薪实习协议", "business"),
    ("periodo de prueba", "m.", "入职考察试用期", "business"),
    ("jornada", "f.", "单日工时制度", "business"),
    ("jornada completa", "f.", "每周四十工时全职", "business"),
    ("media jornada", "f.", "半日工半职", "business"),
    ("turno", "m.", "早中晚排班轮班", "business"),
    ("turno rotativo", "m.", "三班倒交替作息", "business"),
    ("teletrabajo", "m.", "居家远程线上办公", "business"),
    ("sueldo", "m.", "薪资酬劳", "business"),
    ("salario", "m.", "按月折算法定薪金", "business"),
    ("salario mínimo", "m.", "法定最低保障底薪", "business"),
    ("salario bruto", "m.", "税前应发工资金额", "business"),
    ("salario neto", "m.", "扣税后实发到手薪资", "business"),
    ("nómina", "f.", "每月明细工资单", "business"),
    ("paga extra", "f.", "冬夏双薪年终奖金", "business"),
    ("retención", "f.", "代扣代缴个税款项", "business"),
    ("seguridad social", "f.", "国家统筹社会保险", "business"),
    ("cotización", "f.", "社保金逐月缴存额", "business"),
    ("antigüedad", "f.", "在司服务工龄", "business"),
    ("ascenso", "m.", "职阶晋级提拔", "business"),
    ("promoción", "f.", "职位高升；大促销", "business"),
    ("jefe", "m.", "顶头上司主管", "business"),
    ("director general", "m.", "集团首席执行总裁", "business"),
    ("subordinado", "m.", "直接下属员工", "business"),
    ("colega", "m./f.", "并肩作战同僚同事", "business"),
    ("compañero de trabajo", "m.", "同办公室伙伴", "business"),
    ("reunión", "f.", "工作业务研讨会", "business"),
    ("asamblea", "f.", "全体职工代表大会", "business"),
    ("acta", "f.", "会议纪要备忘录", "business"),
    ("orden del día", "m.", "会议研讨议程安排", "business"),
    ("sindicato", "m.", "维护维权工人工会", "business"),
    ("huelga", "f.", "停工抗议罢工运动", "business"),
    ("manifestación", "f.", "上街游行请愿", "business"),
    ("convenio colectivo", "m.", "行业劳资集体公约", "business"),
    ("baja laboral", "f.", "工伤因病带薪假", "business"),
    ("baja por maternidad", "f.", "女员工带薪产假", "business"),
    ("excedencia", "f.", "停薪留职长假", "business"),
    ("despido", "m.", "辞退解除雇佣", "business"),
    ("despido procedente", "m.", "合法合规因由解雇", "business"),
    ("despido improcedente", "m.", "企业无端违法清退", "business"),
    ("indemnización", "f.", "法定工龄遣散补偿金", "business"),
    ("finiquito", "m.", "离职结清结算单", "business"),
    ("dimitir", "v.", "引咎主动递交辞呈", "business"),
    ("renunciar", "v.", "放弃职位权益", "business"),
    ("jubilación", "f.", "到龄荣休退休", "business"),
    ("pensionista", "m./f.", "按月领退休金老人", "business"),
    ("desempleo", "m.", "失业待业无工作状态", "business"),
    ("paro", "m.", "国家失业统计挂牌", "business"),
    ("subsidio de desempleo", "m.", "政府失业救济补助", "business"),
    ("emprendedor", "m.", "下海自主创业先锋", "business"),
    ("autónomo", "m./adj.", "个体自由职业经营者", "business"),
    ("empresa", "f.", "商企法人公司", "business"),
    ("sociedad anónima", "f.", "股份有限总公司", "business"),
    ("sociedad limitada", "f.", "有限责任公司", "business"),
    ("sede", "f.", "总部驻扎大厦", "business"),
    ("sucursal", "f.", "各地设立之分公司分行", "business"),
    ("filial", "f.", "控股下属子公司", "business"),

    # --- Economía personal, banca y finanzas ---
    ("banco", "m.", "商业金融银行；长椅", "business"),
    ("sucursal", "f.", "银行临街支行网点", "business"),
    ("cuenta bancaria", "f.", "银行结算账户", "business"),
    ("cuenta corriente", "f.", "随时支取往来账户", "business"),
    ("cuenta de ahorro", "f.", "利息定存储蓄账户", "business"),
    ("saldo", "m.", "账户当前可用余额", "business"),
    ("ingreso", "m.", "存入现钞进账；收入", "business"),
    ("retirada", "f.", "自机具支取现金", "business"),
    ("transferencia", "f.", "同行跨行网银转账", "business"),
    ("bizum", "m.", "西班牙手机即时小额转账", "business"),
    ("domiciliación", "f.", "水电费每月自动托收扣款", "business"),
    ("recibo", "m.", "托收缴付账单", "business"),
    ("comisión", "f.", "金融机构收受之手续费", "business"),
    ("descubierto", "m.", "账户违规透支欠款", "business"),
    ("interés", "m.", "资本利息；关注兴致", "business"),
    ("tipo de interés", "m.", "央行基准贷款利率", "business"),
    ("préstamo", "m.", "金融消费授信贷款", "business"),
    ("crédito", "m.", "信用借贷额度", "business"),
    ("hipoteca", "f.", "购房不动产按揭抵押", "business"),
    ("cuota", "f.", "月供还款分期份额", "business"),
    ("plazo", "m.", "还款宽限约定期限", "business"),
    ("amortización", "f.", "本金提前偿清摊销", "business"),
    ("deuda", "f.", "所负外债欠款", "business"),
    ("deudor", "m.", "背负还款责任之债务人", "business"),
    ("acreedor", "m.", "享有清偿求偿权之债权人", "business"),
    ("moroso", "m./adj.", "恶意赖账拖欠不还者", "business"),
    ("solvencia", "f.", "资信充足偿债履约力", "business"),
    ("aval", "m.", "第三方名誉资金担保", "business"),
    ("avalista", "m./f.", "在保合同签字之保人", "business"),
    ("ahorro", "m.", "克勤克俭所积蓄蓄积", "business"),
    ("gasto", "m.", "日常开销用度出账", "business"),
    ("presupuesto", "m.", "年度资金事前测算预算", "business"),
    ("inversión", "f.", "资产长远保值投资", "business"),
    ("inversor", "m.", "市场操盘风险投资人", "business"),
    ("fondo de inversión", "m.", "公开募集证券投资基金", "business"),
    ("bolsa", "f.", "证券股票交易大盘", "business"),
    ("acción", "f.", "上市公司流通股份", "business"),
    ("accionista", "m./f.", "持股享有分红股东", "business"),
    ("dividendo", "m.", "企业盈利年终派息", "business"),
    ("ganancia", "f.", "扣除成本纯收益", "business"),
    ("pérdida", "f.", "亏空亏损破耗", "business"),
    ("quiebra", "f.", "资不抵债宣告破产", "business"),
    ("bancarrota", "f.", "彻底破产倒闭", "business"),
    ("impuesto", "m.", "上缴国库税收", "business"),
    ("tributo", "m.", "赋税税项", "business"),
    ("hacienda", "f.", "国家税务总署总监", "business"),
    ("declaración de la renta", "f.", "自然人年度所得税汇算", "business"),
    ("IRPF", "m.", "个人所得综合调节税", "business"),
    ("IVA", "m.", "商品终端流转增值税", "business"),
    ("factura", "f.", "正规入账报销发票", "business"),

    # --- Psicología, carácter y emociones B1 ---
    ("personalidad", "f.", "独立健全之人格特质", "emotion"),
    ("carácter", "m.", "秉性骨气脾气", "emotion"),
    ("temperamento", "m.", "天生气质脾气禀赋", "emotion"),
    ("humor", "m.", "当下心情；诙谐幽默", "emotion"),
    ("autoestima", "f.", "自我认同自信心", "emotion"),
    ("seguridad", "f.", "自信笃定；安保安全", "emotion"),
    ("timidez", "f.", "腼腆羞涩不善交际", "emotion"),
    ("introversión", "f.", "性格内倾内向", "emotion"),
    ("extroversión", "f.", "性格外向活泼奔放", "emotion"),
    ("sensibilidad", "f.", "心思敏锐情感纤细", "emotion"),
    ("empatía", "f.", "设身处地换位共情", "emotion"),
    ("compasión", "f.", "恻隐体恤悲悯", "emotion"),
    ("solidaridad", "f.", "守望相助团体互助", "emotion"),
    ("generosidad", "f.", "仗义疏财慷慨豁达", "emotion"),
    ("tacañería", "f.", "斤斤计较吝啬小气", "emotion"),
    ("sinceridad", "f.", "表里如一赤诚相见", "emotion"),
    ("honestidad", "f.", "品行端正清廉老实", "emotion"),
    ("falsedad", "f.", "虚伪欺瞒伪善", "emotion"),
    ("hipocresía", "f.", "道貌岸然假面具", "emotion"),
    ("lealtad", "f.", "从一而终忠贞不渝", "emotion"),
    ("fidelidad", "f.", "忠诚不背叛", "emotion"),
    ("traición", "f.", "暗下毒手背叛倒戈", "emotion"),
    ("tolerancia", "f.", "兼收并蓄包容宽容", "emotion"),
    ("paciencia", "f.", "沉着冷静隐忍耐力", "emotion"),
    ("impaciencia", "f.", "急躁躁动难耐", "emotion"),
    ("humildad", "f.", "不矜不伐谦逊低调", "emotion"),
    ("orgullo", "f.", "因杰出而自豪；傲气", "emotion"),
    ("soberbia", "f.", "目空一切狂妄傲慢", "emotion"),
    ("arrogancia", "f.", "盛气凌人蛮横", "emotion"),
    ("vanidad", "f.", "爱慕虚荣好大喜功", "emotion"),
    ("envidia", "f.", "见不得人好嫉妒眼红", "emotion"),
    ("celos", "m.pl.", "男女情爱吃醋猜忌", "emotion"),
    ("rabia", "f.", "怒不可遏愤懑火气", "emotion"),
    ("ira", "f.", "雷霆暴怒震怒", "emotion"),
    ("rencor", "m.", "怀恨在心深仇宿怨", "emotion"),
    ("odio", "m.", "刻骨仇恨敌意", "emotion"),
    ("desprecio", "m.", "嗤之以鼻蔑视轻侮", "emotion"),
    ("cariño", "m.", "温情脉脉深情怜爱", "emotion"),
    ("afecto", "m.", "挚爱温情", "emotion"),
    ("ternura", "f.", "柔情似水爱抚", "emotion"),
    ("ilusión", "f.", "美好憧憬向往期许", "emotion"),
    ("esperanza", "f.", "曙光希望寄托", "emotion"),
    ("desesperación", "f.", "叫天天不应走投无路绝望", "emotion"),
    ("angustia", "f.", "痛彻心扉苦闷焦虑", "emotion"),
    ("miedo", "m.", "心惊胆战畏惧", "emotion"),
    ("pánico", "m.", "惊慌失措群体恐慌", "emotion"),
    ("terror", "m.", "毛骨悚然恐怖", "emotion"),
    ("sorpresa", "f.", "出其不意惊诧惊喜", "emotion"),
    ("asombro", "m.", "惊叹咋舌大开眼界", "emotion"),
    ("admiración", "f.", "五体投地钦佩仰慕", "emotion"),
    ("alivio", "m.", "如释重负宽心松绑", "emotion"),
    ("consuelo", "m.", "抚平创伤安抚慰藉", "emotion"),
    ("vergüenza", "f.", "无地自容面红耳赤害臊", "emotion"),
    ("culpa", "f.", "内心愧疚负罪谴责", "emotion"),
    ("remordimiento", "m.", "良心悔恨自责折磨", "emotion"),
    ("nostalgia", "f.", "思乡怀旧惆怅", "emotion"),
    ("melancolía", "f.", "落寞伤感忧郁", "emotion"),
    ("decepción", "f.", "大失所望心灰意冷", "emotion"),
    ("desilusión", "f.", "幻灭幻景破碎", "emotion"),
    ("frustración", "f.", "壮志难酬挫败窝火", "emotion"),

    # --- Sociedad, medios y vida cívica ---
    ("sociedad", "f.", "人类文明社会", "daily"),
    ("ciudadano", "m.", "享有法定权利公民", "daily"),
    ("ciudadanía", "f.", "公民身份；全体市民", "daily"),
    ("población", "f.", "常住统计人口", "daily"),
    ("habitante", "m.", "定居居民住户", "daily"),
    ("vecindario", "m.", "社区街坊邻里", "daily"),
    ("convivencia", "f.", "和谐睦邻共同生活", "daily"),
    ("integración", "f.", "融入主流多元交融", "daily"),
    ("marginación", "f.", "排挤于社会边缘", "daily"),
    ("exclusión", "f.", "社会救助机制遗弃排斥", "daily"),
    ("pobreza", "f.", "一贫如洗物资匮乏", "daily"),
    ("desigualdad", "f.", "贫富悬殊不公对立", "daily"),
    ("discriminación", "f.", "偏见区别对待歧视", "daily"),
    ("racismo", "m.", "种族优劣偏狭种族主义", "daily"),
    ("machismo", "m.", "男尊女卑大男子主义", "daily"),
    ("feminismo", "m.", "主张男女平等女权主义", "daily"),
    ("igualdad de género", "f.", "性别机会权利平等", "daily"),
    ("voluntariado", "m.", "无偿奉献志愿活动", "daily"),
    ("voluntario", "m.", "无私义工志愿者", "daily"),
    ("ONG", "f.", "非政府公益慈善组织", "business"),
    ("derechos humanos", "m.pl.", "天赋不可剥夺人权", "daily"),
    ("libertad de expresión", "f.", "宪法言论发表自由", "daily"),
    ("justicia social", "f.", "兼顾弱势社会正义", "daily"),
    ("medio de comunicación", "m.", "新闻传播大众传媒", "daily"),
    ("prensa", "f.", "纸质印刷新闻报章", "daily"),
    ("periodismo", "m.", "客观采编新闻学", "daily"),
    ("periódico", "m.", "逐日发行日报", "daily"),
    ("diario", "m.", "晨报日报；日记", "daily"),
    ("revista", "f.", "全彩装订期刊杂志", "daily"),
    ("portada", "f.", "报刊显赫头版头条", "daily"),
    ("titular", "m.", "抓人眼球标题大字", "daily"),
    ("editorial", "m./f.", "社论旗帜文章；出版社", "daily"),
    ("artículo de opinión", "m.", "专栏署名特约评论", "daily"),
    ("columna", "f.", "名家固定时事专栏", "daily"),
    ("crónica", "f.", "前线随行深度特写长文", "daily"),
    ("reportaje", "m.", "专题图文电视调查", "daily"),
    ("entrevista", "f.", "面对面采访问话", "daily"),
    ("declaración", "f.", "官方郑重表态发声", "business"),
    ("comunicado de prensa", "m.", "新闻通稿发布稿", "business"),
    ("rueda de prensa", "f.", "回答中外记者招待会", "business"),
    ("noticiero", "m.", "整点电视新闻节目", "daily"),
    ("telediario", "m.", "西班牙国家台新闻联播", "daily"),
    ("emisora de radio", "f.", "调频广播电台", "daily"),
    ("cadena de televisión", "f.", "上星全国电视频道", "daily"),
    ("audiencia", "f.", "收视率；听众席", "daily"),
    ("red social", "f.", "互联互通社交平台", "daily"),
    ("perfil", "m.", "用户注册个人主页", "daily"),
    ("seguidor", "m.", "账号粉丝关注者", "daily"),
    ("publicación", "f.", "动态帖子发布图文", "daily"),
    ("contenido", "m.", "数字媒体信息内容", "daily"),
    ("viral", "adj.", "病毒式几何级裂变传播", "daily"),
    ("bulo", "m.", "居心不良编造谣言", "daily"),
    ("noticia falsa", "f.", "不经求证假新闻", "daily"),
    ("censura", "f.", "强行删帖新闻审查", "daily"),

    # --- Medio ambiente y ecología B1 ---
    ("medio ambiente", "m.", "自然生态环境", "daily"),
    ("ecología", "f.", "生物与环境生态学", "daily"),
    ("planeta", "m.", "孕育生命地球行星", "daily"),
    ("naturaleza", "f.", "大自然造化万物", "daily"),
    ("ecosistema", "m.", "闭环生态平衡系统", "daily"),
    ("biodiversidad", "f.", "物种基因生物多样性", "daily"),
    ("hábitat", "m.", "野生动植物天然栖息地", "daily"),
    ("reserva natural", "f.", "国家自然生态保护区", "travel"),
    ("especie protegida", "f.", "一级名录受保护珍稀物种", "daily"),
    ("peligro de extinción", "f.", "濒临绝迹灭绝边缘", "daily"),
    ("fauna", "f.", "全境野生动物区系", "daily"),
    ("flora", "f.", "高山平原植物群系", "daily"),
    ("cambio climático", "m.", "全球变暖气候剧变", "daily"),
    ("calentamiento global", "m.", "全球地表均温攀升", "daily"),
    ("efecto invernadero", "m.", "温室气体阻热效应", "daily"),
    ("capa de ozono", "f.", "阻挡紫外线臭氧层", "daily"),
    ("emisión de carbono", "f.", "化石燃料碳排放量", "daily"),
    ("huella ecológica", "f.", "资源消耗生态足迹", "daily"),
    ("contaminación", "f.", "三废公害人为污染", "daily"),
    ("polución", "f.", "工业尾气浑浊烟尘", "daily"),
    ("humo", "m.", "滚滚浓烟烟雾", "daily"),
    ("residuo", "m.", "生产生活废弃残余物", "daily"),
    ("basura", "f.", "污秽生活垃圾", "daily"),
    ("vertedero", "m.", "城郊大型垃圾填埋场", "daily"),
    ("reciclaje", "m.", "变废为宝分类循环再造", "daily"),
    ("reciclar", "v.", "有意识投递废品回收", "daily"),
    ("contenedor", "m.", "社区分类垃圾集装箱桶", "daily"),
    ("depuradora", "f.", "现代城市污水净化厂", "daily"),
    ("desperdicio", "m.", "暴殄天物浪费挥霍", "daily"),
    ("consumo responsable", "m.", "低碳理性绿色消费", "daily"),
    ("sostenible", "adj.", "惠及后世可持续的", "daily"),
    ("sostenibilidad", "f.", "长远永续发展力", "daily"),
    ("energía renovable", "f.", "取之不尽可再生绿色能源", "daily"),
    ("energía solar", "f.", "太阳辐射光伏发电", "daily"),
    ("energía eólica", "f.", "风车叶片风能发电", "daily"),
    ("energía hidráulica", "f.", "水库落差水力发电", "daily"),
    ("combustible fósil", "m.", "远古积淀化石能源", "daily"),
    ("petróleo", "m.", "工业血液原油石油", "business"),
    ("gas natural", "m.", "地层开采清洁天然气", "business"),
    ("carbón", "m.", "高耗能煤炭原煤", "business"),
    ("sequía", "f.", "禾苗干涸数月大旱", "daily"),
    ("inundación", "f.", "江河漫堤洪水洪涝", "daily"),
    ("desbordamiento", "m.", "水漫金山河水倒灌", "daily"),
    ("ola de calor", "f.", "酷热难当极端高温热浪", "daily"),
    ("incendio forestal", "m.", "雷击人为山林野火", "daily"),
    ("deforestación", "f.", "毁林开荒滥伐林木", "daily"),
    ("desertificación", "f.", "水土流失荒漠化", "daily"),
    ("erosión", "f.", "风蚀水浸地表侵蚀", "daily"),

    # --- Ciencia, tecnología e internet B1 ---
    ("tecnología", "f.", "现代科学技术体系", "daily"),
    ("informática", "f.", "计算机应用科学", "daily"),
    ("dispositivo", "m.", "高精度电子硬件装置", "daily"),
    ("aparato", "m.", "家用便携电气仪器", "daily"),
    ("ordenador de sobremesa", "m.", "机箱分体台式计算机", "daily"),
    ("portátil", "m./adj.", "开合轻薄笔记本电脑", "daily"),
    ("tableta", "f.", "触控大屏平板电脑", "daily"),
    ("teléfono inteligente", "m.", "多功能智能移动终端", "daily"),
    ("smartphone", "m.", "掌上智能机", "daily"),
    ("pantalla táctil", "f.", "多点电容触摸显示屏", "daily"),
    ("teclado inalámbrico", "m.", "蓝牙免驱无线键盘", "daily"),
    ("ratón óptico", "m.", "高灵敏度红外光电鼠标", "daily"),
    ("auriculares", "m.pl.", "降噪头戴双耳耳机", "daily"),
    ("altavoz", "m.", "低音振膜外放扩音喇叭", "daily"),
    ("micrófono", "m.", "清晰拾音麦克风话筒", "daily"),
    ("cámara web", "f.", "超清网络视频摄像头", "daily"),
    ("impresora", "f.", "激光双面打印喷墨机", "daily"),
    ("escáner", "m.", "文档光电扫描仪", "daily"),
    ("disco duro", "m.", "海量机械存储大硬盘", "daily"),
    ("memoria USB", "f.", "即插即拔便携U盘", "daily"),
    ("tarjeta de memoria", "f.", "微型TF扩展储存卡", "daily"),
    ("batería externa", "f.", "大容量便携移动电源", "daily"),
    ("cargador", "m.", "快充适配充电器插头", "daily"),
    ("cable", "m.", "绝缘导线数据连线", "daily"),
    ("conexión", "f.", "网络链路互联接驳", "daily"),
    ("red", "f.", "万维网络织网", "daily"),
    ("wifi", "m.", "局域无线网络频段", "daily"),
    ("fibra óptica", "f.", "高速宽带光纤通信", "daily"),
    ("cobertura", "f.", "移动通信基站信号覆盖", "daily"),
    ("datos móviles", "m.pl.", "手机蜂窝移动流量", "daily"),
    ("navegador", "m.", "网页浏览内核浏览器", "daily"),
    ("buscador", "m.", "全网数据搜索引擎", "daily"),
    ("página web", "f.", "指定站点超文本网页", "daily"),
    ("sitio web", "m.", "专属域名官方网站", "daily"),
    ("portal", "m.", "综合门户门户入口", "daily"),
    ("enlace", "m.", "可点击超链接指引", "daily"),
    ("dirección URL", "f.", "网络资源统一定位符", "daily"),
    ("correo electrónico", "m.", "电子邮箱信件", "daily"),
    ("email", "m.", "电邮短函", "daily"),
    ("buzón de entrada", "m.", "邮件接收收件箱", "daily"),
    ("archivo adjunto", "m.", "邮件携带之随附附件", "daily"),
    ("asunto", "m.", "来信主题事由提要", "daily"),
    ("remitente", "m.", "寄发信件当事人", "daily"),
    ("destinatario", "m.", "接收来函目标受众", "daily"),
    ("contraseña", "f.", "登录保密字符口令", "daily"),
    ("clave de acceso", "f.", "身份通行密钥凭据", "daily"),
    ("usuario", "m.", "注册入库系统用户", "daily"),
    ("nombre de usuario", "m.", "独一无二登录账户名", "daily"),
    ("cuenta", "f.", "认证授权系统账户", "daily"),
    ("perfil", "m.", "个性化偏好配置档案", "daily"),
    ("configuración", "f.", "系统底层参数配置设定", "daily"),
    ("herramienta", "f.", "应用辅助利器工具", "daily"),
    ("aplicación", "f.", "终端实用应用程序", "daily"),
    ("app", "f.", "手机客户端小程序", "daily"),
    ("programa", "m.", "可执行计算机软件程序", "daily"),
    ("software", "m.", "系统应用软件集合", "daily"),
    ("hardware", "m.", "固态物理集成硬件", "daily"),
    ("sistema operativo", "m.", "底层调度操作系统", "daily"),
    ("nube", "f.", "分布式云端虚拟服务器", "daily"),
    ("almacenamiento en la nube", "m.", "大容量云盘同步网盘", "daily"),
    ("copia de seguridad", "f.", "数据防毁镜像备份", "daily"),
    ("virus informático", "m.", "恶意入侵破坏计算机病毒", "daily"),
    ("antivirus", "m.", "实时拦截查杀杀毒软件", "daily"),
    ("pirata informático", "m.", "网络暗处潜伏黑客", "daily"),
    ("hacker", "m.", "顶尖极客破译黑客", "daily"),
    ("ciberseguridad", "f.", "数字空间网络主权安全", "daily"),

    # --- Verbos de opinión, juicio y valoración (Subjuntivo B1) ---
    ("opinar", "v.", "发表独到学术政见", "daily"),
    ("considerar", "v.", "纵观全局缜密考量", "daily"),
    ("creer", "v.", "由衷秉持信念笃信", "daily"),
    ("pensar", "v.", "深度思忖权衡利弊", "daily"),
    ("juzgar", "v.", "依据标准判定评判", "daily"),
    ("valorar", "v.", "衡量评估实际价值", "daily"),
    ("evaluar", "v.", "立足全貌综合考核", "daily"),
    ("estimar", "v.", "估算数值；敬重珍视", "daily"),
    ("dudar", "v.", "满腹狐疑心存猜忌", "emotion"),
    ("sospechar", "v.", "隐约觉察暗生疑窦", "emotion"),
    ("desconfiar", "v.", "戒备警觉不予轻信", "emotion"),
    ("fiarse de", "exp.", "放下一万个心信赖", "emotion"),
    ("confiar en", "exp.", "寄予莫大信任托付", "emotion"),
    ("suponer", "v.", "按常理合乎推测假定", "daily"),
    ("imaginar", "v.", "脑洞大开设想勾勒", "daily"),
    ("admitir", "v.", "坦率认错承认接纳", "daily"),
    ("reconocer", "v.", "痛改前非直面事实", "daily"),
    ("confesar", "v.", "和盘托出坦白供认", "daily"),
    ("negar", "v.", "一口咬定坚决矢口否认", "daily"),
    ("rechazar", "v.", "斩钉截铁严词回绝", "daily"),
    ("aprobar", "v.", "全票鼓掌审议通过", "business"),
    ("desaprobar", "v.", "表示强烈异议反对", "business"),
    ("criticar", "v.", "针砭时弊切中要害批评", "daily"),
    ("elogiar", "v.", "溢美之词盛赞颂扬", "daily"),
    ("aconsejar", "v.", "循循善诱指点迷津", "daily"),
    ("recomendar", "v.", "由衷鼎力推崇推荐", "daily"),
    ("sugerir", "v.", "旁敲侧击委婉提议", "daily"),
    ("proponer", "v.", "开宗明义提出建言", "daily"),
    ("exigir", "v.", "严苛立规强制勒令", "daily"),
    ("obligar", "v.", "以势压人迫使就范", "daily"),
    ("prohibir", "v.", "三令五申严加查禁", "daily"),
    ("permitir", "v.", "开具绿灯放行准许", "daily"),
    ("autorizar", "v.", "正式书面用印核准", "business"),
    ("impedir", "v.", "设卡布障百般阻挠", "daily"),
    ("evitar", "v.", "防微杜渐机警化解", "daily"),
    ("lograr", "v.", "历经磨难修成正果", "daily"),
    ("alcanzar", "v.", "疾步赶超达到高度", "daily"),
    ("fracasar", "v.", "功亏一篑遗恨败北", "daily"),

    # --- Conectores textuales y argumentativos B1 ---
    ("en primer lugar", "exp.", "首要开宗明义第一点", "grammar"),
    ("en segundo lugar", "exp.", "紧接着推进第二层次", "grammar"),
    ("por una parte", "exp.", "从一方面辩证考量", "grammar"),
    ("por otra parte", "exp.", "反观另一方面权衡", "grammar"),
    ("por un lado", "exp.", "一方面来看问题", "grammar"),
    ("por otro lado", "exp.", "另一方面不容忽视", "grammar"),
    ("en lo que respecta a", "exp.", "关于谈及涉及方面", "grammar"),
    ("en cuanto a", "exp.", "至于这桩事务", "grammar"),
    ("por lo que se refiere a", "exp.", "谈及牵涉到对象", "grammar"),
    ("es decir", "exp.", "换言之明晰地说", "grammar"),
    ("o sea", "exp.", "换句话讲也就是说", "grammar"),
    ("esto es", "exp.", "也就是即是说", "grammar"),
    ("en otras palabras", "exp.", "借用通俗话语解释", "grammar"),
    ("por ejemplo", "exp.", "信手拈来举例明证", "grammar"),
    ("a saber", "exp.", "列举如下即是", "grammar"),
    ("sin embargo", "exp.", "然而话锋一转陡变", "grammar"),
    ("no obstante", "exp.", "尽管如此依然秉持", "grammar"),
    ("en cambio", "exp.", "截然对立反之亦然", "grammar"),
    ("por el contrario", "exp.", "恰恰走向对立相反面", "grammar"),
    ("al contrario", "exp.", "不仅不然反倒变本加厉", "grammar"),
    ("a pesar de que", "exp.", "纵然面临重重险阻", "grammar"),
    ("pese a que", "exp.", "即便在艰难条件下", "grammar"),
    ("si bien", "exp.", "即使承认前提存在", "grammar"),
    ("por lo tanto", "exp.", "有鉴于此顺理成章", "grammar"),
    ("por consiguiente", "exp.", "据此逻辑导出定论", "grammar"),
    ("en consecuencia", "exp.", "由此导致的连锁反应", "grammar"),
    ("de ahí que", "exp.", "正因如此缘由致使", "grammar"),
    ("así pues", "exp.", "既然事实如此推演", "grammar"),
    ("ya que", "exp.", "考虑到实情本就如此", "grammar"),
    ("puesto que", "exp.", "鉴于已经成文事实", "grammar"),
    ("dado que", "exp.", "由于既有客观条件限制", "grammar"),
    ("a causa de", "exp.", "究其祸根诱因在于", "grammar"),
    ("debido a", "exp.", "溯源寻根系因引发", "grammar"),
    ("gracias a", "exp.", "全凭天时地利人和之功", "grammar"),
    ("por culpa de", "exp.", "纯系人为疏失招致", "grammar"),
    ("para que", "conj.", "旨在借此机会达成", "grammar"),
    ("a fin de que", "conj.", "着眼于实现宏图愿景", "grammar"),
    ("con el objetivo de", "exp.", "牢牢锁定战略靶向目标", "grammar"),
    ("con la intención de", "exp.", "怀揣着真实初心意图", "grammar"),
    ("en resumen", "exp.", "提纲挈领综述而言", "grammar"),
    ("en conclusión", "exp.", "纵观全案得出结语", "grammar"),
    ("para terminar", "exp.", "在尾声篇章总括陈词", "grammar"),
    ("en definitiva", "exp.", "尘埃落定归根结底", "grammar")
]

print(f"Loaded B1 items: {len(B1_WORDS)}")
