// Generator for SIELE 2800 Spanish Vocabulary Database
// Generates src/data/siele2800Data.ts with authentic CEFR A1, A2, B1, B2 words
const fs = require('fs');
const path = require('path');

// Helper to define entries cleanly
// [word, pos, meaning, level, category, exampleEs, exampleZh]
const wordSet = new Set();
const allEntries = [];

function add(word, pos, meaning, level, category, exampleEs = "", exampleZh = "") {
  const cleanWord = word.trim();
  const lower = cleanWord.toLowerCase();
  if (wordSet.has(lower)) {
    return; // deduplicate
  }
  wordSet.add(lower);
  allEntries.push([cleanWord, pos, meaning, level, category, exampleEs, exampleZh]);
}

// ----------------------------------------------------
// 1. NIVEL A1 (Target ~550 words)
// ----------------------------------------------------
const A1_VOCAB = [
  // Greetings & Courtesy
  ["hola", "interj.", "你好", "A1", "daily", "¡Hola! ¿Cómo estás?", "你好！你最近怎么样？"],
  ["adiós", "interj.", "再见", "A1", "daily", "Adiós, ¡hasta mañana!", "再见，明天见！"],
  ["gracias", "interj.", "谢谢", "A1", "daily", "Muchas gracias por tu ayuda.", "非常感谢你的帮助。"],
  ["de nada", "exp.", "不用谢，不客气", "A1", "daily", "—Gracias. —De nada.", "—谢谢。—不用谢。"],
  ["por favor", "exp.", "请，劳驾", "A1", "daily", "¿Un café, por favor?", "请给我一杯咖啡好吗？"],
  ["perdón", "m./interj.", "对不起，劳驾", "A1", "daily", "Perdón, ¿dónde está el metro?", "打扰一下，请问地铁在哪里？"],
  ["disculpe", "v./exp.", "劳驾，抱歉（尊称）", "A1", "daily", "Disculpe señor, ¿qué hora es?", "劳驾先生，请问几点了？"],
  ["lo siento", "exp.", "对不起，很抱歉", "A1", "daily", "Lo siento mucho, no puedo ir.", "非常抱歉，我不能去。"],
  ["bienvenido", "adj./interj.", "欢迎", "A1", "daily", "¡Bienvenidos a España!", "欢迎来到西班牙！"],
  ["buenos días", "exp.", "早上好，上午好", "A1", "daily", "Buenos días a todos.", "大家早上好。"],
  ["buenas tardes", "exp.", "下午好", "A1", "daily", "Buenas tardes, ¿en qué puedo ayudarle?", "下午好，有什么能帮您的？"],
  ["buenas noches", "exp.", "晚上好，晚安", "A1", "daily", "Buenas noches y que descanses.", "晚安，好好休息。"],
  ["hasta luego", "exp.", "回头见，待会儿见", "A1", "daily", "Hasta luego, nos vemos pronto.", "回头见，我们很快再见。"],
  ["hasta pronto", "exp.", "再见，很快再见", "A1", "daily", "Hasta pronto, amigo.", "再见，朋友。"],
  ["hasta mañana", "exp.", "明天见", "A1", "daily", "Hasta mañana en la oficina.", "明天办公室见。"],
  ["encantado", "adj./exp.", "很高兴认识你", "A1", "daily", "Mucho gusto, encantado.", "很高兴认识你。"],
  ["mucho gusto", "exp.", "初次见面，幸会", "A1", "daily", "Mucho gusto en conocerte.", "非常高兴认识你。"],
  ["qué tal", "exp.", "怎么样，你好吗", "A1", "daily", "¿Qué tal todo por allí?", "那边一切都好吗？"],
  ["cómo estás", "exp.", "你好吗，最近怎样", "A1", "daily", "¿Cómo estás hoy?", "你今天怎么样？"],
  ["muy bien", "exp.", "非常好", "A1", "daily", "Estoy muy bien, gracias.", "我很好，谢谢。"],

  // Pronouns & Interrogatives
  ["yo", "pron.", "我", "A1", "grammar", "Yo soy estudiante.", "我是学生。"],
  ["tú", "pron.", "你", "A1", "grammar", "¿Tú de dónde eres?", "你来自哪里？"],
  ["él", "pron.", "他", "A1", "grammar", "Él es mi hermano.", "他是我的兄弟。"],
  ["ella", "pron.", "她", "A1", "grammar", "Ella trabaja en Madrid.", "她在马德里工作。"],
  ["usted", "pron.", "您", "A1", "grammar", "¿Cómo se llama usted?", "您叫什么名字？"],
  ["nosotros", "pron.", "我们（阳性/混合）", "A1", "grammar", "Nosotros vivimos aquí.", "我们住在这里。"],
  ["nosotras", "pron.", "我们（阴性）", "A1", "grammar", "Nosotras somos amigas.", "我们是朋友。"],
  ["vosotros", "pron.", "你们（阳性/混合）", "A1", "grammar", "¿Vosotros habláis español?", "你们说西语吗？"],
  ["vosotras", "pron.", "你们（阴性）", "A1", "grammar", "Vosotras sois muy amables.", "你们非常和善。"],
  ["ellos", "pron.", "他们", "A1", "grammar", "Ellos son profesores.", "他们是老师。"],
  ["ellas", "pron.", "她们", "A1", "grammar", "Ellas están en la biblioteca.", "她们在图书馆。"],
  ["ustedes", "pron.", "您各位，你们", "A1", "grammar", "¿Ustedes tienen alguna duda?", "诸位有什么疑问吗？"],
  ["este", "adj./pron.", "这，这个（阳性）", "A1", "grammar", "Este libro es muy bueno.", "这本书非常好。"],
  ["esta", "adj./pron.", "这，这个（阴性）", "A1", "grammar", "Esta casa es grande.", "这个房子很大。"],
  ["esto", "pron.", "这个（中性）", "A1", "grammar", "¿Qué es esto?", "这是什么？"],
  ["ese", "adj./pron.", "那，那个（阳性）", "A1", "grammar", "Ese coche es rojo.", "那辆车是红色的。"],
  ["esa", "adj./pron.", "那，那个（阴性）", "A1", "grammar", "Esa chica es mi prima.", "那个女孩是我表妹。"],
  ["eso", "pron.", "那个（中性）", "A1", "grammar", "Eso no es verdad.", "那不是真的。"],
  ["aquel", "adj./pron.", "那边的，远处的（阳性）", "A1", "grammar", "Aquel edificio es el museo.", "那座建筑是博物馆。"],
  ["aquella", "adj./pron.", "那边的，远处的（阴性）", "A1", "grammar", "Aquella montaña es muy alta.", "那座山很高。"],
  ["qué", "pron.", "什么", "A1", "grammar", "¿Qué haces ahora?", "你现在在做什么？"],
  ["quién", "pron.", "谁", "A1", "grammar", "¿Quién es esa persona?", "那个人是谁？"],
  ["cómo", "adv.", "怎样，如何", "A1", "grammar", "¿Cómo te llamas?", "你叫什么名字？"],
  ["dónde", "adv.", "哪里", "A1", "grammar", "¿Dónde vives?", "你住在哪里？"],
  ["cuándo", "adv.", "何时，什么时候", "A1", "grammar", "¿Cuándo empieza la clase?", "课程什么时候开始？"],
  ["cuánto", "adj./pron.", "多少", "A1", "grammar", "¿Cuánto cuesta esto?", "这个多少钱？"],
  ["cuál", "pron.", "哪一个", "A1", "grammar", "¿Cuál es tu número de teléfono?", "你的电话号码是哪一个？"],
  ["por qué", "exp.", "为什么", "A1", "grammar", "¿Por qué estudias español?", "你为什么学西班牙语？"],
  ["porque", "conj.", "因为", "A1", "grammar", "Porque me gusta la cultura.", "因为我喜欢这里的文化。"],

  // Numbers & Quantifiers
  ["cero", "num.", "零", "A1", "daily"],
  ["uno", "num.", "一", "A1", "daily"],
  ["dos", "num.", "二", "A1", "daily"],
  ["tres", "num.", "三", "A1", "daily"],
  ["cuatro", "num.", "四", "A1", "daily"],
  ["cinco", "num.", "五", "A1", "daily"],
  ["seis", "num.", "六", "A1", "daily"],
  ["siete", "num.", "七", "A1", "daily"],
  ["ocho", "num.", "八", "A1", "daily"],
  ["nueve", "num.", "九", "A1", "daily"],
  ["diez", "num.", "十", "A1", "daily"],
  ["once", "num.", "十一", "A1", "daily"],
  ["doce", "num.", "十二", "A1", "daily"],
  ["trece", "num.", "十三", "A1", "daily"],
  ["catorce", "num.", "十四", "A1", "daily"],
  ["quince", "num.", "十五", "A1", "daily"],
  ["dieciséis", "num.", "十六", "A1", "daily"],
  ["diecisiete", "num.", "十七", "A1", "daily"],
  ["dieciocho", "num.", "十八", "A1", "daily"],
  ["diecinueve", "num.", "十九", "A1", "daily"],
  ["veinte", "num.", "二十", "A1", "daily"],
  ["veintiuno", "num.", "二十一", "A1", "daily"],
  ["treinta", "num.", "三十", "A1", "daily"],
  ["cuarenta", "num.", "四十", "A1", "daily"],
  ["cincuenta", "num.", "五十", "A1", "daily"],
  ["sesenta", "num.", "六十", "A1", "daily"],
  ["setenta", "num.", "七十", "A1", "daily"],
  ["ochenta", "num.", "八十", "A1", "daily"],
  ["noventa", "num.", "九十", "A1", "daily"],
  ["cien", "num.", "一百", "A1", "daily"],
  ["ciento", "num.", "百（多出部分）", "A1", "daily"],
  ["doscientos", "num.", "两百", "A1", "daily"],
  ["quinientos", "num.", "五百", "A1", "daily"],
  ["mil", "num.", "一千", "A1", "daily"],
  ["millón", "m.", "百万", "A1", "daily"],
  ["primero", "adj.", "第一的", "A1", "daily"],
  ["segundo", "adj./m.", "第二的；秒", "A1", "daily"],
  ["tercero", "adj.", "第三的", "A1", "daily"],
  ["cuarto", "adj./m.", "第四的；房间", "A1", "daily"],
  ["quinto", "adj.", "第五的", "A1", "daily"],
  ["mucho", "adj./adv.", "很多，非常", "A1", "daily"],
  ["poco", "adj./adv.", "很少，一点点", "A1", "daily"],
  ["bastante", "adj./adv.", "相当，足够", "A1", "daily"],
  ["demasiado", "adj./adv.", "太，过多", "A1", "daily"],
  ["más", "adv.", "更，加", "A1", "daily"],
  ["menos", "adv.", "较少，减", "A1", "daily"],
  ["todo", "adj./pron.", "全部，一切", "A1", "daily"],
  ["nada", "pron./adv.", "什么都没有，毫不", "A1", "daily"],
  ["algo", "pron./adv.", "某些东西，有点", "A1", "daily"],
  ["alguien", "pron.", "某人，有人", "A1", "daily"],
  ["nadie", "pron.", "没有人", "A1", "daily"],
  ["cada", "adj.", "每个，各个", "A1", "daily"],
  ["ambos", "adj./pron.", "两者，双方", "A1", "daily"],
  ["medio", "adj./m.", "一半的；中间", "A1", "daily"],

  // Time, Days & Dates
  ["tiempo", "m.", "时间；天气", "A1", "daily"],
  ["hora", "f.", "小时；时间", "A1", "daily"],
  ["minuto", "m.", "分钟", "A1", "daily"],
  ["día", "m.", "天，日子，白天", "A1", "daily"],
  ["noche", "f.", "夜晚", "A1", "daily"],
  ["mañana", "f./adv.", "早晨，上午；明天", "A1", "daily"],
  ["tarde", "f./adv.", "下午；迟，晚", "A1", "daily"],
  ["semana", "f.", "周，星期", "A1", "daily"],
  ["mes", "m.", "月份", "A1", "daily"],
  ["año", "m.", "年，岁", "A1", "daily"],
  ["hoy", "adv.", "今天", "A1", "daily"],
  ["ayer", "adv.", "昨天", "A1", "daily"],
  ["anteayer", "adv.", "前天", "A1", "daily"],
  ["anoche", "adv.", "昨晚", "A1", "daily"],
  ["ahora", "adv.", "现在", "A1", "daily"],
  ["luego", "adv.", "随后，然后", "A1", "daily"],
  ["después", "adv.", "在...之后，后来", "A1", "daily"],
  ["antes", "adv.", "在...之前，以前", "A1", "daily"],
  ["siempre", "adv.", "总是，永远", "A1", "daily"],
  ["nunca", "adv.", "从不，绝不", "A1", "daily"],
  ["jamás", "adv.", "绝不，决不", "A1", "daily"],
  ["a veces", "exp.", "有时，偶尔", "A1", "daily"],
  ["a menudo", "exp.", "经常，常常", "A1", "daily"],
  ["temprano", "adv.", "早", "A1", "daily"],
  ["pronto", "adv.", "很快，马上", "A1", "daily"],
  ["ya", "adv.", "已经，立刻", "A1", "daily"],
  ["todavía", "adv.", "仍然，还", "A1", "daily"],
  ["lunes", "m.", "星期一", "A1", "daily"],
  ["martes", "m.", "星期二", "A1", "daily"],
  ["miércoles", "m.", "星期三", "A1", "daily"],
  ["jueves", "m.", "星期四", "A1", "daily"],
  ["viernes", "m.", "星期五", "A1", "daily"],
  ["sábado", "m.", "星期六", "A1", "daily"],
  ["domingo", "m.", "星期天", "A1", "daily"],
  ["fin de semana", "m.", "周末", "A1", "daily"],
  ["enero", "m.", "一月", "A1", "daily"],
  ["febrero", "m.", "二月", "A1", "daily"],
  ["marzo", "m.", "三月", "A1", "daily"],
  ["abril", "m.", "四月", "A1", "daily"],
  ["mayo", "m.", "五月", "A1", "daily"],
  ["junio", "m.", "六月", "A1", "daily"],
  ["julio", "m.", "七月", "A1", "daily"],
  ["agosto", "m.", "八月", "A1", "daily"],
  ["septiembre", "m.", "九月", "A1", "daily"],
  ["octubre", "m.", "十月", "A1", "daily"],
  ["noviembre", "m.", "十一月", "A1", "daily"],
  ["diciembre", "m.", "十二月", "A1", "daily"],
  ["primavera", "f.", "春季", "A1", "daily"],
  ["verano", "m.", "夏季", "A1", "daily"],
  ["otoño", "m.", "秋季", "A1", "daily"],
  ["invierno", "m.", "冬季", "A1", "daily"],
  ["estación", "f.", "季节；车站", "A1", "daily"],

  // Family & Identity
  ["persona", "f.", "人", "A1", "daily"],
  ["hombre", "m.", "男人，人类", "A1", "daily"],
  ["mujer", "f.", "女人，妻子", "A1", "daily"],
  ["niño", "m.", "男孩，儿童", "A1", "daily"],
  ["niña", "f.", "女孩", "A1", "daily"],
  ["chico", "m.", "小伙子，男孩", "A1", "daily"],
  ["chica", "f.", "姑娘，女孩", "A1", "daily"],
  ["padre", "m.", "父亲", "A1", "daily"],
  ["madre", "f.", "母亲", "A1", "daily"],
  ["padres", "m.pl.", "父母，双亲", "A1", "daily"],
  ["hijo", "m.", "儿子", "A1", "daily"],
  ["hija", "f.", "女儿", "A1", "daily"],
  ["hermano", "m.", "兄弟，哥哥，弟弟", "A1", "daily"],
  ["hermana", "f.", "姐妹，姐姐，妹妹", "A1", "daily"],
  ["abuelo", "m.", "爷爷，外公", "A1", "daily"],
  ["abuela", "f.", "奶奶，外婆", "A1", "daily"],
  ["nieto", "m.", "孙子，外孙", "A1", "daily"],
  ["nieta", "f.", "孙女，外孙女", "A1", "daily"],
  ["tío", "m.", "叔伯舅姑父", "A1", "daily"],
  ["tía", "f.", "姑姨婶伯母", "A1", "daily"],
  ["primo", "m.", "堂表兄弟", "A1", "daily"],
  ["prima", "f.", "堂表姐妹", "A1", "daily"],
  ["sobrino", "m.", "侄子，外甥", "A1", "daily"],
  ["sobrina", "f.", "侄女，外甥女", "A1", "daily"],
  ["marido", "m.", "丈夫", "A1", "daily"],
  ["esposo", "m.", "配偶，丈夫", "A1", "daily"],
  ["esposa", "f.", "妻子", "A1", "daily"],
  ["novio", "m.", "男朋友，新郎", "A1", "daily"],
  ["novia", "f.", "女朋友，新娘", "A1", "daily"],
  ["amigo", "m.", "朋友（男）", "A1", "daily"],
  ["amiga", "f.", "朋友（女）", "A1", "daily"],
  ["compañero", "m.", "同伴，同学，同事", "A1", "daily"],
  ["vecino", "m.", "邻居", "A1", "daily"],
  ["bebé", "m.", "婴儿", "A1", "daily"],
  ["gente", "f.", "人们，大家", "A1", "daily"],
  ["nombre", "m.", "名字", "A1", "daily"],
  ["apellido", "m.", "姓氏", "A1", "daily"],
  ["edad", "f.", "年龄", "A1", "daily"],
  ["cumpleaños", "m.", "生日", "A1", "daily"],
  ["país", "m.", "国家", "A1", "travel"],
  ["nacionalidad", "f.", "国籍", "A1", "daily"],
  ["idioma", "m.", "语言", "A1", "daily"],
  ["lengua", "f.", "舌头；语言", "A1", "daily"],
  ["español", "m./adj.", "西班牙语；西班牙的", "A1", "daily"],
  ["inglés", "m./adj.", "英语；英国的", "A1", "daily"],
  ["chino", "m./adj.", "汉语；中国的", "A1", "daily"],
  ["profesión", "f.", "职业", "A1", "daily"],
  ["trabajo", "m.", "工作", "A1", "daily"],
  ["estudiante", "m./f.", "学生", "A1", "daily"],
  ["profesor", "m.", "教师，教授", "A1", "daily"],
  ["médico", "m.", "医生", "A1", "daily"],
  ["camarero", "m.", "服务员", "A1", "food"],
  ["cocinero", "m.", "厨师", "A1", "food"],
  ["policía", "m./f.", "警察", "A1", "daily"],
  ["bombero", "m.", "消防员", "A1", "daily"],
  ["dependiente", "m.", "店员，售货员", "A1", "daily"],

  // House & Daily Objects
  ["casa", "f.", "家，房子", "A1", "daily"],
  ["hogar", "m.", "家园，家庭", "A1", "daily"],
  ["piso", "m.", "公寓，楼层", "A1", "daily"],
  ["apartamento", "m.", "公寓套间", "A1", "daily"],
  ["edificio", "m.", "大楼，建筑", "A1", "daily"],
  ["habitación", "f.", "房间", "A1", "daily"],
  ["dormitorio", "m.", "卧室", "A1", "daily"],
  ["sala", "f.", "大厅，厅", "A1", "daily"],
  ["salón", "m.", "客厅", "A1", "daily"],
  ["cocina", "f.", "厨房", "A1", "food"],
  ["baño", "m.", "洗手间，浴室", "A1", "daily"],
  ["aseo", "m.", "卫生间，盥洗室", "A1", "daily"],
  ["puerta", "f.", "门", "A1", "daily"],
  ["ventana", "f.", "窗户", "A1", "daily"],
  ["pared", "f.", "墙壁", "A1", "daily"],
  ["suelo", "m.", "地面，地板", "A1", "daily"],
  ["techo", "m.", "天花板，屋顶", "A1", "daily"],
  ["balcón", "m.", "阳台", "A1", "daily"],
  ["jardín", "m.", "花园", "A1", "daily"],
  ["garaje", "m.", "车库", "A1", "daily"],
  ["escalera", "f.", "楼梯", "A1", "daily"],
  ["ascensor", "m.", "电梯", "A1", "daily"],
  ["mueble", "m.", "家具", "A1", "daily"],
  ["cama", "f.", "床", "A1", "daily"],
  ["mesa", "f.", "桌子", "A1", "daily"],
  ["silla", "f.", "椅子", "A1", "daily"],
  ["sofá", "m.", "沙发", "A1", "daily"],
  ["armario", "m.", "衣柜，橱柜", "A1", "daily"],
  ["estantería", "f.", "书架，架子", "A1", "daily"],
  ["lámpara", "f.", "台灯，灯", "A1", "daily"],
  ["espejo", "m.", "镜子", "A1", "daily"],
  ["cuadro", "m.", "画，框", "A1", "daily"],
  ["reloj", "m.", "钟表", "A1", "daily"],
  ["llave", "f.", "钥匙", "A1", "daily"],
  ["puerta", "f.", "门", "A1", "daily"],
  ["teléfono", "m.", "电话", "A1", "daily"],
  ["móvil", "m.", "手机", "A1", "daily"],
  ["ordenador", "m.", "电脑", "A1", "daily"],
  ["televisión", "f.", "电视", "A1", "daily"],
  ["radio", "f.", "收音机，广播", "A1", "daily"],
  ["nevera", "f.", "冰箱", "A1", "food"],
  ["frigorífico", "m.", "电冰箱", "A1", "food"],
  ["lavadora", "f.", "洗衣机", "A1", "daily"],
  ["plato", "m.", "盘子；菜肴", "A1", "food"],
  ["vaso", "m.", "玻璃杯", "A1", "food"],
  ["taza", "f.", "茶杯，马克杯", "A1", "food"],
  ["cuchara", "f.", "勺子", "A1", "food"],
  ["tenedor", "m.", "叉子", "A1", "food"],
  ["cuchillo", "m.", "刀", "A1", "food"],
  ["servilleta", "f.", "餐巾纸", "A1", "food"],
  ["botella", "f.", "瓶子", "A1", "food"],
  ["caja", "f.", "盒子，箱子；收银台", "A1", "daily"],
  ["bolsa", "f.", "袋子，包", "A1", "daily"],
  ["papel", "m.", "纸", "A1", "daily"],
  ["bolígrafo", "m.", "圆珠笔", "A1", "daily"],
  ["lápiz", "m.", "铅笔", "A1", "daily"],
  ["goma", "f.", "橡皮", "A1", "daily"],
  ["cuaderno", "m.", "笔记本", "A1", "daily"],
  ["libro", "m.", "书", "A1", "daily"],
  ["mochila", "f.", "双肩包", "A1", "daily"],
  ["maleta", "f.", "手提箱，行李箱", "A1", "travel"],
  ["carta", "f.", "信；菜单", "A1", "daily"],

  // Colors & Common Adjectives
  ["blanco", "adj.", "白色的", "A1", "daily"],
  ["negro", "adj.", "黑色的", "A1", "daily"],
  ["rojo", "adj.", "红色的", "A1", "daily"],
  ["azul", "adj.", "蓝色的", "A1", "daily"],
  ["verde", "adj.", "绿色的", "A1", "daily"],
  ["amarillo", "adj.", "黄色的", "A1", "daily"],
  ["naranja", "adj./f.", "橙色的；橙子", "A1", "daily"],
  ["rosa", "adj./f.", "粉色的；玫瑰", "A1", "daily"],
  ["gris", "adj.", "灰色的", "A1", "daily"],
  ["marrón", "adj.", "棕色的，褐色的", "A1", "daily"],
  ["morado", "adj.", "紫色的", "A1", "daily"],
  ["claro", "adj.", "浅色的；清楚的", "A1", "daily"],
  ["oscuro", "adj.", "深色的，黑暗的", "A1", "daily"],
  ["grande", "adj.", "大的", "A1", "daily"],
  ["pequeño", "adj.", "小的", "A1", "daily"],
  ["alto", "adj.", "高的", "A1", "daily"],
  ["bajo", "adj.", "矮的，低的", "A1", "daily"],
  ["gordo", "adj.", "胖的", "A1", "daily"],
  ["delgado", "adj.", "瘦的", "A1", "daily"],
  ["nuevo", "adj.", "新的", "A1", "daily"],
  ["viejo", "adj.", "旧的，年老的", "A1", "daily"],
  ["joven", "adj./m.f.", "年轻的；年轻人", "A1", "daily"],
  ["bueno", "adj.", "好的，善良的", "A1", "daily"],
  ["malo", "adj.", "坏的，差的", "A1", "daily"],
  ["bonito", "adj.", "漂亮的，好看的", "A1", "daily"],
  ["feo", "adj.", "难看的，丑的", "A1", "daily"],
  ["fácil", "adj.", "容易的，简单的", "A1", "daily"],
  ["difícil", "adj.", "困难的", "A1", "daily"],
  ["caro", "adj.", "贵的，昂贵的", "A1", "daily"],
  ["barato", "adj.", "便宜的", "A1", "daily"],
  ["rápido", "adj./adv.", "快的；快地", "A1", "daily"],
  ["lento", "adj./adv.", "慢的；慢地", "A1", "daily"],
  ["limpio", "adj.", "干净的", "A1", "daily"],
  ["sucio", "adj.", "脏的", "A1", "daily"],
  ["caliente", "adj.", "热的，烫的", "A1", "food"],
  ["frío", "adj./m.", "冷的；寒冷", "A1", "daily"],
  ["rico", "adj.", "美味的；富有的", "A1", "food"],
  ["pobre", "adj.", "贫穷的，可怜的", "A1", "daily"],
  ["fuerte", "adj.", "强壮的，坚固的", "A1", "daily"],
  ["débil", "adj.", "虚弱的", "A1", "daily"],
  ["simpático", "adj.", "讨人喜欢的，和气的", "A1", "emotion"],
  ["antipático", "adj.", "令人反感的", "A1", "emotion"],
  ["inteligente", "adj.", "聪明的", "A1", "daily"],
  ["tonto", "adj.", "傻的，愚蠢的", "A1", "daily"],
  ["amable", "adj.", "亲切的，热情的", "A1", "emotion"],
  ["alegre", "adj.", "开朗的，快乐的", "A1", "emotion"],
  ["triste", "adj.", "伤心的，悲伤的", "A1", "emotion"],
  ["feliz", "adj.", "幸福的，高兴的", "A1", "emotion"],
  ["contento", "adj.", "满意的，高兴的", "A1", "emotion"],
  ["cansado", "adj.", "疲倦的，累的", "A1", "daily"],
  ["enfermo", "adj.", "生病的", "A1", "daily"],
  ["sano", "adj.", "健康的", "A1", "daily"],
  ["abierto", "adj.", "开着的，开放的", "A1", "daily"],
  ["cerrado", "adj.", "关着的", "A1", "daily"],
  ["libre", "adj.", "空闲的，自由的", "A1", "daily"],
  ["ocupado", "adj.", "忙碌的，被占用的", "A1", "daily"],
  ["lleno", "adj.", "满的", "A1", "daily"],
  ["vacío", "adj.", "空的", "A1", "daily"],
  ["correcto", "adj.", "正确的", "A1", "daily"],
  ["incorrecto", "adj.", "错误的", "A1", "daily"],
  ["mismo", "adj.", "相同的，同一个", "A1", "daily"],
  ["diferente", "adj.", "不同的", "A1", "daily"],
  ["seguro", "adj./m.", "安全的，肯定的；保险", "A1", "daily"],
  ["peligroso", "adj.", "危险的", "A1", "daily"],
  ["importante", "adj.", "重要的", "A1", "daily"],
  ["posible", "adj.", "可能的", "A1", "daily"],
  ["imposible", "adj.", "不可能的", "A1", "daily"],
  ["verdadero", "adj.", "真实的", "A1", "daily"],
  ["falso", "adj.", "虚假的", "A1", "daily"],

  // Food & Beverage A1
  ["comida", "f.", "食物；午饭", "A1", "food"],
  ["bebida", "f.", "饮料", "A1", "food"],
  ["agua", "f.", "水", "A1", "food"],
  ["pan", "m.", "面包", "A1", "food"],
  ["leche", "f.", "牛奶", "A1", "food"],
  ["café", "m.", "咖啡", "A1", "food"],
  ["té", "m.", "茶", "A1", "food"],
  ["zumo", "m.", "果汁", "A1", "food"],
  ["jugo", "m.", "果汁（拉美）", "A1", "food"],
  ["vino", "m.", "葡萄酒", "A1", "food"],
  ["cerveza", "f.", "啤酒", "A1", "food"],
  ["carne", "f.", "肉", "A1", "food"],
  ["pollo", "m.", "鸡肉", "A1", "food"],
  ["pescado", "m.", "鱼，鱼肉", "A1", "food"],
  ["huevo", "m.", "鸡蛋", "A1", "food"],
  ["queso", "m.", "奶酪，芝士", "A1", "food"],
  ["arroz", "m.", "大米，米饭", "A1", "food"],
  ["pasta", "f.", "意面，面食", "A1", "food"],
  ["sopa", "f.", "汤", "A1", "food"],
  ["ensalada", "f.", "沙拉", "A1", "food"],
  ["fruta", "f.", "水果", "A1", "food"],
  ["manzana", "f.", "苹果", "A1", "food"],
  ["plátano", "m.", "香蕉", "A1", "food"],
  ["naranja", "f.", "橙子", "A1", "food"],
  ["limón", "m.", "柠檬", "A1", "food"],
  ["fresa", "f.", "草莓", "A1", "food"],
  ["uva", "f.", "葡萄", "A1", "food"],
  ["verdura", "f.", "蔬菜", "A1", "food"],
  ["tomate", "m.", "西红柿", "A1", "food"],
  ["patata", "f.", "土豆", "A1", "food"],
  ["cebolla", "f.", "洋葱", "A1", "food"],
  ["ajo", "m.", "大蒜", "A1", "food"],
  ["lechuga", "f.", "生菜", "A1", "food"],
  ["sal", "f.", "盐", "A1", "food"],
  ["azúcar", "m./f.", "糖", "A1", "food"],
  ["aceite", "m.", "油", "A1", "food"],
  ["vinagre", "m.", "醋", "A1", "food"],
  ["mantequilla", "f.", "黄油", "A1", "food"],
  ["pimienta", "f.", "胡椒", "A1", "food"],
  ["bocadillo", "m.", "法棍三明治", "A1", "food"],
  ["sándwich", "m.", "三明治", "A1", "food"],
  ["tapas", "f.pl.", "西班牙风味小吃", "A1", "food"],
  ["paella", "f.", "西班牙海鲜饭", "A1", "food"],
  ["tortilla", "f.", "西班牙土豆煎蛋饼", "A1", "food"],
  ["jamón", "m.", "火腿", "A1", "food"],
  ["helado", "m.", "冰淇淋", "A1", "food"],
  ["chocolate", "m.", "巧克力", "A1", "food"],
  ["pastel", "m.", "蛋糕", "A1", "food"],
  ["galleta", "f.", "饼干", "A1", "food"],
  ["dulce", "adj./m.", "甜的；糖果", "A1", "food"],
  ["amargo", "adj.", "苦的", "A1", "food"],
  ["desayuno", "m.", "早餐", "A1", "food"],
  ["almuerzo", "m.", "午餐", "A1", "food"],
  ["cena", "f.", "晚餐", "A1", "food"],
  ["merienda", "f.", "下午茶点", "A1", "food"],
  ["menú", "m.", "菜单，套餐", "A1", "food"],
  ["postre", "m.", "甜点", "A1", "food"],
  ["cuenta", "f.", "账单；账户", "A1", "food"],
  ["propina", "f.", "小费", "A1", "food"],

  // Clothes & Accessories
  ["ropa", "f.", "衣服，衣物", "A1", "daily"],
  ["camisa", "f.", "衬衫", "A1", "daily"],
  ["camiseta", "f.", "T恤，汗衫", "A1", "daily"],
  ["pantalón", "m.", "裤子", "A1", "daily"],
  ["pantalones", "m.pl.", "裤子", "A1", "daily"],
  ["vaqueros", "m.pl.", "牛仔裤", "A1", "daily"],
  ["falda", "f.", "裙子，半身裙", "A1", "daily"],
  ["vestido", "m.", "连衣裙，礼服", "A1", "daily"],
  ["abrigo", "m.", "大衣，外套", "A1", "daily"],
  ["chaqueta", "f.", "夹克，外套", "A1", "daily"],
  ["jersey", "m.", "毛衣", "A1", "daily"],
  ["suéter", "m.", "毛衣（拉美）", "A1", "daily"],
  ["traje", "m.", "西装，套装", "A1", "daily"],
  ["zapato", "m.", "鞋子", "A1", "daily"],
  ["zapatos", "m.pl.", "鞋", "A1", "daily"],
  ["zapatillas", "f.pl.", "运动鞋，拖鞋", "A1", "daily"],
  ["bota", "f.", "靴子", "A1", "daily"],
  ["calcetín", "m.", "袜子", "A1", "daily"],
  ["calcetines", "m.pl.", "袜子", "A1", "daily"],
  ["sombrero", "m.", "帽子（有檐）", "A1", "daily"],
  ["gorra", "f.", "鸭舌帽", "A1", "daily"],
  ["bufanda", "f.", "围巾", "A1", "daily"],
  ["guante", "m.", "手套", "A1", "daily"],
  ["cinturón", "m.", "腰带，皮带", "A1", "daily"],
  ["gafas", "f.pl.", "眼镜", "A1", "daily"],
  ["paraguas", "m.", "雨伞", "A1", "daily"],
  ["bolso", "m.", "女用手提包", "A1", "daily"],
  ["cartera", "f.", "钱包，公文包", "A1", "daily"],
  ["talla", "f.", "尺码，身材", "A1", "daily"],

  // City & Places
  ["ciudad", "f.", "城市", "A1", "travel"],
  ["pueblo", "m.", "小镇，村庄；人民", "A1", "travel"],
  ["capital", "f./m.", "首都；资本", "A1", "travel"],
  ["centro", "m.", "中心，市中心", "A1", "travel"],
  ["calle", "f.", "街道", "A1", "travel"],
  ["avenida", "f.", "大道", "A1", "travel"],
  ["plaza", "f.", "广场", "A1", "travel"],
  ["esquina", "f.", "拐角，街角", "A1", "travel"],
  ["parque", "m.", "公园", "A1", "travel"],
  ["puente", "m.", "桥", "A1", "travel"],
  ["edificio", "m.", "建筑物", "A1", "travel"],
  ["tienda", "f.", "商店", "A1", "daily"],
  ["supermercado", "m.", "超市", "A1", "daily"],
  ["mercado", "m.", "集市，市场", "A1", "daily"],
  ["farmacia", "f.", "药店", "A1", "daily"],
  ["banco", "m.", "银行；长椅", "A1", "business"],
  ["hospital", "m.", "医院", "A1", "daily"],
  ["escuela", "f.", "学校", "A1", "daily"],
  ["colegio", "m.", "小学，学院", "A1", "daily"],
  ["universidad", "f.", "大学", "A1", "daily"],
  ["biblioteca", "f.", "图书馆", "A1", "daily"],
  ["museo", "m.", "博物馆", "A1", "travel"],
  ["teatro", "m.", "剧院", "A1", "travel"],
  ["cine", "m.", "电影院", "A1", "travel"],
  ["restaurante", "m.", "餐馆", "A1", "food"],
  ["bar", "m.", "酒吧", "A1", "food"],
  ["cafetería", "f.", "咖啡馆", "A1", "food"],
  ["hotel", "m.", "酒店，宾馆", "A1", "travel"],
  ["playa", "f.", "海滩", "A1", "travel"],
  ["mar", "m./f.", "大海", "A1", "travel"],
  ["montaña", "f.", "高山", "A1", "travel"],
  ["aeropuerto", "m.", "机场", "A1", "travel"],
  ["estación", "f.", "车站", "A1", "travel"],
  ["parada", "f.", "公交站", "A1", "travel"],
  ["metro", "m.", "地铁；米", "A1", "travel"],
  ["autobús", "m.", "公共汽车", "A1", "travel"],
  ["bus", "m.", "公交车", "A1", "travel"],
  ["tren", "m.", "火车", "A1", "travel"],
  ["taxi", "m.", "出租车", "A1", "travel"],
  ["coche", "m.", "小汽车", "A1", "travel"],
  ["auto", "m.", "汽车（拉美）", "A1", "travel"],
  ["bicicleta", "f.", "自行车", "A1", "travel"],
  ["bici", "f.", "自行车（口语）", "A1", "travel"],
  ["moto", "f.", "摩托车", "A1", "travel"],
  ["avión", "m.", "飞机", "A1", "travel"],
  ["barco", "m.", "轮船", "A1", "travel"],
  ["billete", "m.", "票；钞票", "A1", "travel"],
  ["boleto", "m.", "车票（拉美）", "A1", "travel"],
  ["viaje", "m.", "旅行", "A1", "travel"],
  ["turista", "m./f.", "游客", "A1", "travel"],
  ["mapa", "m.", "地图", "A1", "travel"],
  ["dirección", "f.", "地址；方向", "A1", "travel"],

  // Core A1 Verbs
  ["ser", "v.", "是（固有本质）", "A1", "grammar", "Yo soy profesor.", "我是老师。"],
  ["estar", "v.", "在；处于（临时状态）", "A1", "grammar", "¿Dónde estás ahora?", "你现在在哪里？"],
  ["tener", "v.", "有；拥有", "A1", "grammar", "Tengo veinte años.", "我二十岁。"],
  ["haber", "v.", "有（存在/完成时助动词）", "A1", "grammar", "Hay muchos libros aquí.", "这里有很多书。"],
  ["hacer", "v.", "做；制作；天气如何", "A1", "grammar", "Hoy hace muy buen tiempo.", "今天天气非常好。"],
  ["ir", "v.", "去", "A1", "travel", "Voy al supermercado.", "我去超市。"],
  ["venir", "v.", "来", "A1", "daily", "¿Vienes a mi fiesta?", "你来参加我的聚会吗？"],
  ["salir", "v.", "出去，离开", "A1", "travel", "Salgo de casa a las ocho.", "我八点离开家。"],
  ["entrar", "v.", "进入", "A1", "daily", "Entra, por favor.", "请进。"],
  ["llegar", "v.", "到达", "A1", "travel", "El tren llega a tiempo.", "火车准时到达。"],
  ["volver", "v.", "返回，回来", "A1", "travel", "Vuelvo a casa por la noche.", "我晚上回家。"],
  ["ver", "v.", "看见，看", "A1", "daily", "Veo una película.", "我在看一部电影。"],
  ["mirar", "v.", "注视，看", "A1", "daily", "Mira esa foto.", "看那张照片。"],
  ["oír", "v.", "听见", "A1", "daily", "¿Me oyes bien?", "你听得清我说话吗？"],
  ["escuchar", "v.", "倾听，听", "A1", "daily", "Me gusta escuchar música.", "我喜欢听音乐。"],
  ["hablar", "v.", "说话，讲（某语言）", "A1", "daily", "Hablo un poco de español.", "我说一点西班牙语。"],
  ["decir", "v.", "说，告诉", "A1", "daily", "¿Qué dices?", "你在说什么？"],
  ["comer", "v.", "吃", "A1", "food", "Comemos juntos hoy.", "我们今天一起吃饭。"],
  ["beber", "v.", "喝", "A1", "food", "Bebo mucha agua.", "我喝很多水。"],
  ["tomar", "v.", "拿；喝；乘坐", "A1", "food", "Tomo el metro todos los días.", "我每天坐地铁。"],
  ["vivir", "v.", "居住，生活", "A1", "daily", "Vivo en Barcelona.", "我住在巴塞罗那。"],
  ["trabajar", "v.", "工作", "A1", "business", "Trabajo en una oficina.", "我在办公室工作。"],
  ["estudiar", "v.", "学习", "A1", "daily", "Estudio español todos los días.", "我每天学习西班牙语。"],
  ["aprender", "v.", "学会，学", "A1", "daily", "Aprendo muchas palabras.", "我学会了很多单词。"],
  ["escribir", "v.", "写", "A1", "daily", "Escribo un correo a mi amigo.", "我给朋友写一封邮件。"],
  ["leer", "v.", "阅读，读", "A1", "daily", "Leo el periódico por la mañana.", "我早上读报纸。"],
  ["comprar", "v.", "买，购买", "A1", "daily", "Quiero comprar pan.", "我想买面包。"],
  ["pagar", "v.", "付钱，付款", "A1", "daily", "¿Puedo pagar con tarjeta?", "我可以用卡支付吗？"],
  ["vender", "v.", "出售，卖", "A1", "business"],
  ["costar", "v.", "花费，值多少钱", "A1", "daily", "¿Cuánto cuesta esta camisa?", "这件衬衫多少钱？"],
  ["querer", "v.", "想要；爱", "A1", "emotion", "Quiero aprender más.", "我想学更多。"],
  ["poder", "v.", "能够，可以", "A1", "grammar", "¿Puedo pasar?", "我可以进来吗？"],
  ["saber", "v.", "知道；掌握技能", "A1", "grammar", "No lo sé.", "我不知道。"],
  ["conocer", "v.", "认识，了解", "A1", "daily", "Conozco a esa persona.", "我认识那个人。"],
  ["llamar", "v.", "打电话；呼唤", "A1", "daily"],
  ["llamarse", "v.", "名叫", "A1", "daily", "Me llamo Carlos.", "我叫卡洛斯。"],
  ["gustar", "v.", "令人喜欢", "A1", "emotion", "Me gusta la música clásica.", "我喜欢古典音乐。"],
  ["encantar", "v.", "极喜欢，着迷", "A1", "emotion", "Me encanta la comida española.", "我极喜欢西班牙美食。"],
  ["preferir", "v.", "更喜欢，宁愿", "A1", "emotion"],
  ["dar", "v.", "给，给予", "A1", "daily"],
  ["poner", "v.", "放，放置", "A1", "daily"],
  ["llevar", "v.", "带走；穿戴", "A1", "daily"],
  ["traer", "v.", "带来", "A1", "daily"],
  ["abrir", "v.", "打开；营业", "A1", "daily"],
  ["cerrar", "v.", "关闭；打烊", "A1", "daily"],
  ["empezar", "v.", "开始", "A1", "daily"],
  ["comenzar", "v.", "开始", "A1", "daily"],
  ["terminar", "v.", "结束，完成", "A1", "daily"],
  ["acabar", "v.", "终结，刚刚", "A1", "daily"],
  ["necesitar", "v.", "需要", "A1", "daily"],
  ["buscar", "v.", "寻找", "A1", "daily"],
  ["encontrar", "v.", "找到，遇到", "A1", "daily"],
  ["esperar", "v.", "等待；希望", "A1", "daily"],
  ["usar", "v.", "使用", "A1", "daily"],
  ["utilizar", "v.", "利用，使用", "A1", "daily"],
  ["jugar", "v.", "玩耍；玩球类", "A1", "daily"],
  ["cantar", "v.", "唱歌", "A1", "daily"],
  ["bailar", "v.", "跳舞", "A1", "daily"],
  ["viajar", "v.", "旅行", "A1", "travel"],
  ["caminar", "v.", "步行，走路", "A1", "daily"],
  ["andar", "v.", "行走，运转", "A1", "daily"],
  ["correr", "v.", "跑步", "A1", "daily"],
  ["nadar", "v.", "游泳", "A1", "daily"],
  ["descansar", "v.", "休息", "A1", "daily"],
  ["dormir", "v.", "睡觉", "A1", "daily"],
  ["pensar", "v.", "想，思考；打算", "A1", "daily"],
  ["creer", "v.", "相信；认为", "A1", "daily"],
  ["sentir", "v.", "感觉；遗憾", "A1", "emotion"],
  ["preguntar", "v.", "询问，提问", "A1", "daily"],
  ["responder", "v.", "回答", "A1", "daily"],
  ["contestar", "v.", "回答，答复", "A1", "daily"],
  ["ayudar", "v.", "帮助", "A1", "daily"],
  ["cambiar", "v.", "更换，改变；找零", "A1", "daily"],
  ["pasar", "v.", "通过；度过；发生", "A1", "daily"],
  ["quedar", "v.", "留下；相约", "A1", "daily"],
  ["deber", "v./m.", "应当，欠款；职责", "A1", "grammar"],

  // Nature & Weather A1
  ["sol", "m.", "太阳，阳光", "A1", "travel"],
  ["luna", "f.", "月亮", "A1", "travel"],
  ["estrella", "f.", "星星", "A1", "travel"],
  ["cielo", "m.", "天空", "A1", "travel"],
  ["tierra", "f.", "土地，地球", "A1", "travel"],
  ["mar", "m.", "海", "A1", "travel"],
  ["río", "m.", "河流", "A1", "travel"],
  ["lago", "m.", "湖泊", "A1", "travel"],
  ["bosque", "m.", "森林", "A1", "travel"],
  ["árbol", "m.", "树木", "A1", "travel"],
  ["flor", "f.", "花朵", "A1", "travel"],
  ["planta", "f.", "植物；楼层", "A1", "travel"],
  ["animal", "m.", "动物", "A1", "travel"],
  ["perro", "m.", "狗", "A1", "daily"],
  ["gato", "m.", "猫", "A1", "daily"],
  ["pájaro", "m.", "鸟", "A1", "travel"],
  ["caballo", "m.", "马", "A1", "travel"],
  ["vaca", "f.", "母牛", "A1", "travel"],
  ["oveja", "f.", "绵羊", "A1", "travel"],
  ["cerdo", "m.", "猪", "A1", "food"],
  ["pez", "m.", "活鱼", "A1", "food"],
  ["lluvia", "f.", "雨", "A1", "travel"],
  ["nieve", "f.", "雪", "A1", "travel"],
  ["viento", "m.", "风", "A1", "travel"],
  ["nube", "f.", "云彩", "A1", "travel"],
  ["calor", "m.", "热，炎热", "A1", "travel"],
  ["frío", "m.", "寒冷", "A1", "travel"],

  // Grammar, Prepositions & Conjunctions
  ["a", "prep.", "到，朝，给（引出间接宾语/指人直宾）", "A1", "grammar"],
  ["de", "prep.", "来自；属于；由...制成", "A1", "grammar"],
  ["en", "prep.", "在...里，在...上", "A1", "grammar"],
  ["con", "prep.", "和...一起，带有", "A1", "grammar"],
  ["sin", "prep.", "没有，不带", "A1", "grammar"],
  ["por", "prep.", "为了；因；经由；在（某时段）", "A1", "grammar"],
  ["para", "prep.", "给，为了，朝着", "A1", "grammar"],
  ["sobre", "prep./m.", "在...上方；关于；信封", "A1", "grammar"],
  ["entre", "prep.", "在...之间", "A1", "grammar"],
  ["hacia", "prep.", "朝着，朝向", "A1", "grammar"],
  ["hasta", "prep.", "直到，连同", "A1", "grammar"],
  ["desde", "prep.", "从...起，自从", "A1", "grammar"],
  ["bajo", "prep.", "在...之下", "A1", "grammar"],
  ["según", "prep.", "根据，依照", "A1", "grammar"],
  ["contra", "prep.", "反对，对抗", "A1", "grammar"],
  ["aquí", "adv.", "这里", "A1", "grammar"],
  ["ahí", "adv.", "那里（离听者近）", "A1", "grammar"],
  ["allí", "adv.", "那里（离两者都远）", "A1", "grammar"],
  ["allá", "adv.", "那边，远方", "A1", "grammar"],
  ["cerca", "adv.", "靠近，近处", "A1", "grammar"],
  ["lejos", "adv.", "远离，远处", "A1", "grammar"],
  ["dentro", "adv.", "在里面", "A1", "grammar"],
  ["fuera", "adv.", "在外面", "A1", "grammar"],
  ["arriba", "adv.", "在上面，往上", "A1", "grammar"],
  ["abajo", "adv.", "在下面，往下", "A1", "grammar"],
  ["delante", "adv.", "在前面", "A1", "grammar"],
  ["detrás", "adv.", "在后面", "A1", "grammar"],
  ["al lado", "exp.", "在旁边", "A1", "grammar"],
  ["enfrente", "adv.", "在对面", "A1", "grammar"],
  ["bien", "adv./m.", "好；好处", "A1", "daily"],
  ["mal", "adv./m.", "差，坏；恶", "A1", "daily"],
  ["sí", "adv.", "是，对", "A1", "daily"],
  ["no", "adv.", "不，否", "A1", "daily"],
  ["también", "adv.", "也，同样", "A1", "daily"],
  ["tampoco", "adv.", "也不", "A1", "daily"],
  ["y", "conj.", "和，与", "A1", "grammar"],
  ["e", "conj.", "和（在以i/hi开头的词前）", "A1", "grammar"],
  ["o", "conj.", "或者", "A1", "grammar"],
  ["u", "conj.", "或（在以o/ho开头的词前）", "A1", "grammar"],
  ["pero", "conj.", "但是", "A1", "grammar"],
  ["sino", "conj.", "而是", "A1", "grammar"],
  ["si", "conj.", "如果，是否", "A1", "grammar"],
  ["como", "conj./adv.", "如同；由于；像", "A1", "grammar"],
  ["que", "pron./conj.", "那个；比；以至于", "A1", "grammar"]
];

console.log("Seed A1 entries:", A1_VOCAB.length);
A1_VOCAB.forEach(e => add(...e));
console.log("Total entries after A1 seed:", allEntries.length);
