# -*- coding: utf-8 -*-
import json

books_data = [
    # BOOK 1
    ("xx1", "新现西·第1册", "A1", [
        ("第1课", [
            ("mamá", "f.", "妈妈", "daily", "日常交流", "Mi mamá es profesora.", "我妈妈是老师。"),
            ("papá", "m.", "爸爸", "daily", "日常交流", "Mi papá trabaja en un hospital.", "我爸爸在医院工作。"),
            ("este", "pron./adj.", "这，这个", "grammar", "动词介词", "Este es mi libro.", "这是我的书。"),
            ("esta", "pron./adj.", "这，这个（阴性）", "grammar", "动词介词", "Esta es mi amiga Ana.", "这是我的朋友安娜。"),
            ("esto", "pron.", "这个（中性）", "grammar", "动词介词", "¿Qué es esto?", "这是什么？"),
            ("quién", "pron.", "谁", "grammar", "动词介词", "¿Quién es ella?", "她是谁？"),
            ("qué", "pron.", "什么", "grammar", "动词介词", "¿Qué es esto?", "这是什么？"),
            ("él", "pron.", "他", "grammar", "动词介词", "Él es estudiante.", "他是学生。"),
            ("ella", "pron.", "她", "grammar", "动词介词", "Ella es médica.", "她是医生。"),
            ("usted", "pron.", "您", "daily", "日常交流", "¿Cómo está usted?", "您身体好吗？"),
            ("tú", "pron.", "你", "grammar", "动词介词", "¿De dónde eres tú?", "你是哪里人？"),
            ("yo", "pron.", "我", "grammar", "动词介词", "Yo soy de Pekín.", "我来自北京。"),
            ("sí", "adv.", "是，对", "daily", "日常交流", "Sí, soy estudiante.", "是的，我是学生。"),
            ("no", "adv.", "不，不是", "daily", "日常交流", "No, él no es profesor.", "不，他不是老师。"),
            ("hola", "interj.", "你好", "daily", "日常交流", "¡Hola! Mucho gusto.", "你好！很高兴认识你。"),
        ]),
        ("第2课", [
            ("casa", "f.", "房子，家", "daily", "日常交流", "Mi casa es pequeña pero cómoda.", "我的家虽小但很舒服。"),
            ("mesa", "f.", "桌子", "daily", "日常交流", "El libro está en la mesa.", "书在桌子上。"),
            ("silla", "f.", "椅子", "daily", "日常交流", "Tome asiento en esta silla.", "请坐在这把椅子上。"),
            ("libro", "m.", "书", "daily", "日常交流", "Leo un libro en español.", "我在读一本西语书。"),
            ("pluma", "f.", "钢笔", "daily", "日常交流", "¿Tienes una pluma?", "你有钢笔吗？"),
            ("lápiz", "m.", "铅笔", "daily", "日常交流", "Escribo con lápiz.", "我用铅笔写字。"),
            ("gato", "m.", "猫", "daily", "日常交流", "El gato duerme en el sofá.", "猫在沙发上睡觉。"),
            ("perro", "m.", "狗", "daily", "日常交流", "Tengo un perro muy leal.", "我有一只忠诚的狗。"),
            ("hermano", "m.", "兄弟", "daily", "日常交流", "Mi hermano mayor vive en Madrid.", "我哥哥住在马德里。"),
            ("amigo", "m.", "朋友", "daily", "日常交流", "Es un buen amigo mío.", "他是我的一个好朋友。"),
            ("taza", "f.", "茶杯，杯子", "daily", "日常交流", "Una taza de té caliente, por favor.", "请来一杯热茶。"),
            ("vaso", "m.", "玻璃杯", "daily", "日常交流", "Bebo un vaso de agua.", "我喝了一杯水。"),
            ("cama", "f.", "床", "daily", "日常交流", "La cama es muy suave.", "这张床非常柔软。"),
            ("sala", "f.", "客厅，大厅", "daily", "日常交流", "Descansamos en la sala.", "我们在客厅里休息。"),
            ("foto", "f.", "照片", "emotion", "情绪性格", "Esta es la foto de mi familia.", "这是我的全家福照片。"),
        ]),
        ("第3课", [
            ("estudiante", "m./f.", "学生", "daily", "日常交流", "Soy estudiante universitario.", "我是大学生。"),
            ("profesor", "m.", "教师，教授", "daily", "日常交流", "El profesor explica la lección.", "老师在讲解课文。"),
            ("médico", "m.", "医生", "business", "职场商务", "El médico me examinó atentamente.", "医生仔细地给我做了检查。"),
            ("obrero", "m.", "工人", "business", "职场商务", "Los obreros construyen el edificio.", "工人们在建大楼。"),
            ("campesino", "m.", "农民", "business", "职场商务", "Los campesinos trabajan en el campo.", "农民在田野里劳作。"),
            ("español", "adj./m.", "西班牙语；西班牙的", "daily", "日常交流", "Hablo español todos los días.", "我每天都说西班牙语。"),
            ("chino", "adj./m.", "中文；中国的", "daily", "日常交流", "Estudiamos la cultura china.", "我们学习中国文化。"),
            ("grande", "adj.", "大的", "grammar", "动词介词", "Es una ciudad muy grande.", "那是一座很大的城市。"),
            ("pequeño", "adj.", "小的", "grammar", "动词介词", "El pueblo es pequeño y tranquilo.", "村庄小而宁静。"),
            ("bonito", "adj.", "漂亮的，好看的", "emotion", "情绪性格", "Tiene unos ojos muy bonitos.", "她有一双很漂亮的眼睛。"),
            ("feo", "adj.", "难看的，丑的", "emotion", "情绪性格", "El tiempo está muy feo hoy.", "今天天气很糟糕。"),
            ("bueno", "adj.", "好的，善良的", "emotion", "情绪性格", "Es una buena persona.", "他是一个好人。"),
            ("malo", "adj.", "坏的，不好的", "emotion", "情绪性格", "Fumar es malo para la salud.", "吸烟有害健康。"),
            ("alto", "adj.", "高的", "emotion", "情绪性格", "Mi padre es muy alto.", "我父亲个子很高。"),
            ("bajo", "adj.", "矮的；低的", "emotion", "情绪性格", "El precio es muy bajo.", "价格非常低。"),
        ]),
        ("第4课", [
            ("ventana", "f.", "窗户", "daily", "日常交流", "Abre la ventana, por favor.", "请把窗户打开。"),
            ("puerta", "f.", "门", "daily", "日常交流", "Cierra la puerta con llave.", "用钥匙把门锁上。"),
            ("pizarra", "f.", "黑板", "daily", "日常交流", "Miren la pizarra.", "请看黑板。"),
            ("reloj", "m.", "钟表", "daily", "日常交流", "Miro el reloj con frecuencia.", "我经常看钟表。"),
            ("cuadro", "m.", "画，图画", "emotion", "情绪性格", "Es un cuadro al óleo famoso.", "那是一幅著名的油画。"),
            ("habitación", "f.", "房间", "daily", "日常交流", "Mi habitación da al sur.", "我的房间朝南。"),
            ("cocina", "f.", "厨房", "food", "美食餐饮", "Cocinamos juntos en la cocina.", "我们在厨房里一起做饭。"),
            ("baño", "m.", "浴室，洗手间", "daily", "日常交流", "¿Dónde está el baño?", "请问洗手间在哪里？"),
            ("jardín", "m.", "花园", "travel", "旅行交通", "Hay flores hermosas en el jardín.", "花园里有美丽的花朵。"),
            ("lámpara", "f.", "台灯，灯", "daily", "日常交流", "Enciende la lámpara de la mesa.", "把桌上的台灯打开。"),
            ("piso", "m.", "地面；楼层；公寓", "daily", "日常交流", "Vivo en el tercer piso.", "我住在三楼。"),
            ("pared", "f.", "墙壁", "daily", "日常交流", "Colgamos el mapa en la pared.", "我们把地图挂在墙上。"),
            ("techo", "m.", "天花板，屋顶", "daily", "日常交流", "El techo de la iglesia es alto.", "教堂的屋顶很高。"),
            ("limpio", "adj.", "干净的", "daily", "日常交流", "El aula está muy limpia.", "教室非常干净。"),
            ("sucio", "adj.", "脏的", "daily", "日常交流", "Mis manos están sucias.", "我的手弄脏了。"),
        ]),
        ("第5课", [
            ("universidad", "f.", "大学", "daily", "日常交流", "Estudio en la Universidad de Pekín.", "我在北京大学学习。"),
            ("facultad", "f.", "系，学院", "daily", "日常交流", "Pertenezco a la facultad de lenguas.", "我属于外国语学院。"),
            ("clase", "f.", "课，班级", "daily", "日常交流", "Tenemos clase a las ocho.", "我们八点上课。"),
            ("aula", "f.", "教室", "daily", "日常交流", "El aula está limpia y ordenada.", "教室干净整洁。"),
            ("lección", "f.", "课，课文", "grammar", "动词介词", "Repasamos la lección cinco.", "我们复习第五课。"),
            ("texto", "m.", "课文，文章", "grammar", "动词介词", "Leemos el texto en voz alta.", "我们大声朗读课文。"),
            ("ejercicio", "m.", "练习", "grammar", "动词介词", "Hacemos los ejercicios de gramática.", "我们做语法练习。"),
            ("fácil", "adj.", "容易的", "grammar", "动词介词", "El examen fue muy fácil.", "考试非常容易。"),
            ("difícil", "adj.", "困难的", "grammar", "动词介词", "La pronunciación de la erre es difícil.", "辅音r的发音比较难。"),
            ("estudiar", "v.tr.", "学习", "grammar", "动词介词", "Estudiamos con mucha dedicación.", "我们非常认真地学习。"),
            ("leer", "v.tr.", "阅读，朗读", "grammar", "动词介词", "Me gusta leer novelas clásicas.", "我喜欢读经典小说。"),
            ("escribir", "v.tr.", "书写，写作", "grammar", "动词介词", "Escribo una carta a mi amigo.", "我给朋友写了一封信。"),
            ("escuchar", "v.tr.", "倾听，收听", "grammar", "动词介词", "Escuchamos la grabación atentamente.", "我们仔细听录音。"),
            ("hablar", "v.intr.", "说话，说", "grammar", "动词介词", "Hablamos español en clase.", "我们在课上说西班牙语。"),
            ("comprender", "v.tr.", "理解，懂", "grammar", "动词介词", "Comprendo toda la explicación.", "我听懂了所有讲解。"),
        ]),
        ("第6课", [
            ("familia", "f.", "家庭，家族", "daily", "日常交流", "Mi familia es muy unida.", "我的家庭非常和睦。"),
            ("padre", "m.", "父亲", "daily", "日常交流", "Mi padre es ingeniero.", "我父亲是工程师。"),
            ("madre", "f.", "母亲", "daily", "日常交流", "Mi madre cocina muy bien.", "我母亲做饭很好吃。"),
            ("abuelo", "m.", "祖父，外祖父", "daily", "日常交流", "Mi abuelo tiene ochenta años.", "我爷爷八十岁了。"),
            ("abuela", "f.", "祖母，外祖母", "daily", "日常交流", "Mi abuela nos cuenta historias.", "我奶奶给我们讲故事。"),
            ("nieto", "m.", "孙子，外孙", "daily", "日常交流", "Tiene dos nietos encantadores.", "他有两个可爱的孙子。"),
            ("sobrino", "m.", "侄子，外甥", "daily", "日常交流", "Mi sobrino empieza la escuela primaria.", "我侄子上小学了。"),
            ("primo", "m.", "表兄弟，堂兄弟", "daily", "日常交流", "Juego al ajedrez con mi primo.", "我和表哥下国际象棋。"),
            ("trabajar", "v.intr.", "工作", "business", "职场商务", "Trabaja en una empresa extranjera.", "他在一家外企工作。"),
            ("vivir", "v.intr.", "生活，居住", "daily", "日常交流", "Vivo en el centro de la ciudad.", "我住在市中心。"),
            ("tener", "v.tr.", "有，拥有", "grammar", "动词介词", "Tengo veinte años.", "我今年二十岁。"),
            ("año", "m.", "年，岁", "daily", "日常交流", "Tiene veinticinco años.", "他二十五岁。"),
            ("edad", "f.", "年龄", "daily", "日常交流", "¿Qué edad tienes?", "你多大年纪？"),
            ("joven", "adj./m./f.", "年轻的；年轻人", "emotion", "情绪性格", "Es un escritor muy joven y talentoso.", "他是一位年轻有才华的作家。"),
            ("anciano", "adj./m.", "年迈的；老人", "emotion", "情绪性格", "Ayudamos a los ancianos a cruzar.", "我们帮助老年人过马路。"),
        ]),
        ("第7课", [
            ("hoy", "adv.", "今天", "daily", "日常交流", "Hoy hace un día estupendo.", "今天天气非常好。"),
            ("ayer", "adv.", "昨天", "daily", "日常交流", "Ayer fui a la biblioteca.", "昨天我去了图书馆。"),
            ("mañana", "adv./f.", "明天；早晨", "daily", "日常交流", "Nos vemos mañana por la mañana.", "明天早晨见。"),
            ("lunes", "m.", "星期一", "daily", "日常交流", "El lunes empezamos nuevo curso.", "星期一我们开始新课程。"),
            ("martes", "m.", "星期二", "daily", "日常交流", "El martes tenemos examen.", "周二我们有考试。"),
            ("miércoles", "m.", "星期三", "daily", "日常交流", "El miércoles juego al fútbol.", "周三我踢足球。"),
            ("jueves", "m.", "星期四", "daily", "日常交流", "El jueves por la tarde descanso.", "周四下午我休息。"),
            ("viernes", "m.", "星期五", "daily", "日常交流", "El viernes por la tarde descansamos.", "周五下午我们休息。"),
            ("sábado", "m.", "星期六", "daily", "日常交流", "El sábado salgo con amigos.", "周六我和朋友出去。"),
            ("domingo", "m.", "星期日", "daily", "日常交流", "El domingo vamos al campo.", "星期日我们去乡村。"),
            ("hora", "f.", "小时，钟点", "daily", "日常交流", "¿Qué hora es ahora mismo?", "现在是几点钟？"),
            ("minuto", "m.", "分钟", "daily", "日常交流", "Espérame cinco minutos.", "等我五分钟。"),
            ("temprano", "adv.", "早地", "daily", "日常交流", "Me despierto muy temprano cada día.", "我每天起得很早。"),
            ("tarde", "adv./f.", "晚；下午", "daily", "日常交流", "Llegó tarde a la cita.", "他约会迟到了。"),
            ("semana", "f.", "星期，周", "daily", "日常交流", "Nos vemos la próxima semana.", "我们下周见。"),
        ]),
        ("第8课", [
            ("ciudad", "f.", "城市", "travel", "旅行交通", "Barcelona es una ciudad cosmopolita.", "巴塞罗那是一座国际大都市。"),
            ("calle", "f.", "街道", "travel", "旅行交通", "Cruza la calle con cuidado.", "小心过马路。"),
            ("plaza", "f.", "广场", "travel", "旅行交通", "La Plaza Mayor está llena de turistas.", "马约尔广场挤满了游客。"),
            ("parque", "m.", "公园", "travel", "旅行交通", "Paseamos por el parque al atardecer.", "傍晚我们在公园里散步。"),
            ("museo", "m.", "博物馆", "travel", "旅行交通", "El Museo del Prado tiene obras maestras.", "普拉多博物馆收藏了无数杰作。"),
            ("hospital", "m.", "医院", "daily", "日常交流", "El hospital está cerca de aquí.", "医院离这儿不远。"),
            ("banco", "m.", "银行；长凳", "business", "职场商务", "Voy al banco a cambiar divisas.", "我去银行换外汇。"),
            ("cerca", "adv.", "近", "grammar", "动词介词", "Mi escuela está muy cerca.", "我的学校非常近。"),
            ("lejos", "adv.", "远", "grammar", "动词介词", "El aeropuerto queda bastante lejos.", "机场离得相当远。"),
            ("salir", "v.intr.", "出来，出发", "grammar", "动词介词", "Salimos de casa a las siete.", "我们七点从家里出发。"),
            ("entrar", "v.intr.", "进入", "grammar", "动词介词", "Entramos en el edificio silenciosos.", "我们安静地走进了大楼。"),
            ("ir", "v.intr.", "去，前往", "grammar", "动词介词", "Voy a la biblioteca central.", "我去市中心图书馆。"),
            ("venir", "v.intr.", "来，到来", "grammar", "动词介词", "¿Vienes conmigo al concierto?", "你跟我一起去音乐会吗？"),
            ("avenida", "f.", "大道，林荫道", "travel", "旅行交通", "Caminamos por una amplia avenida.", "我们漫步在一条宽阔的大道上。"),
            ("cine", "m.", "电影院；电影", "daily", "日常交流", "Vamos al cine los viernes.", "我们周五常去看电影。"),
        ]),
        ("第9课", [
            ("comprar", "v.tr.", "买", "daily", "日常交流", "Voy a comprar fruta fresca.", "我要去买新鲜水果。"),
            ("vender", "v.tr.", "卖", "business", "职场商务", "Venden libros antiguos en la plaza.", "他们在广场上卖旧书。"),
            ("tienda", "f.", "商店", "daily", "日常交流", "Entramos en una tienda de ropa.", "我们走进一家服装店。"),
            ("mercado", "m.", "市场", "daily", "日常交流", "El mercado municipal abre temprano.", "市政集市开门很早。"),
            ("precio", "m.", "价格", "business", "职场商务", "El precio de este abrigo es razonable.", "这件大衣的价格很合理。"),
            ("dinero", "m.", "钱", "business", "职场商务", "No llevo mucho dinero encima.", "我身上没带很多钱。"),
            ("caro", "adj.", "昂贵的", "daily", "日常交流", "Este restaurante es demasiado caro.", "这家餐馆太贵了。"),
            ("barato", "adj.", "便宜的", "daily", "日常交流", "Compré un diccionario muy barato.", "我买到一本很便宜的词典。"),
            ("camisa", "f.", "衬衫", "daily", "日常交流", "Lleva una camisa blanca limpia.", "他穿了一件干净的白衬衫。"),
            ("pantalón", "m.", "裤子", "daily", "日常交流", "Compré un pantalón azul marino.", "我买了一条藏青色裤子。"),
            ("vestido", "m.", "连衣裙", "daily", "日常交流", "El vestido le sienta de maravilla.", "这条连衣裙她穿起来美极了。"),
            ("falda", "f.", "短裙", "daily", "日常交流", "Lleva una falda plisada elegante.", "她穿了一条优雅的百褶裙。"),
            ("zapatos", "m.pl.", "鞋子", "daily", "日常交流", "Estos zapatos me quedan cómodos.", "这双鞋穿起来很舒适。"),
            ("pagar", "v.tr.", "付款", "business", "职场商务", "¿Puedo pagar con tarjeta de crédito?", "我可以用信用卡付款吗？"),
            ("costar", "v.intr.", "花费，价格为", "business", "职场商务", "¿Cuánto cuesta este reloj?", "这只表要多少钱？"),
        ]),
        ("第10课", [
            ("comida", "f.", "食物；午饭", "food", "美食餐饮", "La comida española es deliciosa.", "西班牙美食非常可口。"),
            ("desayuno", "m.", "早餐", "food", "美食餐饮", "El desayuno incluye café con leche.", "早餐包含牛奶咖啡。"),
            ("almuerzo", "m.", "午餐", "food", "美食餐饮", "Tomamos un almuerzo ligero al mediodía.", "中午我们吃了一顿便午餐。"),
            ("cena", "f.", "晚餐", "food", "美食餐饮", "Cenamos en familia a las nueve.", "九点我们一家人共进晚餐。"),
            ("desayunar", "v.intr.", "吃早餐", "food", "美食餐饮", "Desayuno fruta y tostadas.", "我早餐吃水果和烤面包片。"),
            ("almorzar", "v.intr.", "吃午餐", "food", "美食餐饮", "Almorzamos en el comedor universitario.", "我们在大学食堂吃午饭。"),
            ("cenar", "v.intr.", "吃晚餐", "food", "美食餐饮", "Ceno temprano para dormir bien.", "我早点吃晚餐以便睡个好觉。"),
            ("pan", "m.", "面包", "food", "美食餐饮", "Compro una barra de pan caliente.", "我买了一条热腾腾的长棍面包。"),
            ("leche", "f.", "牛奶", "food", "美食餐饮", "Bebo un vaso de leche cada mañana.", "我每天早晨喝一杯牛奶。"),
            ("café", "m.", "咖啡", "food", "美食餐饮", "Un café solo sin azúcar, por favor.", "请来一杯不加糖的浓缩黑咖啡。"),
            ("carne", "f.", "肉", "food", "美食餐饮", "Prefiero la carne de ternera.", "我更喜欢牛肉。"),
            ("pescado", "m.", "鱼肉，鱼", "food", "美食餐饮", "El pescado al horno es una delicia.", "烤鱼是一道美味佳肴。"),
            ("arroz", "m.", "米饭，水稻", "food", "美食餐饮", "La paella lleva arroz y azafrán.", "西班牙海鲜饭里有米饭和藏红花。"),
            ("fruta", "f.", "水果", "food", "美食餐饮", "Comer fruta fresca es saludable.", "吃新鲜水果有益健康。"),
            ("agua", "f.", "水", "food", "美食餐饮", "¿Me da una botella de agua mineral?", "能给我一瓶矿泉水吗？"),
        ]),
        ("第11课", [
            ("tiempo", "m.", "时间；天气", "travel", "旅行交通", "Hace un tiempo maravilloso hoy.", "今天天气好极了。"),
            ("clima", "m.", "气候", "travel", "旅行交通", "El clima mediterráneo es muy agradable.", "地中海气候非常舒适宜人。"),
            ("primavera", "f.", "春季", "travel", "旅行交通", "En primavera florecen todos los campos.", "春天所有的田野都百花盛开。"),
            ("verano", "m.", "夏季", "travel", "旅行交通", "En verano vamos a la playa.", "夏天我们去海滩度假。"),
            ("otoño", "m.", "秋季", "travel", "旅行交通", "Las hojas caen doradas en otoño.", "秋天树叶金黄地飘落。"),
            ("invierno", "m.", "冬季", "travel", "旅行交通", "Nieva con frecuencia en invierno.", "冬天经常下雪。"),
            ("frío", "m./adj.", "寒冷；冷的", "travel", "旅行交通", "Tengo frío, ponte el abrigo.", "我觉得冷，快穿上外套。"),
            ("calor", "m.", "炎热，热度", "travel", "旅行交通", "En agosto hace un calor sofocante.", "八月的天气酷热难耐。"),
            ("lluvia", "f.", "雨水", "travel", "旅行交通", "La lluvia limpia el aire urbano.", "雨水洗净了城市的空气。"),
            ("llover", "v.impers.", "下雨", "grammar", "动词介词", "Empieza a llover con fuerza.", "开始下大雨了。"),
            ("sol", "m.", "太阳", "travel", "旅行交通", "Hace mucho sol esta mañana.", "今天早晨阳光明媚。"),
            ("viento", "m.", "风", "travel", "旅行交通", "Sopla un viento fresco del norte.", "从北方吹来阵阵清凉的风。"),
            ("nieve", "f.", "雪", "travel", "旅行交通", "La montaña está cubierta de nieve.", "山峰被白雪覆盖。"),
            ("nevar", "v.impers.", "下雪", "grammar", "动词介词", "Nieva copiosamente en los Pirineos.", "比利牛斯山脉大雪纷飞。"),
            ("temperatura", "f.", "温度", "travel", "旅行交通", "La temperatura subirá diez grados.", "气温将上升十度。"),
        ]),
        ("第12课", [
            ("cuerpo", "m.", "身体", "daily", "日常交流", "El ejercicio fortalece el cuerpo.", "锻炼使身体强健。"),
            ("cabeza", "f.", "头，头部", "daily", "日常交流", "Me duele un poco la cabeza.", "我头有点痛。"),
            ("ojo", "m.", "眼睛", "emotion", "情绪性格", "Abrió los ojos con sorpresa.", "他惊讶地睁大了眼睛。"),
            ("nariz", "f.", "鼻子", "daily", "日常交流", "Respiró hondo por la nariz.", "他用鼻子深深吸了一口气。"),
            ("boca", "f.", "嘴巴", "daily", "日常交流", "Abre la boca para examinarla.", "张开嘴做检查。"),
            ("mano", "f.", "手", "daily", "日常交流", "Lávate las manos antes de comer.", "饭前要洗手。"),
            ("brazo", "m.", "手臂", "daily", "日常交流", "Me torcí el brazo derecho.", "我扭伤了右手臂。"),
            ("pierna", "f.", "腿", "daily", "日常交流", "Tengo agujetas en las piernas.", "我两条腿酸痛。"),
            ("pie", "m.", "脚，足", "daily", "日常交流", "Fuimos al centro a pie.", "我们步行去了市中心。"),
            ("doler", "v.intr.", "疼痛", "grammar", "动词介词", "Me duele la garganta desde anoche.", "从昨晚起我嗓子就疼。"),
            ("enfermo", "adj./m.", "生病的；病人", "daily", "日常交流", "El enfermo guarda reposo en cama.", "病人在床上静养。"),
            ("salud", "f.", "健康", "daily", "日常交流", "La salud es lo más importante.", "健康是最重要的财富。"),
            ("medicina", "f.", "药物；医学", "daily", "日常交流", "Toma esta medicina tres veces al día.", "这种药每天吃三次。"),
            ("farmacia", "f.", "药房，药店", "daily", "日常交流", "Hay una farmacia de guardia al lado.", "隔壁有一家急诊值班药房。"),
            ("fiebre", "f.", "发烧，发热", "daily", "日常交流", "Tiene treinta y ocho grados de fiebre.", "他发烧三十八度。"),
        ]),
        ("第13课", [
            ("vacaciones", "f.pl.", "假期", "travel", "旅行交通", "Nos vemos después de las vacaciones.", "假期结束后见。"),
            ("viajar", "v.intr.", "旅行", "travel", "旅行交通", "Nos gusta viajar por todo el mundo.", "我们喜欢周游世界。"),
            ("tren", "m.", "火车", "travel", "旅行交通", "Tomamos el tren de alta velocidad.", "我们乘坐高铁。"),
            ("avión", "m.", "飞机", "travel", "旅行交通", "El avión aterriza en Barajas puntual.", "飞机准时降落在巴拉哈斯机场。"),
            ("autobús", "m.", "公共汽车", "travel", "旅行交通", "El autobús de la línea uno va al centro.", "一号线公交车开往市中心。"),
            ("metro", "m.", "地铁", "travel", "旅行交通", "Viajar en metro es rápido y ecológico.", "坐地铁既快捷又环保。"),
            ("coche", "m.", "汽车", "travel", "旅行交通", "Alquilamos un coche para recorrer Andalucía.", "我们租了一辆车游览安达卢西亚。"),
            ("estación", "f.", "车站；季节", "travel", "旅行交通", "La estación de tren está concurrida.", "火车站人流熙熙攘攘。"),
            ("aeropuerto", "m.", "机场", "travel", "旅行交通", "Llegamos al aeropuerto dos horas antes.", "我们提前两小时到达机场。"),
            ("maleta", "f.", "行李箱", "travel", "旅行交通", "Hago la maleta con antelación.", "我提前收拾好了行李箱。"),
            ("pasaporte", "m.", "护照", "travel", "旅行交通", "Muestre su pasaporte en la aduana.", "请在海关出示您的护照。"),
            ("billete", "m.", "车票，机票", "travel", "旅行交通", "Compré un billete de ida y vuelta.", "我买了一张往返票。"),
            ("hotel", "m.", "旅馆，酒店", "travel", "旅行交通", "Nos alojamos en un hotel céntrico.", "我们入住了一家位于市中心的酒店。"),
            ("reservar", "v.tr.", "预订", "business", "职场商务", "Deseo reservar una habitación doble.", "我想预订一间双人房。"),
            ("visitar", "v.tr.", "参观，拜访", "travel", "旅行交通", "Visitamos la Alhambra de Granada.", "我们参观了格拉纳达的阿罕布拉宫。"),
        ]),
        ("第14课", [
            ("deporte", "m.", "体育运动", "daily", "日常交流", "El deporte mejora el estado de ánimo.", "运动能改善心情。"),
            ("jugar", "v.intr.", "玩耍；踢球", "grammar", "动词介词", "Los niños juegan al fútbol alegres.", "孩子们欢快地踢足球。"),
            ("fútbol", "m.", "足球", "daily", "日常交流", "El fútbol levanta grandes pasiones.", "足球运动激发极大的热情。"),
            ("baloncesto", "m.", "篮球", "daily", "日常交流", "Jugamos al baloncesto los sábados.", "我们周六常打篮球。"),
            ("natación", "f.", "游泳", "daily", "日常交流", "La natación relaja toda la espalda.", "游泳能彻底放松背部肌肉。"),
            ("nadar", "v.intr.", "游泳", "daily", "日常交流", "Aprendió a nadar de muy pequeño.", "他从小就学会了游泳。"),
            ("correr", "v.intr.", "跑步", "daily", "日常交流", "Corro media hora cada amanecer.", "我每天清晨慢跑半小时。"),
            ("música", "f.", "音乐", "emotion", "情绪性格", "Escucho música clásica para relajarme.", "我听古典音乐来放松身心。"),
            ("canción", "f.", "歌曲", "emotion", "情绪性格", "Cantamos una canción tradicional.", "我们唱了一首传统民歌。"),
            ("cantar", "v.tr.", "唱歌", "emotion", "情绪性格", "Canta con una voz melodiosa.", "她的歌声婉转悠扬。"),
            ("bailar", "v.intr.", "跳舞", "emotion", "情绪性格", "Aprendieron a bailar flamenco juntos.", "他们一起学会了跳弗拉门戈舞。"),
            ("fiesta", "f.", "节日，聚会", "daily", "日常交流", "Organizamos una fiesta de bienvenida.", "我们组织了一场热烈的欢迎派对。"),
            ("invitar", "v.tr.", "邀请", "daily", "日常交流", "Te invito a tomar un café.", "我请你喝杯咖啡。"),
            ("regalo", "m.", "礼物", "emotion", "情绪性格", "Le compré un regalo de cumpleaños.", "我给她买了一份生日礼物。"),
            ("cumpleaños", "m.", "生日", "daily", "日常交流", "¡Feliz cumpleaños y muchos éxitos!", "祝你生日快乐，万事如意！"),
        ]),
        ("第15课", [
            ("correo", "m.", "邮政；邮件", "daily", "日常交流", "Envíame los datos por correo.", "请把数据通过邮件发给我。"),
            ("carta", "f.", "信件；菜单", "daily", "日常交流", "Escribió una emotiva carta a sus padres.", "他给父母写了一封充满深情的信。"),
            ("teléfono", "m.", "电话", "daily", "日常交流", "Suena el teléfono con insistencia.", "电话急促地响了起来。"),
            ("llamar", "v.tr.", "打电话；叫", "grammar", "动词介词", "Llámame en cuanto llegues a casa.", "你一到家就给我打电话。"),
            ("mensaje", "m.", "短信，信息", "daily", "日常交流", "Recibí tu mensaje de texto.", "我收到了你的短信。"),
            ("internet", "m.", "互联网", "business", "职场商务", "Buscamos información en internet.", "我们在互联网上查找资料。"),
            ("ordenador", "m.", "电脑", "business", "职场商务", "Trabajo toda la jornada con ordenador.", "我整天都在电脑前工作。"),
            ("móvil", "m.", "手机", "daily", "日常交流", "Consulto las noticias en el móvil.", "我在手机上浏览新闻。"),
            ("buscar", "v.tr.", "寻找，查找", "grammar", "动词介词", "Busco las llaves que extravié.", "我在找我弄丢的钥匙。"),
            ("encontrar", "v.tr.", "找到，遇到", "grammar", "动词介词", "Al fin encontré lo que buscaba.", "我终于找到了我要找的东西。"),
            ("enviar", "v.tr.", "寄送，发送", "grammar", "动词介词", "Envío el paquete por correo certificado.", "我通过挂号信寄出包裹。"),
            ("recibir", "v.tr.", "接收，收到", "grammar", "动词介词", "Recibí una grata sorpresa hoy.", "我今天收到了一份意外的惊喜。"),
            ("número", "m.", "号码，数字", "daily", "日常交流", "¿Cuál es tu número de teléfono móvil?", "你的手机号码是多少？"),
            ("tarjeta", "f.", "卡片，名片", "business", "职场商务", "Intercambiamos tarjetas profesionales.", "我们交换了商务名片。"),
            ("usar", "v.tr.", "使用", "grammar", "动词介词", "Usa el diccionario para consultar dudas.", "用词典查阅疑难问题。"),
        ]),
        ("第16课", [
            ("costumbre", "f.", "风俗，习惯", "daily", "日常交流", "Es una vieja costumbre popular.", "这是一项古老的民间习俗。"),
            ("cultura", "f.", "文化", "emotion", "情绪性格", "Respetamos la diversidad de cada cultura.", "我们尊重每一种文化的多元性。"),
            ("tradición", "f.", "传统", "daily", "日常交流", "Mantienen viva una hermosa tradición.", "他们让这一优良传统薪火相传。"),
            ("país", "m.", "国家", "travel", "旅行交通", "España es un país de rica historia.", "西班牙是一个历史悠久的国家。"),
            ("nacionalidad", "f.", "国籍", "daily", "日常交流", "¿Cuál es su nacionalidad oficial?", "请问您的官方国籍是什么？"),
            ("mundo", "m.", "世界", "travel", "旅行交通", "Viajó por todo el ancho mundo.", "他周游了广袤的全世界。"),
            ("idioma", "m.", "语言", "daily", "日常交流", "El español es un idioma universal.", "西班牙语是一种世界性语言。"),
            ("lengua", "f.", "语言；舌头", "daily", "日常交流", "El castellano es la lengua oficial.", "卡斯蒂利亚语是官方语言。"),
            ("aprender", "v.tr.", "学习，学会", "grammar", "动词介词", "Deseo aprender a expresarme con soltura.", "我想学会自如流畅地表达。"),
            ("recordar", "v.tr.", "记住，记起", "grammar", "动词介词", "Aún recuerdo nuestro primer encuentro.", "我依然记得我们的第一次相遇。"),
            ("olvidar", "v.tr.", "忘记", "grammar", "动词介词", "Nunca olvidaré tu valiosa ayuda.", "我绝不会忘记你宝贵的帮助。"),
            ("pueblo", "m.", "人民；村庄", "daily", "日常交流", "El pueblo conserva su encanto colonial.", "这座小镇保留着殖民时期的风貌。"),
            ("extranjero", "adj./m.", "外国的；外国人", "travel", "旅行交通", "Vivió tres años en el extranjero.", "他在国外生活了三年。"),
            ("celebrar", "v.tr.", "庆祝，举行", "emotion", "情绪性格", "Celebramos el éxito con entusiasmo.", "我们满怀热情地庆祝胜利。"),
            ("entender", "v.tr.", "理解，听懂", "grammar", "动词介词", "Entiendo el sentido general del texto.", "我理解这篇课文的大意。"),
        ]),
    ]),
]

print("Ready to run generation")
